### ISSUE TITLE
Redirected responses don't follow allowed_domains

### ISSUE THREAD

**Issue by tarunlalwani** [scrapy/scrapy#1042]
Hi,

If we add allowed_domains and a url from the same domain gets redirected to another domain, then the results for that domain also get processed, which I believe should be filtered

allowed_domains = ('www.knowledgeinbox.com', )

url = "http://www.knowledgeinbox.com/books/"

The url redirects to www.tarlabs.com. The result is still passed to my function which is only interested in knowledgeinbox.com. Not sure if this intentional, as per my understanding its a bug

Please let me know your thoughts

Regards,
Tarun

**Comment by Granitas** [comment]
I don't think it's a bug. There's no way for the spider to know whether the link is being redirected until the link is called in the request queue.

You can set spider setting `REDIRECT_ENABLED = False` to disable redirects.

**Comment by tarlabs** [comment]
I am not saying it should not follow the redirect. What I am saying is that it does download a URL eventually which is not in allowed_domain and calls the parse_item. We are using rules to automatically add the links to be processed. I assumed that even if redirect was going to another domain, I assumed that my callback will not be called. Disabling Redirects is not a solutions as such, because it would disable valid redirects within the same domain

**Comment by Digenis** [comment]
OffsiteMiddleware which uses the allowed_domains is implemented as a spidermiddleware.
Not only its place in the middleware stack prevents it from filtering redirects but also its implementation.
You need a downlaoder middleware placed just after the redirect middleware.

Because of its simple implementation,
it's possible to refactor it to something more abstract
that has the methods of both spider and downloader middlware.

Does anyone object to such refactoring of OffsiteMiddleware upstream?
I would use it.

**Comment by redapple** [comment]
Related: https://github.com/scrapy/scrapy/issues/2241

**Comment by Gallaecio** [comment]
Quick-and-dirty downloader middleware to work around this, for easy copy-pasting:

```python
from scrapy.exceptions import IgnoreRequest
from scrapy.spidermiddlewares.offsite import OffsiteMiddleware as OffsiteSpiderMiddleware

class OffsiteDownloaderMiddleware(OffsiteSpiderMiddleware):

    def process_request(self, request, spider):
        result = list(self.process_spider_output(None, [request], spider))
        if not result:
            raise IgnoreRequest
        return None
```

**Comment by sivang** [comment]
Is this still open issue (given it was created in 2015? )
