### ISSUE TITLE
Issue with CsvItemExporter when used as Feed Exporter with a crawler that yields more than one type of Item

### ISSUE THREAD

**Issue by aaearon** [scrapy/scrapy#1050]
My project includes a spider that yields several different types of Items. All my items inherit from a 'DefaultItem' that has fields such as 'url', 'time_crawled' and 'group_id'.

When defining `FEED_FORMAT = 'csv'`, the feed exporter uses the fields of the first type of Item yielded as the csv's header/column names and then for subsequent yielded items (despite the Item's type) tries to export those items with the fields of the first yielded item.

Since all of the items have 'url', 'time_crawled', 'group_id' and fields that may share the same names, those columns in the CSV get exported but otherwise the column for particular field is empty.

```tim@lindev:~/kkc$ scrapy -v
Scrapy 0.24.4 - project: kkc```

**Comment by nyov** [comment]
That could be termed undefined behavior.
It's really not so possible to do what you want, the way the code works now, because if that would be handled the Exporter couldn't start exporting until the whole crawl is finished, to be certain it has "seen" all the possible Items that can be exported before building a CSV header column.

You should write a custom Pipeline to define your required behavior.

**Comment by nramirezuy** [comment]
I think we can merge a PR of a csv headers setting.
