### ISSUE TITLE
dependency on requests library / urllib python3 compatibility

### ISSUE THREAD

**Issue by nyov** [scrapy/scrapy#1115]
Would it be possible to have a dependency against requests (Apache 2 licensed) in Scrapy?

I noticed that it has superior proxy env handling, where urllib fails to parse IPs or CIDR in a `$no_proxy` variable. This has led to failing testcases for me and I'd like to fix it.

Also, requests provides a nice [`compat` module](https://github.com/kennethreitz/requests/blob/383b20b02324e5c5d1970dd3ab0ba29bd991d2b2/requests/compat.py#L35-L62), wrapping urllib/2 for PY2 and PY3 differences.
If not a dependency, could scrapy do this stuff similarly?
Pulling in urllib/urllib2/urlparse from a local wrapper seems cleaner than throwing `six.moves.` and `try...except` statements everywhere we use them. And we have plenty of those imports.

**Comment by kmike** [comment]
I like `from six.moves.urllib.parse import urlparse` more than `from compat import urlparse` because `six.moves` is kind-of standard, and you can just delete "six.moves" when dropping Python 2.x support. We're already using six for a lot of things, and some Scrapy dependencies also use six - I don't like duplicating its features in a custom compat.py module.

requests is a big library with a lot of features; pulling it just for proxy env variables parsing looks like an overkill.

**Comment by nyov** [comment]
This is true, for only pulling the proxy env fix, requests would be too heavy.
I was also considering the other useful workarounds to urllib that are already solved in there (for example correct support for IP/CIDR in proxy env requires some IP subnet calculation functions and such).

It's noone is considering this proxy issue a bug :( Cpython/urllib would also consider it a feature request. Even though it [wrongly proxies requests for 127.0.0.0/8](https://gist.github.com/nyov/b64dd1b5fe22dfd9784e), which I see as a pretty obvious issue (security implications).

But I will fix more urllib references the `six` way, in #1121 now.
