### ISSUE TITLE
Allow FEED_EXPORT_FIELDS to be specified per Item rather than for the whole project

### ISSUE THREAD

**Issue by demelziraptor** [scrapy/scrapy#1213]
This setting was added in this commit: https://github.com/scrapy/scrapy/commit/1534e8540bf083c8d7beb0264cccea5488ee0250

But it would be more useful to define per Item.  Maybe change it to a dict and have the Item name as the key?  Or a new attribute for the Item class?

**Comment by kmike** [comment]
`FEED_EXPORT_FIELDS` option was added for 2 main reasons:

1. It is not possible to know all possible fields in advance (because items are processed on-by-one), but we need to know it to write a CSV header. With a single Item class a set of its defined fields can be used. But when several item classes this doesn't work, and `FEED_EXPORT_FIELDS` allows to specify which fields should be in result. 

2. In Scrapy master it is possible to yield raw dicts instead of Item instances; FEED_EXPORT_FIELDS allows to define fields to export for the cases dicts have different keys (e.g. when keys for empty values are omitted).

(1) won't work if you define `FEED_EXPORT_FIELDS` per Item class. 

A set of fields defined in Item is essentially a per-item `FEED_EXPORT_FIELDS`. 
Do you want to skip some fields on export time even if they are defined?

**Comment by demelziraptor** [comment]
I see what you mean.  I have a requirement at the moment that feed exports are csv format and that the fields remain in the same order (currently using a custom exporter to do this).  Spiders only use one item each, so defining via the Item is not an issue.  Maybe define these fields in the Spider instead?

**Comment by kmike** [comment]
In scrapy master it is possible to override settings per-spider - see http://doc.scrapy.org/en/master/topics/settings.html#settings-per-spider.

**Comment by demelziraptor** [comment]
I keep forgetting this!  Thank you!
