### ISSUE TITLE
PIL instead of Pillow

### ISSUE THREAD

**Issue by timschwab** [scrapy/scrapy#1323]
I don't know if this qualifies as an issue, but I've noticed that Scrapy uses PIL rather than Pillow for its image manipulations. For example, for the ImagesPipeline. Development in PIL stopped in 2009, but Pillow, a fork of PIL, is now the new standard. This seems to be what I've gathered from the [Intertubes](http://stackoverflow.com/a/10109941/1455074) and [Wikipedia](https://en.wikipedia.org/wiki/Python_Imaging_Library).

This isn't a huge deal, but I have been having some issues with PIL. They are fixable, but will get worse as time progresses.

**Comment by kmike** [comment]
Yeah, you're right that Pillow should be preferred to PIL, and Scrapy already [recommends](http://doc.scrapy.org/en/latest/topics/media-pipeline.html#using-the-images-pipeline) Pillow over PIL. 

PIL and Pillow use the same import name (`PIL`). Is it `import PIL` which made you think Scrapy uses PIL rather than Pillow?

**Comment by timschwab** [comment]
Ah, yes that is indeed why I thought that. Okay then, my mistake.
