### ISSUE TITLE
Need urgent help! Scrapy: command not found

### ISSUE THREAD

**Issue by ikansal2** [scrapy/scrapy#1332]
I am trying to use scrapy to build a web crawler. I am using it on Mac OS yosemite and after installing scrapy I tried to run the program given on the scrapy website. But when I try to run it, terminal says scarpy: command not found. I really need help and quick help! Please. I think my scrapy is installed in a different path but I don't know how to change it so that it works.

**Comment by curita** [comment]
Hi @ikansal2! Following the [installation guide](http://scrapy.readthedocs.org/en/latest/intro/install.html#installing-scrapy) (basically running `pip install Scrapy` after installing `pip`) installs Scrapy successfully in that OS.

Since this doesn't seem like a bug because it's probably something with your configuration or the way you installed it I'm going to close the issue and prompt you to ask for user support either in our mailing list https://groups.google.com/forum/#!forum/scrapy-users or Stack Overflow: http://stackoverflow.com/questions/tagged/scrapy.

If you isolate the problem and find out that we need to update the documentation or it's any other bug directly related with Scrapy please open up the issue with those details!
