### ISSUE TITLE
Can't install on OSX 10.10.4

### ISSUE THREAD

**Issue by jooddang** [scrapy/scrapy#1342]
[jooddang@a ~]$ scrapy startproject tutorial
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/Library/Python/2.7/site-packages/scrapy/__init__.py", line 48, in <module>
    from scrapy.spiders import Spider
  File "/Library/Python/2.7/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Library/Python/2.7/site-packages/scrapy/http/__init__.py", line 12, in <module>
    from scrapy.http.request.rpc import XmlRpcRequest
  File "/Library/Python/2.7/site-packages/scrapy/http/request/rpc.py", line 7, in <module>
    from six.moves import xmlrpc_client as xmlrpclib
ImportError: cannot import name xmlrpc_client

================
On Python console

>>> import scrapy 

makes error - can't import _monkeypatches module

**Comment by nautilus28** [comment]
How did you install Scrapy?

**Comment by jooddang** [comment]
I couldn't install 1.0.1 but 0.24.2.

**Comment by curita** [comment]
Please install latest patch for that release (which is 0.24.6) to fix that error, it seems like the version of `six` you have in your system is too old.

If you installed scrapy with pip, run `pip install -U Scrapy==0.24.6` to upgrade it.

I'm closing this issue since we provide support for minor releases through patch versions, it's expected that 0.24.2 has errors that have been fixed in following 0.24.x patches. If you encounter the same error in 0.24.6 please reopen the issue so we can fix it.

**Comment by jooddang** [comment]
I'm sorry I guess my comment drove you wrong.
The error message above was shown after I tried to install scrapy 1.0.1. It seemed like it was installed without any problem but the error message was shown. After I installed 0.24.2, I don't get any error message. 
What I'm saying is that there's still a problem with 1.0.1.

**Comment by curita** [comment]
Sorry about that then, now I'm wondering why `six` wasn't updated while installing scrapy.

How did you install 1.0.1? Can I ask you to install it again and let us see the output of `scrapy version -v` and `python -c 'import six; print six.__version__'` so we can confirm the versions of the dependencies?

**Comment by curita** [comment]
Ok, I found out why `six` wasn't upgraded in OS X: pypa/pip#2468.

This is an issue when using the python provided by OS X - `six` is already present system wide in `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python`, but pip installs and upgrades libraries in `/Library/Python/2.7/site-packages`. Problem is, `"/System/..."` is listed in sys.path before `"/Library/..."`, so when scrapy uses `six` is using the one that comes with OS X in the first directory, which is 1.4.1 if you're using yosemite, instead of the new version of it installed in the second path.

@nautilus28: One way of fixing this is by running `export PYTHONPATH="/Library/Python/2.7/site-packages"` in your terminal (or even better, adding that line to your `~/.bashrc` file so it's automatically run) before running `pip install -U scrapy`, but I think the best solution is installing a newer version of python with one of the unofficial package managers of OS X like homebrew or macports.

I'm going to write an OS X installation section in the docs mentioning the possible workarounds so we can point them to the users. Thanks @nautilus28 for reporting the issue, I'm going to double check again before closing any new ones ;)

**Comment by jooddang** [comment]
I installed 1.0.1 by 
$ sudo pip install scrapy

And, pip list shows that
> pyOpenSSL (0.15.1)
> six (1.9.0)
> w3lib (1.11.0)
> lxml (3.4.4)

**Comment by darkrho** [comment]
I'd suggest to include `conda` (either through anaconda or miniconda distributions) as the recommended method to install scrapy instead of messing with system-wide packages in OS X.

**Comment by darkrho** [comment]
For testing purposes, I've published scrapy in my conda channel, it can be installed by using:

```
$ conda install -c https://conda.anaconda.org/rolando/ scrapy
```

There are packages for the platforms: `linux-32`, `linux-64` and `osx-64`.

**Comment by itranga** [comment]
please try easy_install six
