### ISSUE TITLE
Investigate Slack integration

### ISSUE THREAD

**Issue by curita** [scrapy/scrapy#1372]
I know we talked about this before internally, and it's not a development issue, but I wanted to create a ticket to track it somehow and get more feedback.

I'd love to have a [Slack](https://slack.com/) channel for Scrapy since that's where most of Scrapinghub inter-company communication takes place, I'm sure it'd be a lot easier to provide Scrapy support if we used it (and personally I'm not very fond of IRC).

I think this is possible, I just stumbled upon this repo: [gamechanger/dusty](https://github.com/gamechanger/dusty) which uses this `slacking` app (http://rauchg.com/slackin/) to create a "public" (through invite) channel for the project. I kind of like the approach, and I think it's worth at least investigating it to integrate it to our current work env.

**Comment by nyov** [comment]
> and personally I'm not very fond of IRC

:((((

but I can understand why to some extend. Love the freedom of it though.
Looked at Slack, but since it looks so very team-oriented I didn't try it. Also no Linux client. So I can't give any feedback on this yet.
Does it actually make sense to sign up without a team, being a 1-person team?
Wouldn't mind to chat with some again, who don't hang out on IRC anymore, but don't want g+.

**Comment by barraponto** [comment]
Yeah, i too feel sad that IRC is being left behind in favor of a proprietary linux-unfriendly service.

**Comment by Linuxhombre** [comment]
Agreed :/

On 7/21/15 7:08 AM, Capi Etheriel wrote:
>
> Yeah, i too feel sad that IRC is being left behind in favor of a 
> proprietary linux-unfriendly service.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scrapy/scrapy/issues/1372#issuecomment-123323560>.
>

-- 
Joshua M. Feldman


skype: LinuxHombre
tel: 1-424-283-0045
www.linkedin.com/in/feldmanj/en

**Comment by jdemaeyer** [comment]
Just because Slack itself doesn't offer a native linux client doesn't mean it's linux-unfriendly. There are two mature, actively maintained Linux Slack clients out there ([ScudCloud](https://github.com/raelgc/scudcloud) and [plaidchat](https://github.com/plaidchat/plaidchat)), plus the web interface, plus an IRC gateway (so you can connect to the Slack channel just like you connect to the freenode channel).

It is indeed hard (if they haven't used IRC yet), or at least annoying (if they don't regularly use IRC), for most users to seek help in the IRC channel, and if Socket.IO has had such tremendous success with a public Slack community, I think it's a great opportunity to boost Scrapy user support as well.

**Comment by Digenis** [comment]
> and if Socket.IO has had such tremendous success with a public Slack community

Let's not make decisions based on assumptions

> It is indeed hard (if they haven't used IRC yet), or at least annoying (if they don't regularly use IRC), for most users to seek help in the IRC channel

If by users you mean just any computer user, I may agree.
But in our case, they are coders at least.
The python community uses IRC and mailing lists extensively.
Such users are pushed back by this transition.
Maybe it will manage to provide support to new users, but different users.
I am afraid it will actually repel coders in favour of another audience,
users who are more likely to ask for solutions to their problems
before they RTFM. (Excuse me for the term,
but I think it's an necessary rite going extinct)

Regarding the IRC gateway, I doubt it's going to be functional.
Once non-IRC features sneak-in, it will become unusable for IRC users.
And what exactly are those features?
Does the scrapy community need them?
Does the **scrapy** community consist of non-IT people?
I am sure scrapy users have their clients or managers who are interested in web scraping
but clients/managers are not IT.
They are not concerned what the scrapy community uses to communicate
they are concerned with their contractors/employees getting their job done
and they will use the communication means that **they** prefer.
For many users/programmers out of scrapinghub,
slack is going to be yet another system for communication.

Let's assume a non-IT person wanted to ask "I am looking for a contractor..."
and didn't because he/she couldn't use IRC.
Would the scrapy community be the right place to ask?
(Isn't the commercial support link on the site obvious?)

Let's assume someone wants to upload a **screenshot of a stacktrace** (?!!)
and doesn't because he/she can't be bothered to upload somewhere else
and post the link to IRC.
Would he/she be the right person to answer to?

I don't want to be rude and I hope my email doesn't read on an aggressive tone.
I just want to respond to the call for feedback made by @curita
and argue that the community has no problem, especially none that would be solved by Slack.
We are mostly programmers doing our work
and I find it very nice to only occupy a tmux window for IRC,
where I can attend various python (& other FOSS) communities
instead of running another tab on the browser,
next to some web applications a client/manager needs me to use. 


P.S. sorry for the long email

**Comment by jdemaeyer** [comment]
>> and if Socket.IO has had such tremendous success with a public Slack community

> Let's not make decisions based on assumptions

From the [link](http://rauchg.com/slackin/) @curita posted:
> In less than two weeks, we already had a community of more than 400 users. Not only did it *dramatically* outpace the growth rate of our IRC server, but it fostered a much stronger sense of community. I’ve already seen a great exchange of technical knowledge, new ideas and even business opportunities for those involved.

Sounds like a tremendous success to me ;). I'd also say the average Socket.IO user is at least as (probably even more) tech-savvy as the average Scrapy user, and apparently switching to Slack has not at all resulted in a degradation of the community to a free tech support team for them.

For your other questions: Yes, I think the Scrapy community is a great place to ask for contractors. And yes, someone who posts screenshots of a stacktrace is definitely the right person to answer to: we've all started with no clue whatsoever at some point. But I guess this boils down us having different ideas of what a healthy community looks like, and that's alright. :)

**Comment by nyov** [comment]
I think any slack vs irc discussion isn't really relevant. It's a different communication platform. The more presence the better, usually. It's not really one versus the other, though some small fracturing of supporter base may result. People will continue to use IRC.
But there are people on Slack which are not on IRC, already, and the question is only whether to provide a "public channel" to them.
I'd say go for it, using slackin or building a custom integration looks reasonably easy, though I am unaware what constitutes "integrate[ing] it to our current work env".

My intent wasn't to sidetrack this to a discussion pro/contra IRC, just a general expression of sadness that not everyone can like IRC. But I grew up with it, nowadays people grow up with the notion "Internet==Web" and having profile pages to manage their account settings, so messaging some bot on IRC may be alien to them. (Though knowing irc has been a skill for life. It's been around since I got my first modem and while other services come and go, irc is likely still around for the rest of mine.)

Assuming those people, who would choose this medium over IRC, are computer-illiterate is bogus. (I'd sure work with @curita anytime, or any of the scrapinghubbers not in `#scrapy` anymore.) And clicking on a [webchat button](http://scrapy.org/community/) is dead simple, being on IRC doesn't confirm a persons tech-savvyness.
Besides, lowering the entry-level communications barrier with curious management-level types is exactly what they should be looking for as a company and a no-obligations hangout is probably a good thing for that.

All that aside there seem to be some [drawbacks](http://kukuruku.co/hub/pm/how-to-share-a-channel-between-slack-teams) to being an invited guest to a slack team -- e.g. losing all the chat history when getting booted off, which wouldn't happen with irc, or even email. Though maybe there is a way around that, similar to an IRC log bot.

But I would give it a try for some casual hanging out. So let me know when I can get an invite or beta-test this integration. You have my mail ;)

**Comment by barraponto** [comment]
if I can connect to slack through IRC, then I can definitely log it and even use my bouncer.
so, as far as i'm concerned, it's a matter of moving from freenode to slack.
as for "being the next thing", let's no forget what happened to Hipchat, the last next thing in chats.

**Comment by cyberplant** [comment]
It finally not depends on if YOU (or somebody else) can connect through IRC. I like this idea, because IRC is old fashioned and people is a bit scared about that.

Also, lots of different companies are now using slack for work, so they already have the clients configured, that makes it even easier.

And well, about me.. I started using IRC in 1995, even created a couple of bots who lasted for many years, so I know it pretty well.

**Comment by Digenis** [comment]
@jdemaeyer 
>  And yes, someone who posts screenshots of a stacktrace is definitely the right person to answer to: we've all started with no clue whatsoever at some point.

I said the opposite

> Let's assume someone wants to upload a screenshot of a stacktrace (?!!)
**and doesn't** because he/she **can't be bothered** to upload somewhere else

I don't argue that we shouldn't answer. I will.
And also suggest to upload as text to some pastebin.
My point is that **helping** upload images paves paths to laziness
(not "laziness" as a programmer's quality).

---

Personally I believe the "user support boost" is all about marketing,
using a communication platform with a more fancy/captivating experience.
The rest, "fondness", "fashion" and "fear" are not my kind of arguments.
More valid bug reports, more acceptable patches. Are these an expectation?
Just think of pypy, twisted, django or other successful python projects
who all manage very well with mailing lists and IRC.

**Comment by cyberplant** [comment]
How I see it's a bit different. We have some people that can help, and people that want to ask questions, and both don't want to use IRC. 

So, having something like Slack can help those people to meet! :smiley_cat: 

And one example is me, I used to have weechat in one screen window, but as all the interesting channels I used to visit are now dead, I don't have it anymore. But I always have Slack open for work.

**Comment by hkdobrev** [comment]
Hi! Is there any development on this? Do you know of some ways to connect Scrapy or Scrapy cloud to Slack even via webhooks? Thank!

**Comment by ttilberg** [comment]
One thing that might not be on the mind of folks who are lukewarm on slack (looking at above comments from 2015) -- It's a very easy, free way to make cross platform push notifications to whatever device you are on (desktop, phone, etc).

I have a few ruby scraping processes that send certain messaging to a channel in Slack. I find the ability to receive push notifications related to monitoring incredibly useful.

I arrived on this page when looking to see if someone already made a `StatsMailerSlack` type middleware. I found this other project that seems to provide this functionality: https://github.com/ericvalente/scrapy_logs_to_slack

**Comment by jdemaeyer** [comment]
Given the latest comments and the fact that googling "Scrapy Slack" leads here, maybe a little clarification is in order:

**This issue is not about the technical integration of scrapy with Slack** (which should be relatively straight-forward with [Slack Incoming Webhooks](https://api.slack.com/incoming-webhooks) and a small Scrapy pipeline/extension [like this one](https://github.com/rudeigerc/scrapy-slackbot/blob/master/scrapyslackbot/extensions.py) or the one @ttilberg posted above). :slightly_smiling_face: 

The question discussed here is about **finding a home for the Scrapy community**, which is currently [scattered](https://scrapy.org/community/) among a little-used IRC channel, a low-volume subreddit, and the "scrapy" Stack Overflow tag. While there's definitely the most users active at the latter, Stack Overflow simply isn't intended to be a "community home".

**Comment by barraponto** [comment]
I would recommend Gitter or Discord since Slack lacks history in free plans. As communities grows large, the messages volume might mean history is gone on a daily basis in Slack... For example large opensource project communities, see [Reactiflux](https://discordapp.com/invite/0ZcbPKXt5bZiQhB5) and [FreeCodeCamp](https://gitter.im/FreeCodeCamp/home)

**Comment by Gallaecio** [comment]
If we wish to use open source software for communications, we could consider Matrix, possibly with a bridge to the current IRC channel.

**Comment by wRAR** [comment]
There is currently [an official Discord server](https://discord.gg/mv3yErfpvq), though it's also low-volume (but higher than the IRC channel).
