### ISSUE TITLE
scrapy Request failing silently in some conditions

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#1407]
Looks like Scrapy is silently failing in case user attempts to make requests to url which meets two conditions:

1) request url is incorrect, e.g. no netloc
2) request url is outside allowed_domains

consider following simple spider

```python
from scrapy import Spider, Request


class SimpleSpider(Spider):
    name = "simple"
    start_urls = [
        "http://httpbin.org/get"
    ]
    allowed_domains = ["httpbin.org"]

    def parse(self, response):
        url_not_allowed = "http:/github.com"
        yield Request(url_not_allowed)
```

requested url is not in allowed_domains and is additionally incorrect. When you run this spider, you get following output (silent failure)

```
2015-08-03 16:20:20 [scrapy] INFO: Spider opened
2015-08-03 16:20:20 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-08-03 16:20:20 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2015-08-03 16:20:21 [scrapy] DEBUG: Crawled (200) <GET http://httpbin.org/get> (referer: None)
2015-08-03 16:20:21 [scrapy] INFO: Closing spider (finished)
```

no exception is printed despite the fact that url is incorrect and not allowed. 

Expected output: there should be either exception about incorrect url, or warning saying `Filtered offsite request to 'github.com'`.

**Comment by jdemaeyer** [comment]
Hm, some thoughts:
- The request is indeed filtered by the `OffSiteMiddleware`. If you print the stats you see `'offsite/filtered': 1` in there. The thing is that the middleware only emits one debug log *per domain*, and since `urlparse` cannot make out a hostname from the URL, `urlparse_cached(x).hostname` is `None` and the if clause that would emit the debug logging message is never entered (https://github.com/scrapy/scrapy/blob/master/scrapy/spidermiddlewares/offsite.py#L34)
- URLs without double slashes are perfectly valid (e.g. `mailto:blah@example.com`), and Scrapy consequently only checks for `:` in URLs (https://github.com/scrapy/scrapy/blob/master/scrapy/http/request/__init__.py#L56)
- However, HTTP URLs without double slashes are *not* valid: [RFC2616](http://www.faqs.org/rfcs/rfc2616.html) 3.2.2

I don't think the scheme check in `Request` should look for `://`. After all, someone might have implemented custom download handlers for non-http-like schemes. Maybe it'd be enough to add "offsite filtered" messages for the case that the `hostname` could not be extracted from the URL (one per request filtered)?
