### ISSUE TITLE
Html http-equiv Tag with status code 200

### ISSUE THREAD

**Issue by AlanChien** [scrapy/scrapy#1422]
Dear Scrapy developer,

I crawl following url : 

"http://www.baidu.com/link?url=trNkDflaMpWNZbbB5OphH_bi_8jMpse4zyjTFrexyYw-XAg9M9VmS6YfvsEdUaJEbHKMKfdoPu1LUVMynFNXv1DVVRE6vnmYvCZ1s4jkJae&wd=&eqid=ac8e85b700005ad90000000455c83eee"

and response with status code 200 and content as follow:

```
"<script>window.location.replace("http://testrepository.readthedocs.org/en/latest/MANUAL.html")</script>\n<noscript><META http-equiv="refresh" content="0;URL=\'http://testrepository.readthedocs.org/en/latest/MANUAL.html\'"></noscript>\n"

```

It's won't auto redirect to correct url, why? Maybe it's not scrapy bug, but is there any solution to solve this?

Very thanksful.

Best wishes.

**Comment by kmike** [comment]
Hi @AlanChien,

See https://github.com/scrapy/scrapy/issues/18. I think both options are valid; maybe it worths it to add more control to user whether to follow meta refresh inside `noscript` tags. 

By default it makes more sense not to follow such redirects because one can use [w3lib.html.get_meta_refresh](https://github.com/scrapy/w3lib/blob/7ec91ce52b67f3e62b78e5efd44d3589b8c7a894/w3lib/html.py#L287) to follow the redirect manually. Currently to avoid following it the whole middleware should be disabled, or at least you need to know the expected page contents in advance.

**Comment by Gallaecio** [comment]
@AlanChien @kmike https://github.com/scrapy/w3lib/pull/38 fixed this issue, right?
