### ISSUE TITLE
XML serialiser corrupts output when encountering None values

### ISSUE THREAD

**Issue by Malvineous** [scrapy/scrapy#1428]
If you set a field to the value `None` then use the XML serialiser, the output XML becomes corrupted (invalid XML, missing tags, etc.) and you get the following exception for each item during the scrapy run:

```
2015-08-12 11:01:43 [scrapy] ERROR: Error caught on signal handler: <bound method ?.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x7f70e7723ed0>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/scrapy/xlib/pydispatch/robustapply.py", line 57, in robustApply
    return receiver(*arguments, **named)
  File "/usr/lib/python2.7/site-packages/scrapy/extensions/feedexport.py", line 193, in item_scraped
    slot.exporter.export_item(item)
  File "/usr/lib/python2.7/site-packages/scrapy/exporters.py", line 130, in export_item
    self._export_xml_field(name, value)
  File "/usr/lib/python2.7/site-packages/scrapy/exporters.py", line 146, in _export_xml_field
    self._xg_characters(serialized_value)
  File "/usr/lib/python2.7/site-packages/scrapy/exporters.py", line 157, in _xg_characters
    serialized_value = serialized_value.decode(self.encoding)
AttributeError: 'NoneType' object has no attribute 'decode'
```

This was happening for me because I was using a CSS selector and `extract_first()`, but the element was optional, so for those items where the element was missing, the field was being set to `None`, causing this problem.

**Comment by RickyY1689** [comment]
Hi @Gallaecio, looking to pick this issue up. Does it still need a resolution?

This will be part of [a university course assignment](https://shuiblue.github.io/UofT-ECE444/) to seek out an open source repo and aim to contribute to it's codebase.

Looking forward to a confirmation. Thanks!

**Comment by Gallaecio** [comment]
I do not remember this issue at all, and I am extremely surprised that I seemingly tagged this 22 days ago.

I have just verified that the issue no longer exists. It turns out it was addressed by https://github.com/scrapy/scrapy/pull/1747.

**Comment by Gallaecio** [comment]
@RickyY1689 This issue aside, feel free to ask for help if you find anything else you would like to work on. Depending on your areas of interest and the scope of the assignment, there are many things you could potentially work on that do not necessarily have an issue in the bug tracker, like improving test coverage.

**Comment by RickyY1689** [comment]
@Gallaecio, ah unfortunate. Thanks for the prompt reply! It'd be great if you could recommend something to work on. I only have a day or two's worth of development time so the scope of the problem would have to be pretty small. Happy to help improve test coverage but our assignment also asks us to make some changes within the code base beyond test cases. Let me know if you have something in mind!

**Comment by Gallaecio** [comment]
Making it so that a public API that accepts a path as a string also accept as `pathlib.Path` object, as part of https://github.com/scrapy/scrapy/issues/5739, could be a good option. However, finding such an API might not be trivial.

Finding a non-documentation-only, non-test-only issue that can be handled with 8h-16h hours of development by someone not familiar with the code base can be tricky, Scrapy’s code base is not always the easiest to work with.

These are some potential options I see at https://github.com/scrapy/scrapy/contribute:
- https://github.com/scrapy/scrapy/issues/5537 (writing a test seems like the hardest part)
- https://github.com/scrapy/scrapy/issues/5491 (there is workaround code provided, it is a matter of adapting it)
- https://github.com/scrapy/scrapy/issues/4463 (some aspects of the fix are discussed in detail)
- https://github.com/scrapy/scrapy/issues/960 (1 known easy workaround, and 1 complex, interesting, unfinished implementation; requires manual testing with S3, though, although the free tier should be enough)
