### ISSUE TITLE
CrawlSpider - change the link extractor rules while spider is running?

### ISSUE THREAD

**Issue by stejesh** [scrapy/scrapy#1432]
I understand this is a support question, but i've got no proper solutions after a lot of searching on sites like stackoverflow.com

My query is for the `CrawlSpider`

I understand `rules` is a static variable, 

Can i change the `rules` in runtime say, like

```
@classmethod
def set_rules(cls,rules):
 cls.rules = rules
```
by 

`self.set_rules(rules)`

<br/>
Is this the acceptable practice for the `CrawlSpider` ?  if not please suggest the appropriate method

My use case, 

I'm using scrapy to crawl certain categories A,B,C....Z of a particular website. each category has 1000 links spread over 10 pages 
 
and when scrapy hits a link in a some category which is "too old". I'd like the crawler to stop following the remainder of the 10 pages ONLY for that category alone and thus my requirement of dynamic rule changes.

Please point me out on the right direction.

Thanks!

**Comment by eliasdorneles** [comment]
The `rules` are meant to be static, you should not change them at runtime. Because the order of the handling responses is not guaranteed (they're handled asynchronously), you can't trust that you'd be changing rules at an appropriate time.

You may want to try using a callback like this instead, that decides when to follow the parsing rules:

```
def maybe_follow_rules(self, response):
    if self.should_follow_rules(self, response):
        # call CrawlSpider's parse method that applies crawling rules
        for x in self.parse(response):
            yield x
```

Please note that the GitHub issues are meant to track bugs and features for Scrapy. For questions about how to use Scrapy like this, try the [scrapy-users mailing-list](https://groups.google.com/forum/#!forum/scrapy-users) or [Stackoverflow](stackoverflow.com/tags/scrapy).
