### ISSUE TITLE
Update ubuntu packages

### ISSUE THREAD

**Issue by gmeans** [scrapy/scrapy#1438]
Can we get the ubuntu packages updated w/ the 1.0.3 release?

The latest one I see is 1.0.1.post1+g5b8c9e5-1435726464.

**Comment by cyberplant** [comment]
Hello @gmeans, you can find the latest version of scrapy in the `unstable` distribution of the repository:
http://packages.scrapy.org/ubuntu/pool/unstable/s/scrapy/

We (Scrapinghub) are now doing more real testing for ensuring the stability of scrapy, so we take from `unstable` weekly, move to `testing`, test, and if everything works for some days, move to stable.

That's why now takes longer to have the latest versions in `main`.

**Comment by pablohoffman** [comment]
@cyberplant can you update the Scrapy ubuntu package documentation to reflect this?

**Comment by cyberplant** [comment]
Sure!
