### ISSUE TITLE
Headers object serializes to json differently depending on the indent value

### ISSUE THREAD

**Issue by dvdbng** [scrapy/scrapy#1459]
A scrapy.http.headers.Headers instance will serialize to a shallow object if indent=None and wrap the values in a list if indent is a number:

```
>>> from scrapy.http.headers import Headers
>>> h = Headers({ "X-Foo": "bar" })
>>> print json.dumps(h)
{"X-Foo": "bar"}
>>> print json.dumps(h, indent=3)
{
   "X-Foo": [
      "bar"
   ]
}
```

Tested in Scrapy 1.0.3

**Comment by redapple** [comment]
Indeed. Weird.

**Comment by elacuesta** [comment]
This is in fact weird, but (at least in python 2.7.10) it's not caused _only_ by passing the `indent` argument; for instance, a correct output can be obtained by passing `sort_keys=True`.

Consider the following piece of code:
```
import inspect
from json import dumps

class CustomDict(dict):
    def _inspect(self):
        current_frame = inspect.currentframe()
        outer_frames = inspect.getouterframes(current_frame)
        for frame in outer_frames:
            print(frame[1:-2])

    def __getitem__(self, key):
        self._inspect()
        return super(CustomDict, self).__getitem__(key)

    def items(self):
        self._inspect()
        return super(CustomDict, self).items()

    def iteritems(self):
        self._inspect()
        return ((k, v) for k, v in super(CustomDict, self).iteritems())
```

This allows us to get the call chain:

```
>>> d = CustomDict(key=['value'])
>>> print dumps(d)
('<stdin>', 4, '_inspect')
('<stdin>', 8, '__getitem__')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 270, 'iterencode')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 207, 'encode')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py', 243, 'dumps')
('<stdin>', 1, '<module>')
{"key": ["value"]}
>>> print dumps(d, indent=4)
('<stdin>', 4, '_inspect')
('<stdin>', 11, 'iteritems')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 363, '_iterencode_dict')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 434, '_iterencode')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 209, 'encode')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py', 250, 'dumps')
('<stdin>', 1, '<module>')
{
    "key": [
        "value"
    ]
}
```
If no arguments are passed to `json.dumps`, a cached `JSONEncoder` object is used (https://hg.python.org/cpython/file/v2.7.10/Lib/json/__init__.py#l243). This default encoder (https://hg.python.org/cpython/file/v2.7.10/Lib/json/__init__.py#l111) ends up calling the `c_make_encoder` function which is implemented in C, instead of `_make_iterencode` (https://hg.python.org/cpython/file/v2.7.10/Lib/json/encoder.py#l259). It seems to me that the C implementation calls `__getitem__` first and the python one calls `iteritems` (https://hg.python.org/cpython/file/v2.7.10/Lib/json/encoder.py#l363).

The difference can also be seen with: 
```
>>> print dumps(d, sort_keys=4)
('<stdin>', 4, '_inspect')
('<stdin>', 14, 'items')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 361, '_iterencode_dict')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 434, '_iterencode')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 209, 'encode')
('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py', 250, 'dumps')
('<stdin>', 1, '<module>')
{"key": ["value"]}
```
In this case, the `items` method is invoked (https://hg.python.org/cpython/file/v2.7.10/Lib/json/encoder.py#l361).

Given that the `Headers` class returns only the last item in `__getitem__` (https://github.com/scrapy/scrapy/blob/master/scrapy/http/headers.py#L41), only one element is serialized.

I'm not sure how can this be solved, returning the full list of valus in `__getitem__` would be backwards incompatible.

**Comment by Gallaecio** [comment]
As #5146 mentions, this is not reproducible in Python 3, where you actually need to use `to_unicode_dict()` to get something that you can represent in JSON (using `h` directly causes a `TypeError` due to `bytes` being used), and the issue is not reproducible with the resulting `dict`, which is a regular dict with strings as keys and values.
