### ISSUE TITLE
ImportError: No module named spiders

### ISSUE THREAD

**Issue by vazeer** [scrapy/scrapy#1490]
from scrapy.spiders import CrawlSpider, Rule
i have Scrapy 0.24.5
Python 2.7.6

**Comment by kmike** [comment]
Hey @vazeer,

Upgrade to Scrapy 1.0 to make your import work. In Scrapy 0.24 the import should be `from scrapy contrib.spiders import ...`. 

It is better to upgrade because Scrapy 0.24 is unlikely to get bug fixes, and Scrapy 1.0 should be backwards compatible. But if you have to use Scrapy 0.24 then correct docs are here: http://doc.scrapy.org/en/0.24/topics/spiders.html.

**Comment by chenjian158978** [comment]
Hey@kmike, I have  Scrapy version 1.0.4, well, the problem is still here: ImportError: No module named spiders....
Can you fix this? 
How about you? @vazeer

**Comment by kmike** [comment]
@chenjian158978 could you please paste the full traceback? Are you sure Scrapy is installed correctly?

**Comment by chenjian158978** [comment]
@kmike I deleted the project and then rebuild the scrapy, followed the Scrapy Tutorial V1.0...and now everything is OK.
The project was built a long time ago, maybe that's the problem.
thx for your reply.

**Comment by emazurek** [comment]
Hint: Don't delete `__init__.py` from any place in your project directory. Just because it's empty doesn't mean you don't need it.
