### ISSUE TITLE
Copying items not work correctly with list values

### ISSUE THREAD

**Issue by ils78** [scrapy/scrapy#1493]
> > item = Item()
> > item['some_field'] = []
> > 
> > c_item = Item(item)
> > c_item['some_field'].append(1)
> > 
> > print item['some_field'], c_item['some_field']
> > [1] [1]

**Comment by Digenis** [comment]
Not a bug.
See https://docs.python.org/2/library/copy.html

What you do It is not meant to deepcopy.
This is the constructor to which you pass an `Item` instance
and since it receives a mapping, it makes a shallow copy.
It's the same thing you'd expect from `dict2 = dict(dict1)`
See the documentation link.

**Comment by kmike** [comment]
Yeah, I agree with @Digenis: we document Items as providing dictionary-like API.
But the example at http://doc.scrapy.org/en/latest/topics/items.html#other-common-tasks can be improved. So I think it is a documentation issue.

**Comment by nramirezuy** [comment]
I wonder if we want to provide a deepcopy shortcut.

**Comment by kmike** [comment]
I like an idea of a deepcopy shortcut.
