### ISSUE TITLE
Overriding `CLOSESPIDER_PAGECOUNT` settings within Spider does not get honored

### ISSUE THREAD

**Issue by deanq** [scrapy/scrapy#1561]
Is this one of those settings that cannot be overridden per Spider instance? Is it finalized before instantiation?

```
class SiteSpider(CrawlSpider):

    def __init__(self, **kw):
        settings.set('CLOSESPIDER_PAGECOUNT', kw.get('maxpages', 100), priority='cmdline')
        super(SiteSpider, self).__init__(**kw)
...
```

What am I missing or is this even possible?

**Comment by jdemaeyer** [comment]
Hey @deanq, you cannot update the settings from within `Spider.__init__()`. They are marked 'immutable' long before it is called.

For per-spider settings, you can use [the Spider's `custom_settings` attribute](http://doc.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.Spider.custom_settings).

However, given that you want to read from the keyword arguments given on Spider instantiation, that won't really help you either. You could try two things:

  1. Write your own modified CloseSpider extension by subclassing [`scrapy.extensions.closespider`](https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/closespider.py), then overwrite the [`page_count()` method](https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/closespider.py#L47) so that it checks against `spider.maxpages` (or similar) instead of against `self.close_on['pagecount']`.
  2. "Hack" your keyword argument `maxpages` into the existing CloseSpider extension by circumventing the settings, e.g.:

  ```python
  # in your spider
  def __init__(self, **kw):
      # You might have to change the 0 to another index depending on your enabled extensions,
      # check by printing self.crawler.extensions.middlewares somewhere
      self.crawler.extensions.middlewares[0].close_on['pagecount'] = kw.get('maxpages', 100)
  ```

**Comment by deanq** [comment]
Thanks for the response @jdemaeyer . I was going for those options you listed before, but I found a shorter way. I ended up keeping a self.pages_crawled property that gets incremented for each `parse` and call `CloseSpider('max pages reached')` when it reaches the maximum. It's not precise, but so was `CLOSESPIDER_PAGECOUNT`. At least it shuts off close to the number provided.

**Comment by pawelmhm** [comment]
would it be possible to add support for command line arguments in default Scrapy CloseSpider extension? I recently faced similar problem as @deanq I ended up subclassing Scrapy default CloseSpider extension and adding support for command line. Maybe functionality like this would be useful for other users? Are there any concerns that would block improvement like this?

**Comment by jdemaeyer** [comment]
hi @pawelmhm. It is already possible to configure the the CloseSpider extension through the command line tool, because all settings can be overridden from there. Like this:
`scrapy crawl -s CLOSESPIDER_PAGECOUNT=100 myspider`

**Comment by deanq** [comment]
I'm using scrapyd to run my crawlers, and I need to be able to pickup parameters passed through the POST. Command line doesn't apply in my case.

**Comment by kmike** [comment]
@deanq /schedule allows to override settings (http://scrapyd.readthedocs.org/en/latest/api.html#schedule-json), isn't it enough? You can set a default value (100) in Spider.custom_settings and pass overridden value when necessary using `setting=CLOSESPIDER_PAGECOUNT=100`.
