### ISSUE TITLE
Disable telnet by default?

### ISSUE THREAD

**Issue by curita** [scrapy/scrapy#1572]
This topic was discussed in #1524, where some reasons were presented to keep telnet enable by default (as it is now) or to disable it.

**Comment by nyov** [comment]
> I think another possibility could be to have telnet disabled in the default settings, but have it enabled in the `settings.py` template when you create a project. That way new projects created by `scrapy startproject` would have it enabled, and in all other cases it'd be disabled by default.

That would work for me aswell, making it a project-env default setting, instead of a global one. Was just asking for a smaller footprint on _embedded_ projects (using scrapy as a library). :+1:

**Comment by nramirezuy** [comment]
I don't use templates and I want telnet enabled by default. 
So keeping the settings as it is for the last years and just adding it to the settings to templates seems more logical to me. It will increase awareness for new comers, who I think actually use templates.

**Comment by kmike** [comment]
@nramirezuy disabling telnet in generated settings template solves nothing because these settings are used in a project, and in a project you likely want telnet enabled. You're more likely to want telnet disabled in a custom script which uses CrawlerProcess, but this script likely doesn't use settings.py. 

There is already commented out code to disable telnet in project settings template (a bit convoluted though, it doesn't use TELNET_ENABLED option).

**Comment by nramirezuy** [comment]
@kmike I would say to use `CrawlerProcess` you have `Scrapy` understatement, basically you provably already made some spider and you are trying something more advanced. Given this point I would say there is nothing to solve.

We should simply give more awareness for this settings on the documentation, and not change defaults because they are a better fit for an advanced user.

**Comment by kmike** [comment]
@nramirezuy I think it is more a question of providing a first-class library interface, not about being beginner or advanced user. @nyov is well aware of telnet extension, but he doesn't want to start a new telnet server for each spider executed by CrawlerProcess, it doesn't make much sense for a library to do so.

**Comment by curita** [comment]
Another possibility could be to have it disabled by default, but enabled in all scrapy commands (setting it here should be enough: [`scrapy/commands/__init__.py#L18`](https://github.com/scrapy/scrapy/blob/master/scrapy/commands/__init__.py#L18)). I think this approach serves better to the library/framework distinction.

**Comment by nramirezuy** [comment]
@curita I like that solution a lot more. It just has to be be clear on the documentation.

**Comment by Digenis** [comment]
> Another possibility could be to have it disabled by default, but enabled in all scrapy commands

+1

**Comment by nyov** [comment]
> Another possibility could be to have it disabled by default, but enabled in all scrapy commands

I would think this is the best solution. It fits the perspective of having the commands as the GUI/CLI around scrapy as a library :)
It would feel better if network services such as telnet were enabled by this commandline or wrapping process, instead of from "inside the library".

**Comment by mohmad-null** [comment]
From a security perspective TELNET should be disabled by default. You *cannnot* rely on users knowing it is there and manually disabling it.

If a user wants an insecure configuration (i.e. because they're using it on their local machine) they should have to manually enable it. I believe that's generally considered best-practice from a security perspective. "Insecure by default" as is the case currently is usually frowned upon.

**Comment by kmike** [comment]
@mohmad-null telnet uses auth by default now, with auto-generated password logged at startup - do you see a problem with that?

**Comment by nyov** [comment]
So, should we close this as resolved (or wontfix, depending on your view), as I don't see the current behaviour now changing anytime soon?

**Comment by Gallaecio** [comment]
The feedback so far (including yours) seems to favor enabling it by default only from the command line, so I think it is OK to leave it open for someone to implement that approach.

And there is always the hope that we will eventually change people’s minds and get it disabled by default globally :slightly_smiling_face:

**Comment by Gallaecio** [comment]
Given [the random password mentioned earlier](https://github.com/scrapy/scrapy/issues/1572#issuecomment-540998789), I don’t think this is a security issue.

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/issues/1572#issuecomment-597108730
