### ISSUE TITLE
rules in CrawlSpider don't work

### ISSUE THREAD

**Issue by Leonard-Peng** [scrapy/scrapy#1585]
I recently tried to use scrapy to crawl my blog. Everything worked well until I came to rules. It didn't work and I did not know what was wrong. I followed the doc in [scrapy crawlspider rules doc](http://doc.scrapy.org/en/latest/topics/spiders.html#crawlspider)

Here is the code:
```python

# -*- coding: utf8 -*-
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor


class BlogSpider(CrawlSpider):
    name = 'leonard-peng.blog'
    allowed_domains = ['leonard-peng.github.io']
    start_urls = ['http://leonard-peng.github.io/']
    rules = (
        # try to match '/2015/09/04/regex/'
        Rule(LinkExtractor(allow=('/2015/09/04/regex/', )), callback="parse_item"),
        Rule(LinkExtractor(allow=('2015/09/04/regex/', )), callback="parse_item"),
        Rule(LinkExtractor(allow=(r'/\d{4}/\d{2}/\d{2}/.*', )), callback="parse_item"),
    )

    def parse(self, response):
        print 'get root url data'

    def parse_item(self, response):
        print 'get article url data'


```

**Comment by eliasdorneles** [comment]
When you inherit from `CrawlSpider` instead of a standard `scrapy.Spider` you should NOT override the `parse` function (it implements the rule handling), see the warning note in under the Crawling Rules: http://doc.scrapy.org/en/latest/topics/spiders.html#crawling-rules

Also, please avoid asking questions about how to use Scrapy in the issues, it's better to use the [Stackoverflow scrapy tag](http://stackoverflow.com/tags/scrapy) or the [scrapy-users mailing-list](https://groups.google.com/forum/#!forum/scrapy-users)

**Comment by Leonard-Peng** [comment]
Thanks a lot, it do help me.  ^_^

I'll flow your welcome tip.

**Comment by eliasdorneles** [comment]
Thanks, glad it helped! :+1: 
I'll close this, then.
