### ISSUE TITLE
scrapy LOG_LEVEL setting in Spider.custom_settings does not work

### ISSUE THREAD

**Issue by YAmikep** [scrapy/scrapy#1612]
I set the `LOG_LEVEL` setting to `INFO` in the Spider class via the `custom_settings` attribute but I still see the `DEBUG` messages in the console.

When I set it on the `settings.py` file or via the command line option `--loglevel`, it works.

I thought any settings could be set via the `custom_settings` attribute. Is that a bug? (Scrapy 1.0.3 and python 2.7.10)

```
class TestSpider(scrapy.Spider):
    name = "Test"
    ...
    custom_settings = {
        'LOG_LEVEL': 'INFO',
    }
```

**Comment by jdemaeyer** [comment]
Looks like a bug, although support for setting `LOG_LEVEL` on the spider *might* be dropped in the future (#1580)

@curita Probably because we're using `settings` instead of `self.settings` [in this line](https://github.com/scrapy/scrapy/blob/master/scrapy/crawler.py#L37)?

**Comment by nramirezuy** [comment]
I think changing `LOG_LEVEL` from the spider doesn't make too much sense anyways.

**Comment by YAmikep** [comment]
@nramirezuy Could you elaborate on your answer? I'm new to scrapy. Why it does not make sense to set the logging level on a Spider? 
Where do you set it? On a project? What if I have different Spider?

Thanks

**Comment by nramirezuy** [comment]
@YAmikep It doesn't make sense because there are 2 clear stages, development and production. During development you will probably want to use `DEBUG`, but for production you will want `INFO` or `WARNING`. This 2 should be 2 completely different environments, making the setting to have no sense.

What if you need to enable `DEBUG` on production for some reason; well then you can use command line to set the `LOG_LEVEL`.

**Comment by YAmikep** [comment]
Thanks @nramirezuy . I see what you meant now.
I agree and actually, only the command line option makes sense. Changing it at the project setting does not make sense either.

**Comment by nramirezuy** [comment]
@YAmikep I guess you are right. But you can cheat it using [`local_settings.py`](https://groups.google.com/forum/#!topic/scrapy-users/pO6BGH5vlII).

**Comment by jackie2013** [comment]
@nramirezuy I set LOG_FILE setting in custom_settings for every Spider to get a different log, but it not work, what should i do? Thanks.

**Comment by djunzu** [comment]
@nramirezuy , I agree with you: development (`DEBUG`) is different from production (`INFO`). But I am facing a particular case...

I run multiple spiders using `CrawlerProcess`, each spider for one website. One of them is very good example of poorly coded html we find in the wild! It is a really f* mess. Plus, it is always changing. So, almost every time a run my crawler (once every 45 days) I find out this particular spider is not running correctly because of the recent changes. Then I need to run it alone in development to be able to fix it.

If I could set just this spider to debug mode, my production would be in info mode and I would know how to fix this particular spider without doing a complete run in debug mode.

My other option is to always run this spider alone. But my workflow would be much more consistent if this bug was fixed.

**Comment by kmike** [comment]
+1 to fix it; it looks like a bug for me.

**Comment by shyandsy** [comment]
so  how to solve this now?

I am running on python 3.5, and all the log information, such as info and debug goes into the log file.
but i only wanna the ERROR!

**Comment by djunzu** [comment]
@shyandsy , your question is not related to this issue even though it is about logging.

If you wanna error level in everywhere, just use the right setting: [LOG_LEVEL](https://doc.scrapy.org/en/1.1/topics/settings.html#std:setting-LOG_LEVEL)

**Comment by shyandsy** [comment]
@djunzu 
hi i have the log level setting in settings.py
![image](https://cloud.githubusercontent.com/assets/5271457/19317020/3aefc6a0-9069-11e6-8a84-8e51ec60234d.png)

but the info, debug also wrote in log file

**Comment by ianhhhhhhhhe** [comment]
About settings, i think maybe you setup but you don't know how to import or activate them. And that's why your logging doesn't work.

So there are some solutions might help.

You need to sure that settings url is corret in ```root/scrapy.cfg```. Then you can set your logging in ```settings.py```. I suggest at least setup LOG_FILE and LOG_LEVEL.

Then you can run ```scrapy crawl crawler_name````

If you want to run the spider from a script, you will need ```from scrapy.utils.project import get_project_settings``` and ```from scrapy.utils.log import configure_logging ```. Then put ```configure_logging(get_project_settings)``` to where you need to activating logging.
