### ISSUE TITLE
Might be a typo

### ISSUE THREAD

**Issue by kburman** [scrapy/scrapy#1620]
https://github.com/scrapy/scrapy/blob/master/scrapy/http/response/text.py#L44

it should be
`self._body = body.encode(self.encoding)`
not 
`self._body = body.encode(self._encoding)`

**Comment by kmike** [comment]
Yeah, this is confusing. I think it is `_encoding` because `.encoding` is a computed property which tries to detect encoding based on headers and body; body is not avaiilable yet (we're setting it), `.encoding` returns `_encoding` anyways if it is set, and we're checking that it is set just above this line.
