### ISSUE TITLE
"Server not found" doc.scrapy.org

### ISSUE THREAD

**Issue by jschilling1** [scrapy/scrapy#1667]
I've had this issue consistently for months using Firefox.
Several refreshes of the page finally allow it to load.

I realize this could be a dns issue with my isp that is completely unrelated to scrapy but the fact that i've never had the same problem with any other site merits a bug report in case anyone else notices this.

**Comment by kmike** [comment]
I'm not sure what can we do with it; I have never seen this issue (also on Firefox), and doc.scrapy.org is hosted by http://readthedocs.org/, so it is hard to debug. If it is a DNS issue with your provider you may try using e.g. Google DNS (8.8.8.8, 8.8.4.4) instead of your provider's DNS default servers.
