### ISSUE TITLE
I have tried to execute the program but i got an unhanded Exception Can any one please help me

### ISSUE THREAD

**Issue by PILLUTLAAVINASH** [scrapy/scrapy#1670]
![error](https://cloud.githubusercontent.com/assets/15902230/12255512/8882c8a8-b91a-11e5-8b9e-d5a948ba6506.PNG)

**Comment by redapple** [comment]
@PILLUTLAAVINASH , please read this page on [how to file proper bugs on scrapy](http://doc.scrapy.org/en/latest/contributing.html#reporting-bugs)

Can I ask you to submit this to [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users) instead?
You will certainly need to submit some spider code and paste your console logs as text instead of image so the community can help you
