### ISSUE TITLE
No way to .extract selector retaining html entities/quoting? 

### ISSUE THREAD

**Issue by jschilling1** [scrapy/scrapy#1700]
I'm extracting js data using .re_first() and later converting it to python native data. The problem is extract/re method don't seem to provide a way to not unquote html, i.e.

original html:
{my_fields:['O\\&\\#\39\;Connor Park'], } (ignore the slashes..)

re_first() output
{my_fields:['O'Connor Park'], }
turning this output into json won't work.

Is there an easy way around it?

EDIT:
re.search(r'exp', extract_first()) actually works, keeping the raw quoted html
extract_first() outputs {my_fields:['O\\&\\#\39\;Connor Park'], 

is it intentional that extract_first() and re_first() deal with quoting differently?

**Comment by Digenis** [comment]
This is a [parsel](https://github.com/scrapy/parsel) discussion.
Parsel extract-like methods have indeed confusing returned encodings
but not in the way you think they are;
`&quot;` doesn't need to be escaped unless it's an element attribute.

Your problem seems to be that you don't understand how json encoding works.
See [python's json module](https://docs.python.org/2/library/json.html) and seek more help by asking in the [scrapy-users mailing list](https://groups.google.com/forum/#!forum/scrapy-users) or http://stackoverflow.com/

**Comment by redapple** [comment]
@jschilling1 ,
I answered your question at http://stackoverflow.com/questions/34887730

**Comment by jschilling1** [comment]
thanks redapple!  can we update documentation describing this difference between extract() and re()?

**Comment by redapple** [comment]
@jschilling1 , issue created https://github.com/scrapy/scrapy/issues/1704
