### ISSUE TITLE
Redirects do not obey deny or allow patterns

### ISSUE THREAD

**Issue by trifle** [scrapy/scrapy#1744]
Currently, redirects go wherever they want, ignoring the deny_res and deny_domain patterns set on a LinkExtractor. This means that no matter how one configures the LinkExtractor, denied URLs may end up being downloaded, parsed and stored.

The best way to stop this from happening would be to write a new downloader middleware. It should subclass BaseRedirectMiddleware, load the allow/deny patterns the same way OffsiteMiddleware does and raise IgnoreRequest when redirect_urls match these patterns.

There is already one related, but less generic issue #1042 .
I think I remember some discussion about a desirable refactor of the URL pattern matching logic (which is all over the place), but I can't find it currently.

I'd love to provide a pull request but it's unlikely I find the time to do so and I also don't have any experience writing tests (sorry).

**Comment by kmike** [comment]
Hey @trifle,

There is no way for LinkExtractor to use a final redirected URL as an input to allow/deny patters: LinkExtractor only extracts lnks from a page, it doesn't handle downloads; that's by design. 

When is it a problem? CrawlSpider?

**Comment by trifle** [comment]
Yes, I'm using CrawlSpider and deny patterns. Redirects within the site get picked up even though they should be denied. Since this is within the same domain, the OffsiteMiddleware doesn't really help.

It's clear that the LinkExtractor cannot know the final target URL. One way to deal with that would be to ignore responses at the beginning of parse(). However, I think it would be much cleaner and potentially more performant to ignore deny-matching requests during the redirect.

**Comment by nramirezuy** [comment]
@trifle I think you should be able to handle your issue with three toys:
[notice `process_request`](http://doc.scrapy.org/en/latest/topics/spiders.html#crawling-rules)
[notice `dont_redirect`](http://doc.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.redirect)
[notice `HTTPERROR_ALLOWED_CODES`](http://doc.scrapy.org/en/latest/topics/spider-middleware.html#httperrormiddleware-settings)

**Comment by trifle** [comment]
Thanks for your help, @nramirezuy & @kmike.

I'm not sure I get your hint, though: Using `process_request`, I can block the spider from following redirects. But at that point, I still don't know whether the n-th redirect URL will match my deny pattern. 

As far as I understand scrapy's architecture (please correct me here!), the earliest place I can block redirect requests is in the redirect chain.

Maybe I can illustrate this with an example. Say I have a site mysite.com of which I don't want to crawl mysite.com/bogus. Now, if the site has one or more redirects in place, I could run into this request chain:

mysite.com/?redirect=1 -->
mysite.com/?redirect=2 -->
mysite.com/bogus

I assume that these requests pass through the middlewares, but do not reach the spider code until the final response. If that is true, then I only have the option to use a middleware OR block after receiving the final response, right?

**Comment by nramirezuy** [comment]
@trifle I think you are looking for a custom `DownloaderMiddleware` positioned closer than `RedirectMiddleware`  to the `Downloader`(a higher number), this way you do it on the `Response`. Or you can use position yourself closer to the `Engine` as possible to catch the `Request` generated by `RedirectMiddleware` as soon as it leaves the scheduler. There is also the possibility of extending similar to https://github.com/scrapy/scrapy/pull/1002, but you need to disable the `BASE` one, this can be done setting the [`BASE`](https://github.com/scrapy/scrapy/blob/master/scrapy/settings/default_settings.py#L100) path with `None` instead of a number on your settings.
This way you can use `Settings` to pass the pattern or `Request.meta`, then raise `IgnoreRequest`(scrapy.exceptions module) to cut the chain.

Currently there is no way to block a request by pattern on the `DownloaderMiddlewares`, maybe you can make a request for a simple `Middleware` that blocks requests based on a regex and just call it `RequestBlockingThingy` :smile: .

**Comment by trifle** [comment]
Thanks @nramirezuy, that sounds very appealing.
I didn't know this came up so often! Obviously there is no need to keep this issue open when there are several related others, so feel free to close. I guess I'll have a stab at creating a DownloaderMiddleware, hopefully with a PR.

Thanks again for scrapy and your hard work in maintaining and expanding it!
