### ISSUE TITLE
Ignore meta-refresh tag embedded inside noscript tag

### ISSUE THREAD

**Issue by dangra** [scrapy/scrapy#18]
Some sites uses a meta-refresh redirect to detect browsers without javascript support, ie: http://www.surlatable.com/product/id/195440.do

```
<NOSCRIPT>
 <META HTTP-EQUIV="refresh" CONTENT="1; URL=/jsmessage.html">
</NOSCRIPT>
```

see http://dev.scrapy.org/ticket/185 for more info

**Comment by oliverrahner** [comment]
Is that really the correct behavior?
I want to parse a site that only displays a warning page when no Javascript has been detected and then redirects from there using <noscript><meta>. For this use case I had to remove the noscript-check.
I'd say Scrapy should follow everything in <noscript> by default, just because I does not implement JS. Maybe this behavior could be configurable via a middleware configuration setting?

**Comment by nramirezuy** [comment]
@oliverrahner open a PR with your proposal it should use the current approach as default.
