### ISSUE TITLE
Disk queues don't preserve Request class

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1890]
When a Request subclass (e.g. FormRequest) is sent to a disk queue a bare Request is what you get back. 

This is inconvenient for scrapy-splash: Splash requests all have Splash URL as request.url, but for logging it is nice to display the requested URL, not only Splash URL. In scrapy-splash this is implemented by changing `__repr__` in a Request subclass, but it works only when request is kept in memory.

**Comment by elacuesta** [comment]
Hello @kmike! I think the problem is in [this line](https://github.com/scrapy/scrapy/blob/master/scrapy/utils/reqser.py#L50), the `request_from_dict` function always returns a `Request` object regardless of the type of the request passed to `request_to_dict`. Please check the above PR which tries to solve the issue. Thanks!
