### ISSUE TITLE
Allow to dump `response.body` automatically when callback failed

### ISSUE THREAD

**Issue by Makman2** [scrapy/scrapy#1928]
Hello :)

I've recently working with scrapy, and I got the idea to automatically dump the body of a gotten response to a file when an exception was raised inside a callback. A log would be printed saying where to find the file and the user can inspect what maybe has gone wrong :)

As I implemented an own little "crash dump system" (which works completely manually, meaning you need to catch and dump everything yourself), I thought of an integrated version.

Let me know what you think about this idea :)
Thanks in advance :+1:

**Comment by kmike** [comment]
Hey @Makman2,

I think you can do that using a custom spider middleware - check http://doc.scrapy.org/en/latest/topics/spider-middleware.html#scrapy.spidermiddlewares.SpiderMiddleware.process_spider_exception. 

Printing response body to log in case of errors may be overwhelming - even a single 20KB response body in a log can be unreadable, and if your spider raises an exception in every callback it will get out of control soon.

Log messages should already include file paths and line numbers as a part of a traceback; it is a bug if the information is not detailed enough. Tracebacks can be scary, but often they are better than anything else because they contain all the information. I've seen more than once when library developers try to be helpful, catch the exception and try to provide a more user-friendly message, but in the end it makes debugging harder because important information from the original traceback is lost.

That said, I think it is possible to create an useful "crash dump" system; it requires some design decisions and maybe a prototype; the experiment worths trying. You don't have to modify Scrapy itself to create this extension; I think creating a separate Python package is the way to go.

**Comment by Makman2** [comment]
Yeah I also thought of using a middleware for this (though I'm not extremely experienced with scrapy to know where to place it exactly :P).
I had in mind to store the response body to a file and printing a single-line log message that tells the user/dev where it lies. Then we dont clutter the terminal with unreadable data :)

**Comment by Makman2** [comment]
Thats also how my crashdump prototype handles this^^

**Comment by kmike** [comment]
I'm closing this issue; this feature can be implemented outside Scrapy. If it turns out to be useful / popular we can consider it for Scrapy.
