### ISSUE TITLE
MediaPipeline (and ImagesPipeline/FilesPipeline) does not handle HTTP redirections

### ISSUE THREAD

**Issue by xoviat** [scrapy/scrapy#2004]
Basically, what's happened is that my spider is unable to download the files because the file_urls provided are actually redirected to the final download link. However, because of the following code, the redirect download middleware is effectively disabled, which makes the download fail.

```
def _check_media_to_download(self, result, request, info):
        if result is not None:
            return result
        if self.download_func:
            # this ugly code was left only to support tests. TODO: remove
            dfd = mustbe_deferred(self.download_func, request, info.spider)
            dfd.addCallbacks(
                callback=self.media_downloaded, callbackArgs=(request, info),
                errback=self.media_failed, errbackArgs=(request, info))
        else:
            request.meta['handle_httpstatus_all'] = True
            dfd = self.crawler.engine.download(request, info.spider)
            dfd.addCallbacks(
                callback=self.media_downloaded, callbackArgs=(request, info),
                errback=self.media_failed, errbackArgs=(request, info))
        return dfd
```

And here is the check in the redirect middleware that disables it:

```
if (request.meta.get('dont_redirect', False) or
                response.status in getattr(spider, 'handle_httpstatus_list', []) or
                response.status in request.meta.get('handle_httpstatus_list', []) or
                request.meta.get('handle_httpstatus_all', False)):
            return response

```

My question is: What is the point of enabling the handling of httpstatus_all, when it effectively disables all of the checks?

**Comment by xoviat** [comment]
Also, here is the error that is caused:

`[scrapy] WARNING: File (code: 302): Error downloading file from <GET <url> referred in <None>
`

**Comment by redapple** [comment]
That [line is quite old](https://github.com/scrapy/scrapy/commit/03751749a80526f3d97f60f0f63892501ef5de19#diff-f37ac01f1c3a8cc5f87456da118d7d1cR77).
I don't know the exact reason.
It may be to catch all non-200 response. But then 301 and 302 are interesting to have handled by redirect mw indeed. So `handle_httpstatus_all` may very well be too-broad scope.

**Comment by jbothma** [comment]
ditto. I overrode the function setting it to True but I'm nervous it'll bite me.
What does a request do when there's an error? will it raise an exception or something so  I don't end up treating an error or empty body as my file?

**Comment by jbothma** [comment]
I think a 301 should modify the corresponding element in file_urls to the new location, although that might be surprising to the user. Adding a redirect trail to the item might be excessive?

A 302 should probably just follow through to the final destination?

This should all respect the allowed domains, right? Is that automatically taken care of by the downloader?

So correct behaviour might look like:
1. remove the override of `handle_httpstatus_all`
2. verify that any http errors result in helpful error logs and storing anything or setting the files field
3. logging a helpful error
4. updating the relevant original url to the last location of the first chain of 301s, e.g. `scraped url > 301 a > 301 b > 302 c > 301 d > 200 e` should see b placed in file_urls

I think 2 and 3 are taken care of by the current code.

I think 4 is technically correct but it isn't easy since redirect status codes aren't in `redirect_urls`. Do you think it's necessary or just over-complicating?

**Comment by Granitas** [comment]
@jbothma To answer your question:  

> This should all respect the allowed domains, right? Is that automatically taken care of by the downloader?

Yes since all requests scheduled go through download middlewares it will go through [OffsiteMiddleware](http://doc.scrapy.org/en/latest/topics/spider-middleware.html#scrapy.spidermiddlewares.offsite.OffsiteMiddleware), so it will do the usual match to spider.allowed_domains.

Regarding the issue I think `handle_httpstatus_all` should be replaced with a `handle_httpstatus_list` that exclused some 300 codes. 
For `FilesPipeline` the callback `media_downloaded()` by default raises an exception on anything that is not 200 or has an empty body, so this pipeline doesn't benefit from this setting at all other than wrapping the error. Excluding that from 300 codes wouldn't break anything other than enabling the redirection, which might be unwanted for some reason but I bet it's the other way around more often than not.

I think implementing a pipeline setting to manage this would be an ideal solution.

**Comment by jbothma** [comment]
Thanks for the response.

A pipeline setting to opt in to allow 300 redirect codes?

**Comment by Granitas** [comment]
I submitted a PR with this :point_up:  
But the question remains, should ignoring redirects remain default behaviour like it is right now or should it be changed?

**Comment by jbothma** [comment]
Ah cool - I wanted to submit such a PR but wanted to clarify that the
pipeline setting you referred to was about allowing redirect codes and thus
following them.

I think the default behaviour should probably remain as it is and there
should be a setting to opt in to following redirects, and your proposed
solution sounds cool to me.

An additional question is what the value of referer should be and whether
the user might want the full redirect chain (considering it could be
arbitrary length) but those could come later. Most people probably don't
care that much, they just want the end file (or an error if the end result
isn't a 200)

**Comment by Granitas** [comment]
For handling redirect chains I think it should be left to the `RedirectMiddleware`, it is using `REDIRECT_MAX_TIMES` setting to set maximum chain size and handles everything else by itself.     

What do you mean regarding referer @jbothma though? I think scrapy by default populates referer with last request.url, right? So the issue might be if there are multiple urls the original file url might be lost? since multiple redirect chain gets handled one redirect at the time all of the redirects with their respective referers will end up in the log, so I don't think original referer might be lost here.

Redirect middleware logs every redirect as:

    logger.debug("Redirecting (%(reason)s) to %(redirected)s from %(request)s",
                 {'reason': reason, 'redirected': redirected, 'request': request},
                 extra={'spider': spider})

So for debugging purposes everything can easily be traced back if that what your question was.

**Comment by jbothma** [comment]
Oh cool! I was thinking it'd be useful if the urls in the chain were
attached to the response object, but this isn't a critical need for me, and
it's probably jsut a sidetrack.

It's probably most useful and expected that the referrer would be the
original url referrer but since that isn't set before there's a redirect
anyway, I track the referrer manually in my `item`.

So it sounds like your PR would address the core issue of being able to
download media behind a redirect

Thanks!

**Comment by SeanPollock** [comment]
Hi I ran in to this issue today too. 

Any updates on this bug, or reason the pull request wasn't merged?
