### ISSUE TITLE
Increase number of full spider examples in documents

### ISSUE THREAD

**Issue by mobcdi** [scrapy/scrapy#2024]
I believe for new users it would be useful if you provided more full examples of spiders in the documentation e.g. working crawler. The documentation is detailed but with the various files that need to be edited or created to create a working spider it can be difficult for new users to get up to speed. 

These reference spiders could also be used to guide users in solving their problem e.g use the basic crawler as per document .... and add a rule to ....

**Comment by djunzu** [comment]
> with the various files that need to be edited or created to create a working spider it can be difficult for new users to get up to speed.

Websites are very different from each other. It is very difficult (impossible!?) to have an example spider/crawler that could be modified/extended in order to be used with another website. And I think Scrapy is a framework for developers/programmers. If someone does not know how to create/edit some files, there are several [companies](http://scrapy.org/companies/) selling this service.

But...

> I believe for new users it would be useful if you provided more full examples of spiders in the documentation e.g. working crawler. 

The major problem with a working crawler is that it crawls some website. And no website want incoming traffic that add nothing to them! If you have for example an e-commerce, you do not want a lot of incoming traffic that will never be a selling.

I think is not very polite and civilized that Scrapy provides working crawlers to random websites. (Unless the website agrees with that.)

A workaround could be to provide a small web application to be downloaded and base the docs examples in this "real" website. This approach would allow:
- more consistency in docs having examples based in a "real" website.
- users can run the toy website locally and try the examples
- users can have a working crawler example and run it without bother anyone with unwanted incoming traffic.

**Comment by mobcdi** [comment]
I hadn't considered the spiders would actually point to working domains to crawl but I do like the idea of a example website to base everything around. It might even help with dealing with user questions by being able to rule out a spider that can't crawl the demo site. 

I originally meant that there would be more stepping stones up from the tutorial spider to more feature rich spiders by giving examples like a crawler spider with a file pipeline with just the minimum files needed so someone can see what files and settings they need to implement

**Comment by eliasdorneles** [comment]
Given that:

1) we now have [an updated examples section](https://doc.scrapy.org/en/latest/intro/examples.html) pointing to [quotesbot project](https://github.com/scrapy/quotesbot) which contains some sample spiders.

2) there is a [quotes-crawler project under Scrapinghub's sample projects](https://github.com/scrapinghub/sample-projects/tree/master/quotes_crawler) which demonstrations different techniques for different versions of the quotes website

What else is there to be done about examples?

**Comment by mobcdi** [comment]
That example site is a great addition, would it be possible to add 1 spider that writes files to disk or a spider that only extract quotes based on conditions e.g. quotes containing the string "life" ?

**Comment by djunzu** [comment]
@eliasdorneles 

I found no references to [sample projects](https://github.com/scrapinghub/sample-projects/tree/master/quotes_crawler) in docs. Is there any? It should!

**Comment by eliasdorneles** [comment]
Right, @stummjr and I weren't sure to add it because those sample projects are more about Scrapinghub stack, but I suppose it makes sense to link them there too.

**Comment by djunzu** [comment]
Those sample are more about Scrapinghub stack... in which way?
For me they are good examples on how to use Scrapy in different ways!

@eliasdorneles , maybe #2350 would answer your previous question.

**Comment by stummjr** [comment]
@eliasdorneles @djunzu [the repository as a whole](https://github.com/scrapinghub/sample-projects) has some examples that are specific to Scrapinghub platform. The [quotes-crawler](https://github.com/scrapinghub/sample-projects/tree/master/quotes_crawler), though, is not and I agree that it has good examples that could be useful for users in general.

So, we could add a pointer to that specific folder in the documentation.

**Comment by djunzu** [comment]
I haven't noticed [quotes-crawler](https://github.com/scrapinghub/sample-projects/tree/master/quotes_crawler) is not [the repository as a whole](https://github.com/scrapinghub/sample-projects). My fault.

I agree, with adding a pointer in docs to that specific folder. Or maybe move/copy that folder to a "Scrapy examples project".

**Comment by Gallaecio** [comment]
I feel this issues is a bit too broad and vague to be able to measure when it has been solved. @mobcdi Do you think you can rethink the issue report focusing on a single, specific problem that can be clearly solved?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
