### ISSUE TITLE
DEFAULT_REQUEST_HEADERS can't set User-Agent

### ISSUE THREAD

**Issue by Leonard-Peng** [scrapy/scrapy#2088]
If I use DEFAULT_REQUEST_HEADERS to set `User-Agent`, it doesn't work.

```python
DEFAULT_REQUEST_HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, sdch',
    'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4',
}
```

I know I can set `User-Agent` for  crawler  by using USER_AGENT setting key:

```python
# settings.py
USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36'
```

I think this behaviour is not corresponding with the doc [User Agent](http://doc.scrapy.org/en/latest/topics/settings.html#user-agent) and [DefaultHeadersMiddleware](http://doc.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware) (_This middleware sets all default requests headers specified in the DEFAULT_REQUEST_HEADERS setting._)

If this behaviour is designed, maybe the doc should be modified.

Thanks.

**Comment by redapple** [comment]
This happens because of the default downloader middlewares order.
Currently, in [default_settings.py](scrapy/scrapy/settings/default_settings.py), it's:
```
DOWNLOADER_MIDDLEWARES_BASE = {
    # Engine side
    'scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware': 100,
    'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware': 300,
    'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware': 350,
    'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': 400,
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': 500,
    'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware': 550,
    'scrapy.downloadermiddlewares.ajaxcrawl.AjaxCrawlMiddleware': 560,
    'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware': 580,
    'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 590,
    'scrapy.downloadermiddlewares.redirect.RedirectMiddleware': 600,
    'scrapy.downloadermiddlewares.cookies.CookiesMiddleware': 700,
    'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': 750,
    'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware': 830,
    'scrapy.downloadermiddlewares.stats.DownloaderStats': 850,
    'scrapy.downloadermiddlewares.httpcache.HttpCacheMiddleware': 900,
    # Downloader side
}
```

so for an outgoing `Request`, `UserAgentMiddleware` runs first and sets the value from `USER_AGENT`, either from your `settings.py`, or, the default (from [default_settings.py](scrapy/scrapy/settings/default_settings.py))

```
USER_AGENT = 'Scrapy/%s (+http://scrapy.org)' % import_module('scrapy').__version__
```

then, `DefaultHeadersMiddleware` runs, but the value is already set, so User-Agent header doesn't get updated.

A couple of options I see:

- remove default `USER_AGENT` from default_settings.py so that `UserAgentMiddleware` doesn't set a default value before `DefaultHeadersMiddleware` sees the request and if you don't set `USER_AGENT` in your `settings.py`
- change the order of the middlewares so that `DefaultHeadersMiddleware` runs before `UserAgentMiddleware`

**Comment by eLRuLL** [comment]
I think changing the order on the middlewares could be a very good solution, as specifying `DEFAULT_REQUEST_HEADERS` is something the user does by conscience, as `USER_AGENT` could be avoided on a simple project
