### ISSUE TITLE
Custom ImagesPipeline doesn't generate thumbnails

### ISSUE THREAD

**Issue by briehanlombaard** [scrapy/scrapy#2198]
For some reason, when using a customised ImagesPipeline thumbnails are no longer generated. This seems to be the case for 1.1.1 and 1.1.2 but not for 1.0.0 so somewhere between those releases something must have changed.

This [example](https://gist.github.com/briehanlombaard/b19885f99b9ee26363070fd9883695b9) should reproduce the problem.

**Comment by redapple** [comment]
@briehanlombaard , did you mean _but not for 1.1.0 _?

**Comment by briehanlombaard** [comment]
@redapple I actually didn't try that version until now, but it does seem to work as well. So the problem must be somewhere between 1.1.0 and 1.1.1

**Comment by briehanlombaard** [comment]
I used [git bisect](https://gist.github.com/briehanlombaard/02d2ff5c6d590de621be1b60640ae66f) to track down the 'bad' commit at https://github.com/scrapy/scrapy/commit/c6277c9963af24d1a61fa201693fafdd46426ee8. I'll see if I can get a fix for the issue if one is needed. I might just be doing something wrong.

**Comment by redapple** [comment]
@briehanlombaard , thank you for continuing the investigation.
I can confirm that thumbnails are not generated with your example starting from scrapy 1.1.1 (worked on 1.1.0)
I'll also have a look in more details.

**Comment by redapple** [comment]
@briehanlombaard , so the trouble is indeed with that commit you linked.
Current implementation is looking for `ARTICLEIMAGESPIPELINE_IMAGES_THUMBS` without looking for `IMAGES_THUMBS`, contrary to what is done for `IMAGES_STORE`, and contrary to what the docs currently say.
@pawelmhm , it looks like we still have a backward incompatibility issue with https://github.com/scrapy/scrapy/pull/1891 and the subsequent fix in https://github.com/scrapy/scrapy/pull/1989
@briehanlombaard's use-case look very reasonable:
- custom ImagesPipeline but only for converting, so any setting change
- use of custom settings for `IMAGES_STORE` and `IMAGES_THUMBS`, like the docs recommend

**Comment by djunzu** [comment]
@redapple , I am not sure it is a bug. It was coded to work just like that. See [this test](https://github.com/scrapy/scrapy/blob/master/tests/test_pipeline_images.py#L324). I don't remember details, but if i am not wrong it was coded in this way to accommodate class attributes in custom ImagesPipelines.

I think that in order to do this given example work it would be necessary some backward incompatibility with class attributes. And, as far as we know, there is no backward incompatibility with class attributes now.

Maybe the way to go now should be just improve the docs and better explain how to create/use custom pipelines.

@briehanlombaard , you should precede `IMAGES_THUMBS` with your custom ImagesPipeline class name:

```python
custom_settings = {
    'ITEM_PIPELINES': {
        'spider.ArticleImagesPipeline': 100,
    },
    'IMAGES_STORE': 'articles',
    #'IMAGES_THUMBS': {
    'ARTICLEIMAGESPIPELINE_IMAGES_THUMBS': {
        'small': (290, 150),
        'medium': (610, 320),
    },
    'AUTOTHROTTLE_ENABLED': True,
}
```
