### ISSUE TITLE
process_spider_exception() not invoked for generators

### ISSUE THREAD

**Issue by Mimino666** [scrapy/scrapy#220]
When a spider implements _parse()_ function through generator (i.e. returning results with _yields_) and an exception raises in _parse()_, then spidermiddleware's _process_spider_exception()_ is not called.

The reason is that exception is finally invoked in one of the spidermiddlewares.

**Comment by lezorich** [comment]
Hi! I want to start contributing to scrapy fixing this issue. I want to fix the bug using the solution proposed by @dangra: call ```process_spider_output``` til the generator fails and then call spidermiddleware's ```process_spider_exception```. 

I have been looking scrapy source code for a while now and I think the solution must be somewhere in here [1] (https://github.com/scrapy/scrapy/blob/master/scrapy/core/spidermw.py#L69), [2] (https://github.com/scrapy/scrapy/blob/master/scrapy/core/scraper.py#L127) but still can't figure out where should the fix go. I also already looked at twisted Deferreds documentation, so I know more or less how it works :)

From what I have understood, the spidermiddleware ```process_spider_output``` and ```process_spider_exception``` are called [here] (https://github.com/scrapy/scrapy/blob/master/scrapy/core/spidermw.py#L69):

```
dfd = mustbe_deferred(process_spider_input, response)
dfd.addErrback(process_spider_exception)
dfd.addCallback(process_spider_output)
```

But the spider ```parse()``` returns a generator right? so ```process_spider_output``` is called because no exception has been raise yet. Because ```process_spider_output``` is called, the scraper thinks that everything is fine, so each spidermiddleware ```process_spider_output``` is called, where finally the exception is invoked. 

I think that I have a good understanding of what's happening below the hood, but I still think that I'm missing something, that's why I wanted to ask if someone can guide me a little here. 

Thanks!!

**Comment by souravsingh** [comment]
I would like to work on this issue.I would like to know how should I start with it?

**Comment by vionemc** [comment]
https://github.com/llonchj/scrapy-sentry

That module will help

**Comment by jeebb** [comment]
To whom it may concern, I used **spider_error** signal as a work-around for this issue (https://doc.scrapy.org/en/latest/topics/signals.html)

**Comment by Hades1996** [comment]
i was trying to make a custom spider middleware to handle exceptions with process_spider_exception method but still doesn't work

@jeebb that saved me, thanks!

**Comment by dangra** [comment]
https://github.com/scrapy/scrapy/pull/2061 from @elacuesta is in the right direction IMHO.

**Comment by dalepo** [comment]
@jeeb can you provide an example?
I tried  the following
`self.crawler.signals.send_catch_log(failure=ex, signal=signals.spider_error, response=response, spider=self)`

But still, process_spider_exception did not call

**Comment by amineallani** [comment]
The workaround i used for this issue was **decorators** : 

First, you need to define the decorator at the top of the file ( before the spider class ) : 

`def handle_exceptions(function):
    def parse_wrapper(spider, response):
        try:
            for result in function(spider, response):
                yield result
        except YourException:
            # handle exception here
            yield next(spider.start_requests())
    return parse_wrapper`

To use it:

@handle_exceptions
def parse(self, response):

**Comment by ariasuni** [comment]
I want to be able to log response headers, text, and meta when any exception occurs so that I can analyze it later on, it would be really useful for websites that have random bugs, or to see information about the bug without the need to launch the spider again.

Do I really need to put a decorator on each and every parse function I use?

**Comment by amineallani** [comment]
Each error prone funtion, where you need to catch the exception needs to be decorated.

**Comment by elacuesta** [comment]
For the record, this decorator approach is only one of the available workarounds while this problem is still present. If you only need to log information about the exceptions, personally I think the best option would be to write an extension (https://doc.scrapy.org/en/latest/topics/extensions.html) that listens to the `spider_error` signal (https://doc.scrapy.org/en/latest/topics/signals.html#spider-error), as pointed out by @jeebb.
Keep in mind that the purpose of the `process_spider_exceptions` method is to be able to _recover_ from exceptions by returning items or requests, while the signals feature only allow listeners to be notified about events.

**Comment by ariasuni** [comment]
@elacuesta Thank you for you help, it’s working for me!

**Comment by PhilipGarnero** [comment]
I came across the exact same issue but I also wanted to be able to send errors happening in the items pipeline to be dispatched to sentry. I ended up using signals for both problems. Here is the code for anyone having the issue :

```.py
# Custom signal used to catch errors from pipelines
pipeline_error = object()

class SentryMiddleware(object):
    """This class is used to catch errors happening in the spiders or the pipelines"""
    def __init__(self):
        self.client = Client(dsn=settings.SENTRY_DSN)

    @classmethod
    def from_crawler(cls, crawler):
        inst = cls()
        # There is a bug that prevents errors to be received via `process_spider_exception`
        # so we use an internal signal automatically dispatched in case of errors instead
        crawler.signals.connect(inst.process_spider_exception_from_signal, signal=signals.spider_error)
        # We listen to a custom made signal we implemented in order to receive errors from pipelines
        crawler.signals.connect(inst.process_pipeline_exception_from_signal, signal=pipeline_error)
        return inst

    def process_spider_exception(self, response, exception, spider):
        self.client.extra_context({"page_url": response.url, "spider_name": spider.name})
        # sys.exc_info() is not working because the exception has been handled already
        # so we build a fake exc info (type, value, traceback)
        self.client.captureException(exc_info=(type(exception), exception, exception.__traceback__))

    def process_spider_exception_from_signal(self, response, failure, spider, **kwargs):
        exception = failure.value
        self.process_spider_exception(response, exception, spider)

    def process_pipeline_exception_from_signal(self, exception, item, pipeline, spider, **kwargs):
        self.client.extra_context({"item": item, "pipeline_name": pipeline.__class__.__name__, "spider_name": spider.name})
        # sys.exc_info() is not working because the exception has been handled already
        # so we build a fake exc info (type, value, traceback)
        self.client.captureException(exc_info=(type(exception), exception, exception.__traceback__))


class AcknowledgeErrorsPipeline(object):
    """
    Every pipeline we use should be subclassed from this one in order for sentry to receive errors.
    Note: This pipeline does not work alone, the `SentryMiddleware` needs to be enabled in order for errors to be sent
    Note: It does not work with pipelines that retrigger requests because
          the request callbacks would not be wrapped with `handle_exceptions` (but you can still wrap them yourself)
    """
    def __init_subclass__(cls, **kwargs):
        # We use this new python feature in order to avoid using a full fledged metaclass
        # for the simple purpose of wrapping a method
        cls.process_item = AcknowledgeErrorsPipeline.handle_exceptions(cls.process_item)
        super().__init_subclass__(**kwargs)

    @classmethod
    def from_crawler(cls, crawler):
        inst = cls()
        inst.signals = crawler.signals
        return inst

    @staticmethod
    def handle_exceptions(process_item):
        def wrapper(self, item, spider, **kwargs):
            try:
                return process_item(self, item, spider, **kwargs)
            except Exception as e:
                # If we catch an exception, we send it as a signal so that `SentryMiddleware` can receive it
                self.signals.send_catch_log(
                    signal=pipeline_error,
                    exception=e, item=item,
                    pipeline=self, spider=spider
                )
                # And we raise it again to prevent disturbing the normal process
                raise e
        return wrapper
```
