### ISSUE TITLE
How to insert time-dependent parameter?

### ISSUE THREAD

**Issue by caizixian** [scrapy/scrapy#2223]
For example, if I have a spider like this
```
import time

class Spider1(scrapy.Spider):
    name = "spider"
    allowed_domains = ["example.com"]
    start_urls = ["https://www.example.com/index.html"]
    def parse(self, response):
        for page in range(1,5000000):
            request = scrapy.Request("https://www.example.com/{}.html".format(page),
                                     method='POST',
                                     body=json.dumps({"time":time.time()}))
            yield request
```
All the `time` in POST requests will be the time when the request is scheduled.

What should I do to make the `time` be the actual time when the request is sent.

Tried to write middlewares to fill in the parameters, but it seems that the middleware methods are also called when the request is scheduled.

**Comment by kmike** [comment]
Hey @caizixian,

Check http://doc.scrapy.org/en/latest/topics/architecture.html: spider middleware methods are called when a request is scheduled, but downloader middleware methods are called when requests are put to/from downloader. They still may spend some time in downloader queue without being fetched though. There is also `download_latency` request.meta key which contains time between download start and download end, I think if you subtract it from the current time it'd be closest to the actual time request is sent.

Hope this helps. I'm closing this issue because we're trying to use issue tracker to track Scrapy bugs and feature requests, not as a support channel. The preferred support channel is http://stackoverflow.com (use "scrapy" tag).

**Comment by caizixian** [comment]
Sorry for still commenting here.

Could you please clarify this to me: how does scheduler decide when to put requests to downloader queue?

For instance, in the example above, it seems that tons of requests are scheduled in short intervals. Will these scheduled requests be added to the downloader queue immediately or be added to the queue when concurrent requests, let's say, are lower than `CONCURRENT_REQUESTS` . 

In my own experiment, I wrote a downloader middleware which will insert some data into Redis database when the `process_request` is invoked. 

And I opened `redis-cli monitor` to monitor DB operations. Whether I call inserting when the request object is being constructed or the `process_request` is invoked, I can always see hundreds of db logs which is way more than download speed.

**Comment by kmike** [comment]
There is a buffer in Downloader, there can't be more than `CONCURRENT_REQUESTS` requests at the same time in Downloader. Requests are moved from a scheduler queue to downloader queue when there is a vacant place in downloader queue. 

When request is in downloader queue, it is doesn't always start to download immediately because downloader handles per-domain and per-ip rate limits.

> And I opened redis-cli monitor to monitor DB operations. Whether I call inserting when the request object is being constructed or the process_request is invoked, I can always see hundreds of db logs which is way more than download speed. 

Are you sure the configuration is proper, i.e. you're using your middleware as a downloader middleware?

Another reason which may cause that is redirect handling. If a redirect is detected, Downloader issues a new request and puts it to the scheduler, with a higher priority; if there is a lot of redirects you may see activity in process_request, but no pages processed by a spider.

HTTP cache may also cause that: you don't have to download these pages, but they are still sent through downloader middlewares.

Maybe CONCURRENT_REQUESTS is the reason - if the value is high, but per-domain rate limit is low, then initially there will be many process_request calls, but not a lot of download requests.

**Comment by caizixian** [comment]
Here is the code.
And if I recall correctly, there's no redirect.

In order to set the body to correct value, I wrote a middleware like this. Is it possible that the new constructed request object (because body cannot be modified) cause the issue?
```
class MyDownloaderMiddleware(object):

    def __init__(self, settings):
        pass

    @classmethod
    def from_crawler(cls, crawler):
        return cls(crawler.settings)

    def process_request(self, request, spider):
        r.incr('counter')
        return request.replace(body=json.dumps({"time":time.time()}))
```

**Comment by kmike** [comment]
@caizixian yes; if you return a new request in a downloader middleware request goes back to the scheduler. From docs:

> If it returns a Request object, Scrapy will stop calling process_request methods and reschedule the returned request.

**Comment by caizixian** [comment]
It's the closest solution that I can think of by using scrapy. Don't know whether there are more elegant solutions.

**Comment by kmike** [comment]
Yeah, it looks like that. To make it somehow work you can assign a high priority for these new requests, i.e. use `.replace(body=..., priority=1000)`. This way requests with time set will be processed without a large delay. You also need to check that the body is only replaced once, e.g. you can put a flag to request.meta. 

I think as a hack you can also use `request._body = ...` and don't return a new request.

**Comment by caizixian** [comment]
Yeah. I checked whether the body is modified or not in real code.

Will educate myself on the priority thing. Thanks again.
