### ISSUE TITLE
Support .format() compatible FEED_URI

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2265]
I wanted to add a new `%(date)s` [for FEED_URI](http://doc.scrapy.org/en/latest/topics/feed-exports.html#storage-uri-parameters) but then I thought we may as well upgrade the formatting support to the more modern [format string syntax](https://docs.python.org/2/library/string.html#format-string-syntax).

What do you think?

**Comment by kmike** [comment]
it'd be backwards incompatible, right?

**Comment by redapple** [comment]
Not necessarily if we can catch the formatting error with `%` and then try `.format()` (or the other way round)
This conversion only happens once, right?

**Comment by kmike** [comment]
I'm not fond of catching formatting errors because there can be format strings valid in both syntaxes; in fact, a string with `{}` but without `%` is a valid format string for `%` formatting. 

We also use %(date)s format in logs (like Python stdlib logging module); this can't be changed (because stdlib only supports this format); it means that if we add new formst specifiers there will be two 'mini-template' languages in scrapy settings.

**Comment by redapple** [comment]
Right. Makes sense.
