### ISSUE TITLE
Scrapy alert when scraping result suspiciously shows a lot of missing data

### ISSUE THREAD

**Issue by vionemc** [scrapy/scrapy#2360]
One of the biggest worries of web scraping is when the site changes and the script should be changed adapting to the site's change. It will be great if Scrapy can show and send an alert when those abnormalities show up. Does Scrapy has any plan of applying such feature?

**Comment by redapple** [comment]
Deciding when a spider "breaks" because of website change is a hard problem and depends a lot on the website.
Scrapy has a [stats collection feature](https://docs.scrapy.org/en/latest/topics/stats.html) (with many built-in stats counts, but that callbacks could also write to), [signals](https://docs.scrapy.org/en/latest/topics/signals.html) and [extension possibilities](https://docs.scrapy.org/en/latest/topics/extensions.html) for users to build their own monitoring component.
There's no plan to have this built-in. But someone from the community may come up with a plugin for scrapy to do just that.

**Comment by Digenis** [comment]
@vionemc, also see https://doc.scrapy.org/en/latest/topics/contracts.html

**Comment by vionemc** [comment]
That's very helpful! Thanks!

**Comment by redapple** [comment]
@vionemc , I'm closing this issue. I assume you found @Digenis link useful.
