### ISSUE TITLE
I don't know how to install this

### ISSUE THREAD

**Issue by lksy0217** [scrapy/scrapy#2406]
```
    running build_ext
    building 'lxml.etree' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "c:\users\jongho\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\JongHo\\AppData\\Local\\Temp\\pip-build-yh509eor\\lxml\\setup.py';f=g
etattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\JongHo\AppData\Local\Temp\pip-629uwerr-record\in
stall-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\JongHo\AppData\Local\Temp\pip-build-yh509eor\lxml\
```

**Comment by redapple** [comment]
What command did you issue?
Did you try installing scrapy using pip? (`pip install scrapy`)
Note that Scrapy is not yet officially supported on Python 3 (because Twisted -- one of the major dependencies of Scrapy -- is not being officially supported on Python 3 and Windows)

Also note that some users have more success using Anaconda to work with scrapy, lxml and Twisted on Windows, and even with Python 3. See https://docs.scrapy.org/en/latest/intro/install.html#anaconda

**Comment by elacuesta** [comment]
Closing due to lack of feedback. Also Scrapy now officially supports Python 3, and `conda` is the recommended way of [installing on Windows](https://docs.scrapy.org/en/latest/intro/install.html#windows)
