### ISSUE TITLE
S3FilesStore: add option for AWS Signature v4 support

### ISSUE THREAD

**Issue by vshlapakov** [scrapy/scrapy#2448]
Newer AWS locations will only authenticate clients that use AWS Signature Version 4.
For example, when using `Images` addon with a custom S3 location you can encounter with:
```
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```
The problem is pretty well known: https://github.com/boto/boto/issues/2741.

Boto library [supports](https://github.com/boto/boto/blob/2.39.0/boto/auth.py#L1025) v4 if you pass a host explicitly and set `S3_USE_SIGV4` envvar. It's a bit [different](https://github.com/boto/botocore/issues/424#issuecomment-68394401) for `botocore`, but should work fine when providing a region short name.

My proposal is to implement it in a similar way to this [approach](https://github.com/danilop/yas3fs/issues/101): `S3FilesStore` could handle new `AWS_HOST` and `AWS_S3_USE_SIGV4` settings, use it to set a corresponding envvar and pass the host to `boto.S3Connection`(or extract the region from host and pass it to botocore client).

**Comment by icenine457** [comment]
I'm looking for a Python project to contribute to, and would like to offer to help with this if possible. This feels like something I could reasonably wrap my head around.

**Comment by aodj** [comment]
I ran into this whilst trying to get the `scrapy.pipelines.files.FilesPipeline` plugin to work with my S3 bucket in Frankfurt. Since Frankfurt requires v4 signatures, I ended up subclassing both the `S3FilesStore` and `FilesPipeline` classes to implement a workaround for this.

You can see what I did in this [gist](https://gist.github.com/aodj/f29e83b768a4e65894f91f686a97a9d6); it requires setting the key id, secret key and region to connect to, and replaces the S3 store object on the subclass of `FilesPlugin`, but seems to work.

**Comment by redapple** [comment]
@aodj , thanks for your input.
@vshlapakov , I would leave out the `boto`-way. Making `botocore` work with V4 signatures looks straightforward enough (I tried on `S3FeedStorage`).
And if `botocore` works, we can recommend users to install it.

**Comment by starrify** [comment]
Just FYI that it looks to me that the issue has been fixed in botocore 1.5.71 (the [changelog](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#1571)).
I have tested using two versions of botocore, by trying to upload a file to a new region which is SigV4 only:

- Using `botocore==1.5.8`: `botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the PutObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`
- Using `botocore==1.5.86` (the currently latest version from PyPI): It successfully works.

cc @redapple

**Comment by redapple** [comment]
@starrify , thanks. Yep. I also noticed that in my tests.

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/2841#issuecomment-1024160940
