### ISSUE TITLE
Scrapy asynchronous behaviour : how to bypass it and wait for a result to perform a new Request ?

### ISSUE THREAD

**Issue by younesherlock** [scrapy/scrapy#2453]
Hello,

My code aims to scrape a webpage (the one in start_urls) to retrieve a number in a "Show More" button.
This number will then be used as a parameter to request a URL that will return a JSON that contains data + a number. This last number will be used as a parameter to request the URL that will return a JSON  that contains data + a number, etc.. The process goes on until the JSON return empty data + a number. When the data is empty, the scraper should stop.

Could you give me an example of a code that does a similar thing ?

**Comment by kmike** [comment]
Hey @younesherlock,

We're using Scrapy issue tracker to track Scrapy bugs and feature requests; you may get better answers at http://stackoverflow.com (use tag 'scrapy') - this is our official support channel.

To populate items from multiple pages you have two main options:

1. Pass incomplete data in request.meta. See https://doc.scrapy.org/en/latest/topics/request-response.html#topics-request-response-ref-request-callback-arguments for an example.
2. Use a third-party project called scrapy-inline-requests: https://github.com/rolando/scrapy-inline-requests.

I'm closing this ticket since it should be better served as a stackoverflow question.
