### ISSUE TITLE
Scrapy loses trailing ?

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#2472]
Scrapy 1.2.1
If I populate start_urls with:
http://localhost/myfile.json?

My actual request (as well as the contents of response.url) is to:
http://localhost/myfile.json

Note the trailing **?** has been removed.

I don't know if there are any servers that will give a different response depending on whether the ? is there or not, however I'm recording the URL's as keys, so the fact that my return URL is different from my sending-url is making life difficult.

I can work around it, but I suspect this isn't meant to be happening, hence the report.

**Comment by kmike** [comment]
Hey @mohmad-null,

Interesting point about `?`; it is w3lib.url.safe_download_url function which removes it (it calls `urlsplit` and then `urlunsplit` from stdlib, and `?` is not preserved in this case). 

There are other cases when URL will be changed: 

* fragment is removed;
* non-ascii characters are escaped.

Note that response.url can be also different from request.url and response.request.url. So for now if you need a key it is better to set it explicitly - use start_requests instead of statu_urls and put the key to request.meta. Another option is to use [scrapy.request.request_fingerprint](https://github.com/scrapy/scrapy/blob/cc06b6b1f68d33c1a5e5429d6dfb9b39577624fe/scrapy/utils/request.py#L19) - this is what Scrapy itself uses for key (e.g. in dupefilters).

**Comment by mohmad-null** [comment]
Hi @kmike
Thanks for the thoughts; I've not encountered your two cases as yet. I'll have a look at the request_fingerprint method; it looks like it may be useful.

**Comment by Gallaecio** [comment]
Should we close this?
