### ISSUE TITLE
Scrapy incompatible with twisted 17.1.0 on TLS/SSL enabled websites.

### ISSUE THREAD

**Issue by Unode** [scrapy/scrapy#2555]
Referencing #2479

Running `pip install scrapy` on a new virtualenv got me Twisted 17.1.0.
Quite a lot of HTTPS websites started to fail (e.g. google) with a twisted error `SSL23_GET_SERVER_HELLO - tlsv1 alert internal error`.

The main cause of the SSL23 error is that code introduced after #1794 on [core/downloader/tls.py](https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/tls.py#L49) imports `_maybeSetHostNameIndication` which has been removed from [_sslverify.py](https://github.com/twisted/twisted/blob/twisted-17.1.0/src/twisted/internet/_sslverify.py).
This code is also wrapped on a large `try: ... except ImportError: pass` which silences the actual cause of the problem. 

Manually downgrading twisted to 16.0.0 solved the problem.
Also to avoid these incompatibilities shouldn't scrapy on pypi be limited to known working versions of dependencies?

```
Scrapy    : 1.3.1
lxml      : 3.7.2.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 3.4.5 (default, Jan 24 2017, 17:55:08) - [GCC 4.9.3]
pyOpenSSL : 16.2.0 (OpenSSL 1.0.2j  26 Sep 2016)
Platform  : Linux-4.6.0-sabayon-x86_64-Intel-R-_Core-TM-_i7-4710MQ_CPU_@_2.50GHz-with-gentoo-2.2
```

**Comment by Rafalonso** [comment]
Yup, just noticed on a fresh install.

```
[scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://renegadeline.com/robots.txt> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'tlsv1 alert internal error')]>]
```

This solution is not working https://github.com/scrapy/scrapy/issues/1429#issuecomment-131782133

**Comment by pawelmhm** [comment]
seems like this commit    https://github.com/twisted/twisted/commit/7180789ddaa901e93fd2d786fdb1749ba39ae493#diff-df501bac724aab523150498f84749b88L53 removed:  `_maybeSetHostNameIndication`.

Looking at the code `set_tlsext_host_name` should have same name as this old deprecated method. I wonder why we need such wrapper that we have there, comment says it is there so that connection is not closed and we log warnings, would be good to check if this still applies after cleanups in Twisted.

**Comment by kmike** [comment]
Thanks @Unode for the detailed report and for the debugging, it was helpful!

**Comment by Unode** [comment]
Cheers everyone. Thanks for the quick fix!

**Comment by glyph** [comment]
> Also to avoid these incompatibilities shouldn't scrapy on pypi be limited to known working versions of dependencies?

In this case, the API begins with an `_`, which means it's private, and scrapy just shouldn't be using it at all.

We go to some trouble in Twisted to make it very difficult to do what Scrapy is doing here; HTTPS certificate errors _should_ result in connection errors, otherwise, what is the point of HTTPS?

Having a better understanding of why Scrapy needs this might help us deliver said functionality from the Twisted side.

**Comment by kmike** [comment]
@glyph thanks for all the help you're providing for debugging Twisted+Scrapy issues, it is really helpful! 

By default Scrapy warns in case of HTTPS failures, not raises an error; this required some copy-pasting which involved `_` method in Twisted < 17. There is a lot of half-broken https websites which users still want to scrape. I'm not sure what the problem is with `https://renegadeline.com` website though: it is not passing https checks when downloading with scrapy/twisted, but it works fine in a browser (firefox or chrome, OS X).

 @redapple must know more about all this stuff :) Relevant code is at https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/contextfactory.py and https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/tls.py.

**Comment by glyph** [comment]
@kmike Glad to help!

@redapple - Looking forward to hearing more about the use-case :).
