### ISSUE TITLE
Scrapy will fill all slots with the same, waiting domain

### ISSUE THREAD

**Issue by milescrawford** [scrapy/scrapy#2638]
If you have a polite DOWNLOAD_DELAY and CONCURRENT_REQUESTS_PER_DOMAIN, Scrapy will happily fill up all of its slots with requests going to a single domain, and essentially sit idle.

A crawl will last at least as long as it takes to crawl the most numerous site, but when waiting for a particular site, Scrapy ignores possible concurrent activity which prolongs the crawl a lot.

Scrapy has all the information required to re-queue requests going to a domain which is already waiting on delays or concurrency limits. Could it be extended to do this?

**Comment by kmike** [comment]
Yeah, this is a known issue. 

I think it should be solved at scheduler level, because re-scheduling has its own issues - for example, downloader middleware will run multiple times.

There are some workarounds; if crawl resume is not required then something like https://github.com/scrapy/scrapy/issues/2474#issuecomment-273925292 works fine; there is also https://github.com/scrapinghub/frontera which may work better for larger-scale crawls, it also doesn't have this problem.

See also: https://github.com/scrapy/scrapy/issues/2623 and https://github.com/scrapy/scrapy/issues/2474.
