### ISSUE TITLE
why Request(url can not be response.url)

### ISSUE THREAD

**Issue by ReZeroS** [scrapy/scrapy#2662]
I have a question, anyone can help me?
my code is here:

http://paste.ubuntu.com/24200006/

the question is why the call_back will not run when the  Request has a args is response.url

**Comment by redapple** [comment]
@ReZeroS , we use GitHub issues for bug reports and feature and architecture discussion.
Your question is more suited for [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) (use "scrapy" tag) or [scrapy-users](https://groups.google.com/forum/#!forum/scrapy-users) user group.
As for your specific problem, I believe it's because Scrapy has a default duplicate request filter, so with
```
    def parse(self, response):
        yield Request(response.url, self.parse_y)
```
you are requesting the same URL twice. If you want to bypass the duplicate request filter, you can use [`dont_filter=True`](https://doc.scrapy.org/en/latest/topics/request-response.html?highlight=dont_filter#request-objects) as an argument when creating `Request()` instances.
