### ISSUE TITLE
image download keep original name

### ISSUE THREAD

**Issue by premiumwd** [scrapy/scrapy#2684]
Hi,

I am really interested in knowing to remove sha1 and keep original name of image downloaded using scrapy. I am using this to mass audit website and optimize it with gulp for easy convert and replace. Please advise.

**Comment by redapple** [comment]
Does this help?
https://stackoverflow.com/questions/37042251/change-naming-convention-for-images-pipeline/37069627#37069627
Note that with ImagesPipeline, images get converted to JPEG by default. You may want to use FilesPipeline to keep original files.

**Comment by kmike** [comment]
There is no such a thing as "original name" because images can be auto-generated; we can only rely on heuristics to get a file name from the URL. See also: https://github.com/scrapy/scrapy/pull/1548. 

I think you can use FilesPipeline instead of ImagesPipeline to try preserving image file name, maybe a subclass with overridden `file_path` method.
