### ISSUE TITLE
Scraping semantic data: perhaps an extension

### ISSUE THREAD

**Issue by arvindpdmn** [scrapy/scrapy#2697]
This is a feature request.

I understand that it's possible to add custom extensions. I am proposing extension(s) to scrape semantic data. To my knowledge, many web pages use one of these:
- Microdata
- Opengraph
- Parsley

Typically, the data extracted will include date of publishing, author name, site name, title, main image URL, etc. Since not all pages on the web are using semantic markup, the extension can also have a feature to create custom mapping: css/xpath selection mapped to relevant data.

What do you think? Any pointers on how to create a custom extension? Thx.

**Comment by kmike** [comment]
Hi @arvindpdmn,

There are libraries like https://github.com/scrapinghub/extruct and https://github.com/Parsely/schemato which allow to scrape semantic data. I'm not sure we should add anything built-in to Scrapy, maybe some documentation. Having such libraries separated from Scrapy is a better architecture because it allows to 1) use them without Scrapy, and 2) avoid making Scrapy larger. Contributions to these libraries is welcome!

**Comment by arvindpdmn** [comment]
Correct. I am not suggesting adding to scrapy's core. But it makes sense to make it an extension. If there are hundreds of extensions, perhaps we should have a hosted distribution point to discover and install them. Anyway, just an idea.

Thx for the links. I'll see if they can be loaded as scrapy's extensions.

**Comment by redapple** [comment]
We try and collect non-Scrapy-core extensions and add-ons under a seperate organization: https://github.com/scrapy-plugins
If you come up with an extension you want to share under scrapy-plugins, please contact us on the [mailing list](https://groups.google.com/forum/#!forum/scrapy-users).
Thank you @arvindpdmn
