### ISSUE TITLE
Import Request in the Template file

### ISSUE THREAD

**Issue by zhongdai** [scrapy/scrapy#2733]
I have been creating many spiders recently, and I noticed I had to add below line every time

`from scrapy.http import Request`

I think for most cases we need the Request to crawl to other pages, only for very simple spider we don't need that. Is it possible to include that line to the template?

**Comment by kmike** [comment]
The intention is for users to use `scrapy.Request`, `import scrapy` is already in the template. Does it work for you?

**Comment by zhongdai** [comment]
Thanks for the quick the response. I didn't noticed `Request` has been declared on the top level, I checked the API document and always use it from` scrapy.http`.

That is fair enough, and please close this issue.

**Comment by kmike** [comment]
Yeah, it'd be nice to mention the shortcut in API docs for Request object: https://doc.scrapy.org/en/latest/topics/request-response.html.

**Comment by keremgocen** [comment]
I'd like to grab this if that's ok

**Comment by marlenachatzigrigoriou** [comment]
Hello! Is this issue still open? Does @keremgocen carry this? If not, could you give me some guidance on what needs to be done (as it was reopened) in order to contribute?

**Comment by Gallaecio** [comment]
This is still open indeed, and it seems like there has been no attempt to address it after https://github.com/scrapy/scrapy/pull/2757, which seems abandoned.

**Comment by marlenachatzigrigoriou** [comment]
Great. Could you give me more guidance on what I should do? I saw your comment https://github.com/scrapy/scrapy/pull/2757#discussion_r263744493 and I assume that I have to begin from this point.

**Comment by Gallaecio** [comment]
Yes.

It’s relatively hard to find what I mention in this comment, but referencing all import paths looks like this:

```python
.. class:: scrapy.http.request.Request
.. class:: scrapy.http.Request
.. class:: scrapy.Request(…)
```

Then there are some possible additional changes to make, but it’s up to you whether to make them or not, since they are not covered by this issue report:

- The same could be done for other classes that have a top-level import in https://github.com/scrapy/scrapy/blob/master/scrapy/__init__.py
- In addition to covering all import paths in the reference documentation, you could search the documentation (and even the docstrings in code) for references to the longer import paths, and switch those usages to the short import path, as the shortest import path should probably be the recommendation in the documentation.

**Comment by marlenachatzigrigoriou** [comment]
So, the purpose is to change every long import path in the documentation files, such as: `.. class:: scrapy.http.request.Request` and `.. class:: scrapy.http.Request` to: `.. class:: scrapy.Request(…)` ?
And this change should be applied to every class declared as top-level in  https://github.com/scrapy/scrapy/blob/master/scrapy/__init__.py:
```
# Declare top-level shortcuts
from scrapy.spiders import Spider
from scrapy.http import Request, FormRequest
from scrapy.selector import Selector
from scrapy.item import Item, Field
```
For example, in [request-response.rst](https://github.com/scrapy/scrapy/blob/master/docs/topics/request-response.rst) line 42 (`:meth:` `~scrapy.spiders.Spider.parse` ` method will be used.`) should become: ` meth: ` `~scrapy.Spider.parse` `  method will be used.`  ?

**Comment by Gallaecio** [comment]
Yes.

The long import paths should only appear once, right above the APi member reference documentation (`.. class:: scrapy.Request(…`), just so that it’s clear that those import paths exist, and so that documentation linking to the Scrapy documentation using InterSphinx continues to work even if it uses the long import paths for API references.

**Comment by marlenachatzigrigoriou** [comment]
Regarding the APi member reference documentation, you mean that, for example: in  [request-response.rst](https://github.com/scrapy/scrapy/blob/master/docs/topics/request-response.rst) in line 491: ` .. class:: FormRequest(url, [formdata, ...])` should turn into: `.. class:: scrapy.FormRequest(url, [formdata, ...]) ` ?

**Comment by Gallaecio** [comment]
Yes. And in addition to that, lines should be added above that line with the other import paths, as in [my example above](https://github.com/scrapy/scrapy/issues/2733#issuecomment-818651071).

**Comment by keremgocen** [comment]
Hey @marlenachatzigrigoriou, sorry I had to drop this. Feel free to drop a comment here if there are any blockers I'm sure someone will help.
