### ISSUE TITLE
Scrapy with Python MPI module

### ISSUE THREAD

**Issue by abhisharma7** [scrapy/scrapy#2736]
I am using Scrapy from almost 1 years I started it in a very naive way but now I started building up queues for different crawling request, but the biggest challenge I am facing is its lack of scalability it can only run on one machine with 32 threads. Does anyone implemented a solution which could scale Scrapy to multiple machines with one machine act as a master node.

I am writing a script to integrate MPI library on top of Scrapy so that it could be run on cluster. If you guys are aware with any of the existing solution please share. 

Thanks
Abhishek

**Comment by kmike** [comment]
Hey @abhisharma7,

There are several projects which allow to distribute Scrapy load to several machines, e.g. https://github.com/scrapinghub/frontera, https://github.com/istresearch/scrapy-cluster, https://github.com/rolando/scrapy-redis. Sometimes it is enough to just split seed URL list into N parts and start N processes on different machines, without a central queue. 

I'm closing this ticket because we're using Scrapy issue tracker to track Scrapy bugs and features requests, and this looks like a discussion ticket. There are better places for such discussions like [scrapy-users](https://groups.google.com/forum/?fromgroups#!forum/scrapy-users) list, https://www.reddit.com/r/scrapy/ or https://stackoverflow.com (use tag "Scrapy").
