### ISSUE TITLE
CLOSESPIDER_ITEMCOUNT in scrapy.extensions.closespider.CloseSpider not working !

### ISSUE THREAD

**Issue by scila1996** [scrapy/scrapy#2748]
I'm want limit a number of item scraped . I Enabled success this extensions "scrapy.extensions.closespider.CloseSpider" And SETTINGS Like this

settings.py
`EXTENSIONS = {
    'scrapy.extensions.closespider.CloseSpider': 1
}`

my spiders
`custom_settings = {
        "CLOSESPIDER_ITEMCOUNT" : 1
    }`

but not working and and logging ...

> {'data': 'abc'}
2017-05-18 09:40:31 [scrapy.core.engine] INFO: Closing spider (closespider_itemcount)
2017-05-18 09:40:31 [scrapy.core.scraper] DEBUG: Scraped from <200 http://tinbatdongsan.com/>
{'data': 'abc'}
2017-05-18 09:40:31 [scrapy.core.scraper] DEBUG: Scraped from <200 http://tinbatdongsan.com/>
{'data': 'abc'}

Help me ! Thank you so much !

**Comment by kmike** [comment]
When CLOSERSPIDER_ITEMCOUNT limit is reached, Scrapy stops the spdier gracefully; it means requests which are currently in the downloader queue (up to CONCURRENT_REQUEST requests) are still processed. This is the expected behavior. But it is not documented at https://doc.scrapy.org/en/latest/topics/extensions.html#module-scrapy.extensions.closespider, so l think it is a documentation issue.

**Comment by scila1996** [comment]
@kmike :+1:  Thanh you ! i only set

`CONCURRENT_REQUEST = 1`

and it worked !

**Comment by redapple** [comment]
Moved to a documentation issue: https://github.com/scrapy/scrapy/issues/2759
