### ISSUE TITLE
Show warning if SPIDER_MODULES is not set

### ISSUE THREAD

**Issue by decentral1se** [scrapy/scrapy#2846]
Following from https://github.com/scrapinghub/shub/issues/293#issuecomment-317388127.

I'm trying to find the right place to show a warning for new users where they have not set the `SPIDER_MODULES` settings and cannot figure out how to run their spider (or get it registered on Scrapy Cloud).

For context, I wrote my spider from scratch without the `startproject` command.

**Comment by redapple** [comment]
This might be interesting to group with a fix for https://github.com/scrapy/scrapy/issues/2825

**Comment by kmike** [comment]
FTR, we shouldn't show a warning if spiders are started using CrawlerRunner or CrawlerProcess, as they don't require a project.

**Comment by lwm** [comment]
> if spiders are started using CrawlerRunner or CrawlerProcess

@kmike, how is this done? With the `runspider` command or?

**Comment by kmike** [comment]
@lwm CrawlerProcess is always used internally, I haven't worded it well. I mean that instead of `scrapy crawl` one can integrate Scrapy into Twisted event loop and start it manually (see https://doc.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script). 

A good point about `scrapy runspider`, we should handle it as well.
