### ISSUE TITLE
IOError: cannot identify image file <cStringIO.StringI object at 0x0000000005796E00>

### ISSUE THREAD

**Issue by MaGuiSen** [scrapy/scrapy#2850]
i got this problem when i use the ImagesPipeline to download some image（but some image can be download）...such as this image url:

http://mmbiz.qpic.cn/mmbiz_png/NmpHEAE5bXl1WYvWBOQBhDeB7Dar8JhIr4tHxouT9AbhZJO7wF1lv2bCUU1UX0YPtU70OUF7RRfnMQpubRJYpA/0?wx_fmt=png

this image can`t be download.

i think it is because the image type is JFIF，and the ImagesPipeline is not support .
i dont know how to Solve this problem, please help me

**Comment by redapple** [comment]
@MaGuiSen , can you share the whole traceback and a sample spider using the ImagesPipeline?
The payload seems to load fine for `PIL.Image`, and detected as JPEG

```
$ scrapy shell 'https://mmbiz.qpic.cn/mmbiz_png/NmpHEAE5bXl1WYvWBOQBhDeB7Dar8JhIr4tHxouT9AbhZJO7wF1lv2bCUU1UX0YPtU70OUF7RRfnMQpubRJYpA/0?wx_fmt=png'
2017-07-26 18:57:38 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: scrapybot)
(...)
2017-07-26 18:57:38 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://mmbiz.qpic.cn/mmbiz_png/NmpHEAE5bXl1WYvWBOQBhDeB7Dar8JhIr4tHxouT9AbhZJO7wF1lv2bCUU1UX0YPtU70OUF7RRfnMQpubRJYpA/0?wx_fmt=png> (referer: None)
(...)
In [1]: from PIL import Image
In [2]: from cStringIO import StringIO as BytesIO
In [3]: orig_image = Image.open(BytesIO(response.body))
In [4]: orig_image
Out[4]: <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=960x1280 at 0x7F0CA5D6F680>
```

**Comment by redapple** [comment]
@MaGuiSen , do you have any update for us?

**Comment by mr-huangyang** [comment]
i got the same problem too

**Comment by dydjiangtao** [comment]
I got this problem too...
![image](https://user-images.githubusercontent.com/25021313/30997922-91c23c0c-a4fd-11e7-8f83-791e7b07ae75.png)
![image](https://user-images.githubusercontent.com/25021313/30997964-cf55437a-a4fd-11e7-8f25-7d5bb83d2f59.png)

**Comment by gasbakid** [comment]
got the same, without any solution till now, i suspect the incopatibility of pillow lib. Any suggestion ?

**Comment by djunzu** [comment]
@mr-huangyang , @dydjiangtao , @gasbakid , as it was previously showed the problem could not be reproduced yet. There is no way to find the problem without more info. So... Are you using the default ImagesPipeline or a custom one? Can you share the image url? Traceback? Can you reproduce the problem with a minimal sample spider?

**Comment by ZhouYangL** [comment]
I got the   @redapple , @mr-huangyang , @MaGuiSen , @dydjiangtao , @gasbakid  please help me.
I used `scrapy shell url` , it not questio
`url='https://img.alicdn.com/bao/uploaded/i2/133560252265971710/TB2ZRMHsFXXXXXZXFXXXXXXXXXX_!!0-rate.jpg'
from PIL import Image
from cStringIO import StringIO as BytesIO
orig_image = Image.open(BytesIO(response.body))
`
but when I use selenuim and scrapy , I get the same question:
`from selenium.webdriver import Chrome
 from scrapy.http import HtmlResponse
browser = Chrome()
browser.get('https://img.alicdn.com/bao/uploaded/i2/133560252265971710/TB2ZRMHsFXXXXXZXFXXXXXXXXXX_!!0-rate.jpg')
r = HtmlResponse('https://img.alicdn.com/bao/uploaded/i2/133560252265971710/TB2ZRMHsFXXXXXZXFXXXXXXXXXX_!!0-rate.jpg', body=browser.page_source.encode('utf-8'), encoding='utf-8')
orig_image = Image.open(BytesIO(r.body))
`
then it have debugs 
orig_image = Image.open(BytesIO(r.body))

/usr/local/lib/python2.7/site-packages/PIL/Image.pyc in open(fp, mode)
   2570         fp.close()
   2571     raise IOError("cannot identify image file %r"
-> 2572                   % (filename if filename else fp))
   2573 
   2574 #

IOError: cannot identify image file <cStringIO.StringI object at 0x102d0ef10>

**Comment by cathalgarvey** [comment]
Hi folks, this is marked as "not reproducible", and it's a bit stale, so I'm inclined to close it. However, if anyone finds a clearly reproducible example, please come back to us and discuss/reopen.

Something quick to consider: If you want images and you don't need them resized/converted/thumbnailed, you can use the filespipeline to download them also. In fact, it should be faster and more efficient. This should be your first recourse if PIL/low - unsupported images become a problem.

Finally @ZhouYangL - I haven't attempted to replicate your shell session, especially as it uses an image that looks prone to changing, and it's been a few months. But I suspect your issue likes in the statement `browser.page_source.encode('utf-8')`, which is being called on what seems to be binary image content. I am guessing that you are using Python 2, because this kind of transform would be very unlikely to occur in Python 3? I suggest that the page contents are probably correct image binary as-is, and should not be encoded into a text-encoding such as UTF8.

Thanks everyone!
