### ISSUE TITLE
Feature suggest: add downloaded/uptodate status to information about downloaded media

### ISSUE THREAD

**Issue by djunzu** [scrapy/scrapy#2893]
Currently File/Image pipelines populate `files`/`images` fields with dicts containing information about the downloaded files (the downloaded path, the original scraped url, and the file checksum). It would be useful to have downloaded/uptodate status in this dict ([motivation](https://stackoverflow.com/questions/45823196/scrapy-how-to-get-status-of-file-download)).

It goes along with other features requests such as having width/height of images also in the dict output.

**Comment by redapple** [comment]
Makes sense.
Also, the format of the dicts is not clearly documented ([it is here](https://docs.scrapy.org/en/latest/topics/media-pipeline.html#scrapy.pipelines.files.FilesPipeline.get_media_requests), but not obvious).
If this proposal is implemented, I would also suggest improving the docs on the structure of results.

**Comment by dcurletti** [comment]
+1

**Comment by ilias-ant** [comment]
this is a great feature suggestion, that is general enough to have many applications on projects that utilize Scrapy!

Hope I find the time to have a try on this soon!

**Comment by Gallaecio** [comment]
I wonder if we want to make a distinction between:
- It had been already downloaded in a previous crawl.
- It had been already downloaded in the current crawl.

**Comment by ilias-ant** [comment]
I think the first approach (in a previous crawl) is sufficient and well-defined, at the right level of abstractness. 

The second approach is probably going to face significant definition challenges in Scrapy projects that utilize more than one Media Pipelines or heavily depend on a specific file expiration policy. Since the whole point of the file expiration policy is to "avoid downloading files that were downloaded recently", I think to take into account the "current crawl" semantics would really confuse the end-user.

Overall, maintaining consistency with the `file_status_count` statistics is definitely the way.

I hope I did not miss your point on this distinction :)
