### ISSUE TITLE
CONCURRENT_REQUESTS_PER_DOMAIN seem not work

### ISSUE THREAD

**Issue by treemore** [scrapy/scrapy#2920]
this is my scrapy file
```python
# -*- coding: utf-8 -*-
import scrapy


class Bug1Spider(scrapy.Spider):
    name = 'bug1'
    allowed_domains = ['google.com']
    start_urls = ['https://www.google.com/search?q=scrapy' for x in range(0, 20, 1)]

    def parse(self, response):
        self.log("*" * 100)
        pass
```

settings.py 
```python
DOWNLOAD_DELAY = 10
# The download delay setting will honor only one of:
CONCURRENT_REQUESTS_PER_DOMAIN = 20
# here AUTOTHROTTLE_ENABLED set True or False not affect the result
AUTOTHROTTLE_ENABLED = False
```
when i execute the shell below
```shell
scrapy crawl bug1
```
i notice that  the start_urls not CONCURRENT request.  
i set CONCURRENT_REQUESTS_PER_DOMAIN=20. i assume will fetch 20 request at the same time, but the console look like the request is fetch one by one . request one and than wait 10 seconds and start the next one. 
maybe  DOWNLOAD_DELAY>0 -> CONCURRENT_REQUES TS_PER_DOMAIN=1 ? 
just like https://stackoverflow.com/questions/37461327/scrapy-concurrent-requests-ignored-when-download-delay-set
but i can not find that in any document.

my scrapy version is  Version: 1.4.0
Twisted version is Version: 17.5.0

**Comment by kmike** [comment]
I'm not sure I understand the question, but if it is an issue with AutoThrottle, see https://doc.scrapy.org/en/latest/topics/autothrottle.html#topics-autothrottle: when AutoThrottle is enabled, DOWNLOAD_DELAY becomes a lower limit on download delay, and CONCURRENT_REQUESTS_PER_DOMAIN becomes an upper limit on concurrency; AutoThrottle adds its own limis. 

I'm closing this ticket, because it looks like a Scrapy usage question. We're using this issue tracker to track Scrapy bugs and enhancements; our support channels are https://www.reddit.com/r/scrapy/ and https://stackoverflow.com (use "Scrapy" tag.
