### ISSUE TITLE
Give `BaseDupeFilter` access to spider-object

### ISSUE THREAD

**Issue by Chratho** [scrapy/scrapy#2940]
I am in a situation where a single item gets defined over a sequence of multiple pages, passing values between the particular callbacks using the `meta`-dict. I believe this is a common approach among scrapy-users.

However, it feels like this approach is difficult to get right. With the default implementation of `RFPDupefilter`, my callback-chain is teared apart quite easy, as fingerprints don't take the meta-dict into account. The corresponding requests are thrown away, the information in the meta-dict which made this request unique is lost.

I have currently implemented by own meta-aware DupeFilter, but I am still facing the problem that it lacks access to the specific spider in use - and only the Spider really knows the meta-attributes that make a request unique. I could now take it a step further and implement my own scheduler, but I'm afraid that all these custom extensions make my code very brittle wrt future versions of scrapy.

**Comment by IAlwaysBeCoding** [comment]
I had a different problem that I needed to change the `RFPDupefilter` class because the HTTP cache didn't cache wasn't working the way I want it. I want it to cache every single `Request` so then I could do a replay of the same scrape using cache `Request` instances with their `Response` pair, and any new `Request` or `Response` instances that my scraper  might yield on the consecutive run to ignore completely.

Here is what you need to do:

1.  Change the dupefilter class inside your settings.py
  * DUPEFILTER_CLASS='yourown.dupefilters.RFPDupeFilter'
2. Subclass scrapy.dupefilters.RFPDupefilter class from yourown.dupefilters.RFPDupefilter
3. Replace  the `request_fingerprint()` method with your own inside yourown.dupefilters.RFPDupefilter. 
4. Optional you can modify a version of [https://github.com/scrapy/scrapy/blob/129421c7e31b89b9b0f9c5f7d8ae59e47df36091/scrapy/utils/request.py#L19](request_fingerprint) to your own function.

That is basically the gist, and I'm positive you can get a working version in 20-30 mins , perhaps a full 1 hour.

**Comment by Chratho** [comment]
As already mentioned, I have a custom Dupefilter with its own fingerprint mechanism up and running. My problem is that without also touching the scheduler and extending it, my fingerprint will never have access to the spider.

**Comment by IAlwaysBeCoding** [comment]
@Chratho I think your problem could be fixed really easily by changing a few lines. Look here inside the [_next_request_from_scheduler()](https://github.com/scrapy/scrapy/blob/master/scrapy/core/engine.py#L149) function, there is nothing that prevents it from passing the spider as a second argument. In fact, this function is only being called ONCE inside the whole Scrapy codebase. 

The change required to make this happen would be to allow `next_request()` from the `Scheduler` class to have a `Spider` instance passed as an argument.

@redapple would you be okay if I submit a PR for this.

**Comment by kmike** [comment]
Another way to solve the problem is to pass a list of meta keys which should be considered for uniqueness check; a custom dupefilter may look at this list and compute fingerprint.

If we're to make spider available to dupefilter we should add from_crawler support in addition to from_settings, this is how it is solved for all other Scrapy components.

**Comment by IAlwaysBeCoding** [comment]
@kmike I still believe there is no possibly reason why spider cannot be available to the Scheduler. If you check my post above, it will be a very small change and it will satisfy the @Chratho request.

**Comment by kmike** [comment]
@IAlwaysBeCoding I'm not sure I follow, sorry! Spider is available to Scheduler in from_crawler method which is called when Scheduler is created; a Scheduler subclass can store spider as an attribute. But this doesn't solve @Chratho's problem, as he heeds spider in dupefilter, not necessarily in Scheduler.

Adding 'scheduler' argument to next_request is a backwards incompatible and could break existing custom schedulers. It also doesn't provide any new features, as this argument is unused by default, and a Scheduler subclass can already access spider by overriding from_crawler method (as a bonus point, access is not limited to next_request method if spider is saved in from_crawler method).

**Comment by IAlwaysBeCoding** [comment]
@kmike, I see I made an error. The spider is in fact available to the `Scheduler` class through the `from_crawler` class method. It is on the `crawler.spider` attribute. You are right sorry, about that.

Also, I guess that would give backwards incompatibility. Never mind, I guess the correct answer for @Chratho would be to grabbed the spider instance from `crawler.spider` when is passed to the `from_crawler` class method.

@kmike thanks for the clarification. You are 100% right!

**Comment by Chratho** [comment]
Sorry for the delay. 

Yes, the solution suggested by @kmike would definitely solve my problem. As it also seems like a natural fit to the design of scrapy I would love to see its implementation in an upcoming release.
