### ISSUE TITLE
Scrapy ImagePipeline ignore images from specific host

### ISSUE THREAD

**Issue by marcuslind90** [scrapy/scrapy#2943]
I have an issue where my crawler is ignoring images from a specific host. It does not download any images and it does not throw any error or log messages. If I replace the image path with any other image path from any other source, it works fine with exactly the same config and code.

I put up a public repo here that reproduce it:
https://github.com/marcuslind90/scrapy_error

As you can see in the `example` spider, I hardcode 2 paths like this:

```
loader.add_value('image_urls', ['https://media.fastighetsbyran.se/22943836.jpg', 'http://hemmon.com/house.jpg'])
```

The first image is ignored (and any other images on that host) while the second image is downloaded.

Anyone recognize this issue? Could it have something to do with headers? Also, I believe that the host is programmatically generating the images because you can append a `?Bredd=<pixels>` parameter that will automatically resize the picture. Perhaps this could be part of it as well.

**Comment by IAlwaysBeCoding** [comment]
> Could it have something to do with headers?

Short answer: YES!

Long answer:
At the moment the ImagePipeline doesn't really tell you of any errors that happened on its pipeline which I think it should.

It only returns 2 fields: `image_urls`, and `images` but the `images` field will only get populated with ONLY  the ok requests that made it through.As you saw, any requests that didn't make it through will not be shown or downloaded. Any other errors will be swallowed and will be left up to the user to find out what happened.

This is a quick hack I did to find out what was wrong, you will have to edit 1 of your Scrapy core files(find where they are on stackoverflow):

Add this line underneath this [line](https://github.com/scrapy/scrapy/pipelines/files.py#L394):
```python
items['results'] = results
```
 
Add a new scrapy.Field() name to your `ScrapyerrorItem`

```python
results = scrapy.Field()
```

When you run it  you will see  is in a new field named 'results' that it is giving you  `twisted.python.failure.Failure scrapy.pipelines.files.FileException` exceptions.

The reason is simple, the host you are trying to scrape knows that you are scraping it via  scraper/script/scrapy. It is giving you an error so you can't scrape images from that host.
Last year someone had the same problem and opened an [issue](https://github.com/scrapy/scrapy/issues/2371).

What you want to do is to make your Requests look exactly as a normal browser. This means first thing first set a custom user agent, do not use Scrapy default user agent.

I have no idea why the hell would a scraping framework would announce it self as a scraper because no site on earth likes to get scraped. Anyways, not sure what they were thinking, but on every single project I code with Scrapy I always make sure to change the default UserAgent. If not, then about 5-10% of the sites blocked me on the first request.

**Comment by marcuslind90** [comment]
My issue was that the media.* subdomain and the www.* subdomain of the website I was crawling had different robots.txt files, so even though I could crawl the page itself, I couldn't crawl the images. It was nothing wrong with Scrapy.

**Comment by IAlwaysBeCoding** [comment]
@marcuslind90  I'm glad that you have figured out your problem. Also, if you check out the [issue](https://github.com/scrapy/scrapy/issues/2371) I pointed out in my previous reply. The @geemaple figured out that robots.txt file at imgs.bipush.com prohibit every scraper that respects the robots.txt from scraping the site.

Put this on your settings.py
`ROBOTSTXT_OBEYROBOTSTXT_OBEY=False`

This will make scrapy ignore robots.txt files and scrape through them. That should fix your problem that you have.
