### ISSUE TITLE
How to clear all data which come from website and reset spider?

### ISSUE THREAD

**Issue by kingname** [scrapy/scrapy#2980]
I am crawling 100 urls in scrapy. I have found that if I `start scrapy` - `crawl 1 url` - `kill scrapy`, then I can crawl every url in a short time. However, if I crawl all the 100 url in the same scrapy process, then the website will find me and refuse me. 

Therefore, the website must write some datas to my spider, so the latter request will fail. Is there some method to `reset the status of spider` just like restart the scrapy process?  So that I can reset the status of spider as soon as I finish crawling every url.

**Comment by pau1a** [comment]
Isn't this just an example of the website detecting your requests as arriving too fast and blocking you as it treats you like an attacker?

Have you tried coding in a time gap between requests?

**Comment by djunzu** [comment]
@kingname , you are more or less right in thinking the website writes some data about you and blocks you. You are wrong thinking the website writes it to your spider: that is virtually impossible. (It is possible if the website set a tracking cookie. In this case, setting [COOKIES_ENABLED](https://doc.scrapy.org/en/1.4/topics/downloader-middleware.html?highlight=cookie#cookies-enabled) to false in your project settings solves the problem.) Usually websites writes data about users internally, in the server itself. The files containing this data are called "requests log" or something like that!

If a website is banning you, you should first read [this doc](https://doc.scrapy.org/en/1.4/topics/practices.html#avoiding-getting-banned). And if you have any questions about "how to" or "why" you should ask the [scrapy community](https://scrapy.org/community/) outside github: try StackOverflow or reddit or IRC.

Github issue tracker is used only to track bugs and feature requests, not to answer "how to" / "why" questions.

**Comment by kingname** [comment]
@djunzu I am sorry to post question in the wrong place. However, this is the feature I request, I hope there is an interface to clear the state of spider . And by the way, I have used proxy middleware and UA middleware to change proxy and UA at every request.

**Comment by djunzu** [comment]
@kingname , no need to be sorry. We are always learning something and adapting our self to each community.

Back to your problem, I think your understanding about request/response cycle and scrapy itself is quite wrong. The web was built to be [stateless](https://en.wikipedia.org/wiki/Stateless_protocol). Most websites work with http and [http is stateless](https://stackoverflow.com/questions/13200152/why-say-that-http-is-a-stateless-protocol). And [http2 is stateless](https://stackoverflow.com/questions/36178447/is-http-2-a-stateless-protocol). As a workaround websites use cookies to allow them to maintain some kind of state between requests. So, if you disable cookies in your spider, there is absolutely no state between your requests. So, how would it be possible to clear all data which come from website and reset a spider if there is no such data in the first place??

There is no way to implement the feature you request simply because there is no state to clear.

But you are being blocked even though web is stateless... There are numerous techniques to analyze request log files and identify single users. In every request you may (and usually you do!) send a lot of information to the server in the form of a [header request](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields). If you are changing your UA and your IP in every request, the server is probably identifying you using other information. There are thousands ways to do it. (Did you disable cookies!?)

The problem you have in hands has nothing to do with scrapy itself. Scrapy is just a tool you use to make requests in the same way the browser is just a tool you use to make requests (and see content). A server/website can block you regarding the fact you are using scrapy or a browser. 

Scrapy itself may have a bug that is messing with you? Yes. But if so, you have to first identify this bug so someone can fix it.

But again, you have a better chance of solving your problem going to SO. Or searching about how server identify/block users and how to avoid it.

**Comment by kingname** [comment]
Thanks for your replay.
