### ISSUE TITLE
trying to make a files and youtube downloader

### ISSUE THREAD

**Issue by monikarazdan** [scrapy/scrapy#3008]
hello, I'm new to python and trying to make files and youtube downloader but while making that I have a problem with setting the youtube URL by the user at runtime(plz someone kindly correct me where I'm wrong)

```
from __future__ import unicode_literals
import youtube_dl
from youtube_dl import YoutubeDL
import urllib
import shutil
import os 


u_input=int(input("enter url:"))
ydl_opts = {}
url=(u_input)
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(url)
    info_dict=ydl.extract_info(url[0], download=False)
    video_title = info_dict.get('title', None)
    print(video_title)
print("DONE!")
script_dir = os.path.dirname(os.path.realpath(__file__))
print(script_dir+"\\" +video_title)](url)
```

**Comment by rmnd551** [comment]
Hi! I see you forgot to indent the variable declaration right after the `with` statement at line #12.
The code should be as follows:
`with youtube_dl.YoutubeDL(ydl_opts) as ydl:`
`.  ydl.download(url)` < Remove the period, I added it so that you could see the space.

Also, you forgot to escape the `\` when you called the `print` function, and you have an orphan bracket.

Modify it so it looks this way:
`print([script_dir + "\\" + video_title](url))`

Alternatively, you could just change the backlash to a normal slash and it should still work with the URLs.
`print([script_dir + "/" + video_title](url))`

The script won't work, though, and that is because of the line where you get the input.
`u_input=int(input("enter url:"))`
Why are you trying to transform the string into an integer?

**Comment by kmike** [comment]
Hey! This doesn't look like a Scrapy issue. For general scraping questions there are better places like https://stackoverflow.com.
