### ISSUE TITLE
HTTPERROR_ALLOWED_CODES can't parse response with 301

### ISSUE THREAD

**Issue by kmagonski** [scrapy/scrapy#3060]
In scrapy.downloadermiddlewares.redirect.RedirectMiddleware#process_response 
dosn't get anything from settings like HTTPERROR_ALLOWED_CODES only in HttpErrorMiddleware we have 
handle_httpstatus_list.

**Comment by cathalgarvey** [comment]
Hi @kmagonski - Could you provide more information on when this becomes a problem? Strictly speaking, a 301 isn't an error, it's a cleanly resolvable navigation cue. Some sites do use 301 to redirect somewhere instead of 404, when they don't have a page for the requested URL.. but that's not how the code is meant to be used.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback from the author.
