### ISSUE TITLE
Why using popen can't start spider

### ISSUE THREAD

**Issue by linglaiyao1314** [scrapy/scrapy#3071]
I need using subprocess.Popen to start spider , but can't work.
if I type the command in shell: 
>nohup scrapy crawl helloworld --logfile log.txt &

it workers well.  
But if I using subprocess:
`command = ["nohup", "scrapy", "crawl", "helloworld", "--logfile", "log.log", "&"]
 subprocess.Popen(command)
`
it can't work , and output:
`   
scrapy crawl [options] <spider>
crawl: error: running 'scrapy crawl' with more than one spider is no longer supported
`
so, how can I slove this problem?

**Comment by pohzipohzi** [comment]
Scrapy is treating `&` as a second spider. The reason for that is because `&` gets passed in as a separate argument in `subprocess.Popen`.

You probably want to remove `&` from the command list (ie `command = ["nohup", "scrapy", "crawl", "helloworld", "--logfile", "log.log"] `). Also see [this](https://stackoverflow.com/questions/1196074/how-to-start-a-background-process-in-python)

**Comment by linglaiyao1314** [comment]
@pohzipohzi Thank you， it slove my problem~
