### ISSUE TITLE
scrapy selector fails when large lines are present response

### ISSUE THREAD

**Issue by shanmuga-cv** [scrapy/scrapy#3077]
Originally encoutered when scraping [Amazon restaurant](https://www.amazon.com/restaurants/zzzuszimbos0015gammaloc1name-new-york/d/B01HH7CS44?ref_=amzrst_pnr_cp_b_B01HH7CS44_438).  
This page contains multiple script tag with lines greater then 64,000 character in one line. 
The selector (xpath and css) does not search beyond these lines. 

Due to this the following xpath `'//h1[contains(@class, "hw-dp-restaurant-name")]/text()'` to extract name of the restaurant returns empty even though there is a matching tag is present.

PFA the response text at [original_response.html.txt.gz](https://github.com/scrapy/scrapy/files/1631425/original_response.html.txt.gz)

**Comment by cathalgarvey** [comment]
Hey @shanmuga-cv - Thanks for reporting this and thanks for providing a sample response to work with!

**Comment by shanmuga-cv** [comment]
Happy to help. 
I would like to help in fixing this. Can you point me which file or module should I look into for fixing this?

**Comment by ayushmankoul** [comment]
Hey, @cathalgarvey  I would also like to give a try to fix this bug. Please help me to fix this bug and how should I proceed.

**Comment by ayushmankoul** [comment]
Hey @shanmuga-cv @cathalgarvey I gave a try for this bug what I observed scrapy takes more time to crawl the given page when compared to other pages on the same website.To improve the efficiency we can use  html5lib library, a far superior HTML parser (IMHO) since conforming to the WHATWG HTML specification is one of its explicit goals, and that increases our chances of Python seeing the same HTML tree as does our browser.I guess we can then ask the normal HtmlResponse given to us by Scrapy to feed that to html5lib, then run selectors to fish out the elements that matter.I have given a thought about it please guide me how can I fix this bug more efficiently

**Comment by mdaniel** [comment]
Hey @ayushmankoul it is considered impolite to [plagiarize content](https://www.reddit.com/r/scrapy/comments/81f13r/how_to_scrape_page_which_contains_multiple_script/dv4zbl9/), even in GitHub issues. Separately, as one can see in the referenced issues, this is actually an lxml bug, which manifests in parsel, which then manifests in Scrapy. So I wouldn't expect any action except encouraging lxml to make a bugfix release.

**Comment by cathalgarvey** [comment]
Hi @mdaniel - Thank you for your work on the related issues, and for providing potential test cases for the fix! And, thanks for the clarity that this is an upstream issue, I'll label it accordingly.

In any case @ayushmankoul, I'm not sure that I understand whether your suggestion was to "Change Parsel to use `html5ever`", or "Work-around the bug using `html5ever` until LXML fix it"? I think the second option makes more sense for us, right now. Changing our underlying parser isn't going to happen for the sake of fixing rare cases like this.

**Comment by mzmmoazam** [comment]
Hi, I was working with a huge html file [Kashmirizaban.html.zip](https://github.com/scrapy/scrapy/files/4979891/Kashmirizaban.html.zip)

I was trying to extract using this selector `response.xpath('//table[@width="717"]')` but it did not fetch all the tables. I tested the xpath on chrome it gave more results than above. 

I am not sure if this is due to the above bug or is there a solution for this?

Thank you

**Comment by wRAR** [comment]
Fixed in https://github.com/scrapy/parsel/pull/116, both provided test cases work correctly with the current Scrapy/parsel.
