### ISSUE TITLE
Possible bug in response.xpath() 

### ISSUE THREAD

**Issue by mohdhashimpa** [scrapy/scrapy#3102]
There was an issue in parsing "title" from the HTML file attached.
[test.txt](https://github.com/scrapy/scrapy/files/1681839/test.txt)

Sample HTML : 
```
<html>
   <head>
      <div></div>
      <title>Gas safety - 10 tips that could save your life</title>
   </head>
   <body>
   </body>
</html>
```

`response.xpath('/html/head/title/text()').extract()` 
The above was returing empty array.

But title was successfully parsed from the following expression
`response.xpath('//title/text()').extract()`

I have reproduced this issue in lxml using the following code.

```
from lxml import etree
with open('./test.txt', 'r') as test_html:
  file_contents = test_html.read()
  tree = etree.HTML(file_contents)
  print('via head specified xpath expression : ',tree.xpath('/html/head/title/text()'))
  print('via take every title xpath expression : ',tree.xpath('//title/text()'))
```

Seems the issue is caused by the div tag.
If that tag is removed, it works properly.

**Comment by kmike** [comment]
I think the problem is that `<div>` tag is not allowed in head, and lxml's html parser normalizes html so that there is no div tag there:
```
In [28]: html = """
    ...: <html>
    ...:    <head>
    ...:       <div></div>
    ...:       <title>Gas safety - 10 tips that could save your life</title>
    ...:    </head>
    ...:    <body>
    ...:    </body>
    ...: </html>"""
In [29]: sel = Selector(html)
In [30]: from lxml.etree import tostring
In [31]: print(tostring(sel.root, encoding='unicode'))
<html>
   <head>
      </head><body><div/>
      <title>Gas safety - 10 tips that could save your life</title>



</body></html>
```

Browsers do something very similar. If you save your test.txt file to disk, rename it to test.html, open in Firefox, then open Inspector and check DOM tree, you'll get this:

```html
<html><head>
      </head><body><div></div>
      <title>Gas safety - 10 tips that could save your life</title>
   
   
   
</body></html>
```

So lxml's html parser does the same as a browser, it doesn't look like a bug.

If you want, you can parse it as XML - in this case tree stays as-is:

```
In [32]: sel = Selector(html, type='xml')
In [33]: sel.xpath('/html/head/title/text()').extract()
Out[33]: ['Gas safety - 10 tips that could save your life']
```

So instead of using `response.xpath` shortcut you can use `scrapy.Selector(response.text, type='xml').xpath` if you want this xpath to work. 

Overall it doesn't look like a bug to me, more like a gotcha: in this case selectors work the same way as in browsers.

**Comment by mohdhashimpa** [comment]
@kmike Can you open this URL in a browser?
https://www.uswitch.com/boilers/guides/gas-safety/

Browsers are able to parse the title correctly. But we cannot.
You can also test the above code using this HTML.

**Comment by mohdhashimpa** [comment]
@kmike How can we update Scrapy's Response object's xpath selector with `Selector(html, type='xml')`

**Comment by mohdhashimpa** [comment]
@kmike Any update here? Thanks.
