### ISSUE TITLE
can't crawl all url

### ISSUE THREAD

**Issue by Linoonphan** [scrapy/scrapy#3107]
Scrapy crawl the page is not complete, in the rules of the write can only crawl part of the url, but can not crawl all, the same rules to crawl a page alone can successfully crawl, I do not know what the problem.

**Comment by kmike** [comment]
Hey @Linoonphan,

I'm not sure what the problem is, but it looks more like a Scrapy usage question, not a concrete bug report. We usually suggest using https://stackoverflow.com (use tag "scrapy") to get help with such issues. It is a good idea to provide more details when creating a stackoverflow question; currently is impossible to debug and reproduce based on the problem description.
