### ISSUE TITLE
Discussion regarding gsoc

### ISSUE THREAD

**Issue by yashrsharma44** [scrapy/scrapy#3136]
Hello, I opened this issue, regarding some discussions of unittests. I am planning to participate in Gsoc , and while I am going through the code base, I am getting hang of most of the code, except unittests. This is  not something that there are issues with the codebase ; my main issue is that **testing for asynchronous programming** is something new for me, so I wanted some advices : 1. How to go about learning unittests ? 2. How do I apply my learning in writing code so that it is utilised with unittests ? 3. While applying Test Driven Development( which is quite new for me), how do I go about bringing new features, if I need to rewrite the previous tests and test-suites from scratch ?
EDIT : I am planning for the Asyncio Project of GSoC, so if specific comments for this project are there, you are most welcome.

**Comment by cathalgarvey** [comment]
Hi @yashrsharma44 - We don't follow TDD in the Scrapy project, but we do require extensive test coverage. In other words, you do not need to write the tests _first_, though you should write tests for any contributions you make.

One advantage of TDD is that it forces you to think about, up-front, what your code should do exactly, before you write it. This can help with good design. So you're welcome to follow TDD in your own work and contributions.

Another good thing about tests; it prevents issues from re-surfacing later on. Say you find a bug that can be fixed by moving a statements up a few lines within a function. That's a simple change, easy to do in seconds. But it's also easy for someone to undo it later, without meaning to. By adding a new test case for the original problem, you make sure that something breaks later if anyone un-fixes the problem. Test cases shape and define software! In a way, they are the "mold" for how the software should behave. :)

As to "how to learn".. By all means, read through Python's built-in unit tests. Then look at PyTest, and then look at Tox. Don't try to learn them all 100%, just get an overview. Then, look at Scrapy's tests and try to figure out how they work, knowing what you now know. Try writing some new tests and see if they work. Try breaking or changing some old ones.

Tests are hard. But they're worth learning, you won't regret it. :)

BTW, I'll close this, as it's just for discussion. But keep discussing here if you like! I'm just trying to bring down our open-issue count. ;)

**Comment by yashrsharma44** [comment]
Thanks for your words :) . BTW if I want to discuss, can we discuss the topics in reddit?
