### ISSUE TITLE
FormRequest.from_response() clickdata ignores input[type=image]

### ISSUE THREAD

**Issue by Nadya24** [scrapy/scrapy#3139]
No way to click image inputs now, see [here](https://github.com/scrapy/scrapy/blob/73668ce4076b87d2d2493f2c9b445c643da9055a/scrapy/http/request/form.py#L165).

**Comment by cathalgarvey** [comment]
Hi @Nadya24, thanks for the report!

When I first read this, I thought `input[type=image]` was for uploading images, so it's a good thing I searched it to [make sure](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/image). So, it looks like this element is generally used for clickable submit buttons, so it should be supported here.

Is this something you're interested in [contributing a PR](https://scrapy.readthedocs.io/en/latest/contributing.html) for?

**Comment by virmht** [comment]
@cathalgarvey , I want to write a fix for this bug. May I submit a PR for the same ?

**Comment by gekco** [comment]
has this been assigned yet? I want to work on this issue.

**Comment by cathalgarvey** [comment]
@virmht - It doesn't look like you've made any commits towards this issue yet, right? Glancing at your fork, by the way, here's a tip: Make a branch for any edits you make. That allows you to push the branch to your repository, and make a pull-request from the branch, instead of your master. That way, you can make more than one PR at a time, without getting them confused.

Also, PRs are always welcome. Propose fixes here, and work on them if there are no objections. If ye feel like working together, see [this documentation on how](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/). The short version is, one of you starts the fork/branch/PR, and give the other push access.

I'd suggest, though, that @virmht has precedence here, as he suggested a fix first. What do you think?

**Comment by virmht** [comment]
@cathalgarvey, I have made some commits, but haven't pushed them on GitHub. Just like you said, I have made a different branch which enabled me to raise 2 PR's simultaneously. Its

**Comment by lopuhin** [comment]
Fixed in #3153, thanks @virmht !
