### ISSUE TITLE
GSOC 2018:Want to contribute to Scrapy in GSOC 2018

### ISSUE THREAD

**Issue by ayushmankoul** [scrapy/scrapy#3156]
Hello Mentors and Developers,

I am Ayushman Koul, a student at GCET Jammu.I went through the Scrapy GSoC 2018 ideas page and found all the projects to be very interesting and want to contribute to Scrapy performance improvement and Scrapy spider auto repair projects.I've used scrapy for my personal projects, which is why I'd love to have an opportunity to contribute meaningfully this summer!
You can know more about me on:
Linkedin: https://www.linkedin.com/in/ayushman-koul-a70350128/
GitHub: https://github.com/ayushmankoul

I have started on picking up an issue and familiarizing myself with the codebase.Please help me how can I fix this bug (https://github.com/scrapy/scrapy/issues/3077) and also have given my feedback on comments.@cathalgarvey, I would really appreciate any guidance on fixing this bug (https://github.com/scrapy/scrapy/issues/3077) and I would like to try my hand more by implementing a small new feature and/or resolving bugs.
If there is anything else that might be useful to know while I'm researching this project please let me know!
Thanking you.

Regards,
Ayushman Koul

**Comment by cathalgarvey** [comment]
Hi @ayushmankoul - I responded in #3077, I don't know if you saw that yet. In any case, as you can see, that issue is possibly not Scrapy's to solve, and work is underway to work-around it, anyway.

Whether as part of GSoC, or not, we appreciate contributions from anyone who's interested. So, do go ahead and get familiar with the Scrapy code-base, and see if there are areas you feel comfortable contributing to. To explain how contributions to Scrapy relate to our GSoC process, we put together a [participation page](http://gsoc2018.scrapinghub.com/participate/) on our landing-site, I recommend reading more there.

Happy coding!
