### ISSUE TITLE
Option to log error instead of info when a non-200 response is ignored

### ISSUE THREAD

**Issue by ariasuni** [scrapy/scrapy#3172]
Currently, when scrapy encounter a 404, it ignore the request and log an info. But I want to know right away if my spider has an error — because most of the time, it’s an error in my code. Instead, it’s drown with other debug messages.

**Comment by kmike** [comment]
There are several ways to implement it: you can have an errback and handle error as you want, you can change a list of HTTP status codes callback should handle, you can make an extension which closes spider in case of 404 errors, you can use CLOSESPIDER_ERRORCOUNT option to stop spider if it produces errors.

Web is unreliable, and Scrapy should account for that. Logging errors instead of stopping a crawl is a design decision which is very unlikely to be changed, so I'm closing this issue.

**Comment by ariasuni** [comment]
I just want to change the log level of

https://github.com/scrapy/scrapy/blob/6cc6bbb5fc5c102271829a554772effb0444023c/scrapy/spidermiddlewares/httperror.py#L53

Anyway I’ll probably just make a subclass that overrides `process_spider_exception` since it is such a small function.

**Comment by kmike** [comment]
Aha, it seems I misunderstood the question, sorry! 

But anyways, for me INFO log level makes sense as a default here: Scrapy follows user configuration and ignores some HTTP status codes, this is not an error. It is possible to override verbosity for this logger using features of stdlib `logging` module, or, as you said, by making a subclass.
