### ISSUE TITLE
 scrapy check Unhandled error in Deferred: with DOWNLOADER_MIDDLEWARES

### ISSUE THREAD

**Issue by aleroot** [scrapy/scrapy#3222]
When I have some downloadmiddlewares and I ran `scrapy check` I got the error:

Unhandled error in Deferred:

the only way to solve is to comment out the DOWNLOADER_MIDDLEWARES section inside settings.py !

I usually have these downloader middlewares : 

```
DOWNLOADER_MIDDLEWARES = {
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': 90,
    'scrapy_proxies.RandomProxy': 100,
    'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': 110,
}
```

I was able to workaround the issue running scrapy check with the following commnad line args: 

`scrapy check  -s DOWNLOADER_MIDDLEWARES={}`

**Comment by grammy-jiang** [comment]
Hi, @aleroot 

It is really hard to answer your question with no more further details.

I have met this error many times, but it's very difficult to find what is wrong and where it is.

But I still can provide some my experience here:

- try to comment the downloader middleware one by one, to make sure which one cause this error
- go to the source code of the downloader middleware, read it, try to comment them and re-run

It sounds like a stupid debugging way. Yes, it is not decent, far away from that, because I think Twisted is an asynchronize framework, some errors/warnings will only happen in some certain cases/sequences of code executing. So maybe traditional debugging is not very suitable for Twisted.

**Comment by aleroot** [comment]
This was not a question but a bug reported, as I've written in the original Ticket I've fixed running the check overriding the `DOWNLOADER_MIDDLEWARES` setting, but this still remain a bug that should be fixed.

**Comment by wRAR** [comment]
@aleroot still, this doesn't look like a good bug report without additional details.

**Comment by Gallaecio** [comment]
@aleroot Any chance you can provide some minimal code to reproduce it, à la https://stackoverflow.com/help/mcve?
