### ISSUE TITLE
'SelectorList' object has no attribute 'get'

### ISSUE THREAD

**Issue by mouday** [scrapy/scrapy#3228]
i can use this code in local, but! move other computer show some error

```python
link = classify.xpath("@href").get()

```

error

`
AttributeError: 'SelectorList' object has no attribute 'get'
`

use version Scrapy 1.1.2  == Scrapy 1.1.2 

and i read scrapy source code 
```python
    def extract(self):
        """
        Call the ``.extract()`` method for each element is this list and return
        their results flattened, as a list of unicode strings.
        """
        return [x.extract() for x in self]
    getall = extract

    def extract_first(self, default=None):
        """
        Return the result of ``.extract()`` for the first element in this list.
        If the list is empty, return the default value.
        """
        for x in self:
            return x.extract()
        else:
            return default
    get = extract_first

```

**Comment by kmike** [comment]
@mouday this is not Scrapy source code, it is parsel source code (https://github.com/scrapy/parsel). I think you can get it working by upgrading parsel library. 

By the way, at the time of 1.1.2 Scrapy release there were no .get/.getall shortcuts; it is possible to use them with this Scrapy version because parsel library was extracted to a separate package which you can upgrade separately.
