### ISSUE TITLE
about setting depth

### ISSUE THREAD

**Issue by MichaelEvil** [scrapy/scrapy#3285]
Is the depth information written in `response.meta['depth']`?

I set DEPTH_LIMIT to 5, and it works. Now I want to make specific Requests ignore this limit(for example, requests about turning page)，so I try it in this way(assuming this response depth is 4):
`yield scrapy.Request(url=“next_page_url”, 
                               headers=self.headers, 
                                 callback=self.parse,
                                 meta={'depth' : response.meta['depth']-1})`
but it doesn't work, and this request would be ignored by scrapy engine normally.

Is there any way to realize my idea? Or is it necessary to use a overwritten depthmidderware? thanks.

**Comment by VMRuiz** [comment]
Hello,

The 'depth' value in the new Request is overrided by the `DepthMiddleware` (https://github.com/scrapy/scrapy/blob/master/scrapy/spidermiddlewares/depth.py#L34) base on the previous `Response.meta['depth']` value.

You can do one of this things:

1. Easy but ugly, changing the  `depth` value in the response:
```
   response.meta['depth'] = response.meta['depth'] - 1
   yield scrapy.Request(url=“next_page_url”, headers=self.headers, callback=self.parse)
```

2. Best Solution, extends the DepthMiddleware to use setdefault instead of always override depth value:

```             
   request.meta.setdefault('depth', depth)
```

**Comment by Gallaecio** [comment]
Related to #891

**Comment by Gallaecio** [comment]
Closing in favor of https://github.com/scrapy/scrapy/issues/891, it’s really the same thing.
