### ISSUE TITLE
Use pipfile instead of requirements Files

### ISSUE THREAD

**Issue by Urahara** [scrapy/scrapy#3312]
I think this will be a great enhancement to the project, one of the main advantages:

- Enables truly deterministic builds, while easily specifying only what you want.

[Pipenv: Python Dev Workflow for Humans](https://docs.pipenv.org/)

**Comment by Papa-Shell** [comment]
Thanks, I appreciate it. I really had no idea what I was doing but I just had an AAAAHHHHHH!!!!!! Moment. Serious noob here… bare with me!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by kmike** [comment]
@Urahara I'm not sure what would be an exact advantage of using Pipfile for Scrapy. Would you mind elaborating on this?

> Enables truly deterministic builds, while easily specifying only what you want.

requirements files are used for Scrapy tests, and we *don't* want deterministic builds there in many cases, we want to use latest library versions and detect failures, instead of testing with older known-to-work versions.
