### ISSUE TITLE
Local Relative URLs work in SHELL but don't work in scrapper

### ISSUE THREAD

**Issue by tarunteckedge** [scrapy/scrapy#3444]
This may relate to #1550 which is closed now, but it still doesn't work in the scrapper.
Please guide further on the same.

Thanks

**Comment by wRAR** [comment]
@tarunteckedge sorry, what's your problem?

**Comment by kmike** [comment]
@tarunteckedge this is by design - otherwise it'd be possible for remote websites to trigger loading local relative files. If you want to make them work the same way in a spider, use [scrapy.util.guess_scheme](https://github.com/scrapy/scrapy/blob/bafd174a9f174e31bd76493761264f4c81649e4a/scrapy/utils/url.py#L87) function to convert an url.
