### ISSUE TITLE
Crawler not returning the result in python django

### ISSUE THREAD

**Issue by adeel3612** [scrapy/scrapy#3467]
Hello i am using this library to create an api in django which return me the result. 

This is my code. 

```
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import scrapy
from scrapy.crawler import CrawlerProcess,CrawlerRunner
import json

@csrf_exempt
def some_view(request, username):
    process = CrawlerRunner({
        'USER_AGENT': 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)',
        'LOG_ENABLED': 'false'
    })
    process_test = process.crawl(QuotesSpider)

    return JsonResponse({'return': process_test})


class QuotesSpider(scrapy.Spider):
    name = "quotes"

    def start_requests(self):
        urls = [
            'http://quotes.toscrape.com/random',
        ]
        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        return json.dumps(response.css('.text::text').extract_first())
```
first i was using `CrawlerProcess` but that was giving me the error of main thread so i user `CrawlerRunner` and now error is `is not JSON serializable`. Any body can help me in this regard i try to read the documentation but no success.

**Comment by elacuesta** [comment]
```
# quotes.py
import json
from scrapy import Spider
from scrapy.crawler import CrawlerRunner

class QuotesSpider(Spider):
    name = 'quotes'
    start_urls = ['http://quotes.toscrape.com/random']

    def parse(self, response):
        return dict(quote=response.css('.text::text').extract_first())

if __name__ == '__main__':
    process = CrawlerRunner()
    process_test = process.crawl(QuotesSpider)
    print(type(process_test))
    print(json.dumps(process_test))  # this will fail
```

```
$ python quotes.py
<class 'twisted.internet.defer.Deferred'>
Traceback (most recent call last):
  File "quotes.py", line 16, in <module>
    print(json.dumps(process_test))  # this will fail
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Deferred' is not JSON serializable
```

First, if you return the result of `json.dumps` from the spider callback you will get `ERROR: Spider must return Request, BaseItem, dict or None, got 'str' in <GET http://quotes.toscrape.com/random>`, you should return a Scrapy Item or a dict instead.

The `is not JSON serializable` message is because what you get from the `process.crawl` operation is not the items from the spider but a `twisted.internet.defer.Deferred` object, which is indeed not JSON serializable. To get the items you could use something like [this stackoverflow answer](https://stackoverflow.com/a/41430245), which connects to the [`item_scraped` Scrapy signal](https://doc.scrapy.org/en/latest/topics/signals.html#item-scraped) to store scraped items. (Disclaimer: I wrote that answer, and I didn't actually tried the integration with Django)

Finally, I believe this kind of questions should go to other support channels like the [Scrapy tag at stackoverflow](https://stackoverflow.com/questions/tagged/scrapy), the Github issues system is more for bug reports or feature requests.

Happy scraping!

**Comment by xiantang** [comment]
if you want schedule your scrapy script. i think you can refer  this code:

```python
from scrapy import Request
from scrapy import Spider
from scrapy.crawler import CrawlerRunner
from twisted.internet import reactor
class QuotesSpider(Spider):
    name = 'quotes'
    start_urls = ['http://quotes.toscrape.com/random']
    def start_requests(self):
        for i in self.start_urls:
            yield Request(i,callback=self.parse1)
    def parse1(self, response):
        print(response.text)


if __name__ == '__main__':
    process = CrawlerRunner()
    d=process.crawl(QuotesSpider)
    d.addBoth(lambda _: reactor.stop())
    reactor.run()
```

**Comment by adeel3612** [comment]
@elacuesta can you please guide me how to solve this i tried your solution but no success. May be django is not allowing this. and if i used the `CrawlerProcess` it gives me the error of thread to be run in main thread.

**Comment by adeel3612** [comment]
@xiantang can this code be run into the function like i am running in `some_view` ?

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
