### ISSUE TITLE
can not install pyndri

### ISSUE THREAD

**Issue by ZahraGithub** [scrapy/scrapy#3541]
Hi,
I try to install pyndri using command: pip install pyndri but I received this error:
 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
What should I do?
Regards

**Comment by Gallaecio** [comment]
I think you may have gotten the wrong Github project. This is scrapy, not https://github.com/cvangysel/pyndri

In any case, you should probably provide (either here if the issue is installing Scrapy or there if it is really about pyndri) additional output, a few more lines preceding the error line you have shared. This is a compilation error (GCC is a compiler), and some previous line should indicate the reason it failed (probably a missing header file from a library you must install in your system beforehand).

**Comment by ZahraGithub** [comment]
You are true. I refer to https://github.com/cvangysel/pyndri
Thanks
