### ISSUE TITLE
set_crawler not working neither warning deprecated?

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#3593]
```
class test(scrapy.Spider):
    name = 'test'

    start_urls = ['http://httpbin.org']

    def set_crawler(self, crawler):
        super(test, self).set_crawler(crawler)
        print(999999999999999)

    def parse(self, response):
        print('ok')
```
considering fixing or removing it?

**Comment by Gallaecio** [comment]
Based on https://stackoverflow.com/a/29763209/939364 I would say it was deprecated more than 3 years ago. A deprecation warning was probably issued in the past, but at some point the code has to be simply removed.

**Comment by VMRuiz** [comment]
There is an actual warning on the code about this been deprecated and its alternative method _from_crawler_

https://github.com/scrapy/scrapy/blob/1fd1702a11a56ecbe9851ba4f9d3c10797e262dd/scrapy/spiders/__init__.py#L55

@NewUserHa What's your point about this?

**Comment by kmike** [comment]
I think that's a valid concern - set_crawler is deprecated and unused, but Scrapy is not checking it, and not calling it, so user never sees a deprecation warning.

**Comment by Gallaecio** [comment]
As @VMRuiz said, the code should be issuing a warning in Scrapy 1.6. We are actually removing this code in 1.7, and its removal will be covered in the release notes: https://github.com/scrapy/scrapy/pull/3846/files#diff-598c16c78e0faacf69ff9ecf4ab00aa9R253

**Comment by kmike** [comment]
The code never issues a warning, because it is not an user who should call `set_crawler` - Scrapy used to call it. Now Scrapy uses `from_crawler` method instead of `set_crawler`. If user defined `set_crawler` method in a Spider subclass, this method just stopped working as a mean to do some work on spider init, without any deprecation warnings - warning is only displayed when a method is called, but Scrapy stopped to call it. This happened a while ago though, I don't think we need to fix that.

**Comment by Gallaecio** [comment]
It seems it hasn’t been working since [`from_crawler` was introduced in Scrapy 1.0](https://github.com/scrapy/scrapy/commit/84fa004793cb1be07c7a3d0ac6fd80a83b4e8487).

I’ve just added comments to the two only StackOverflow responses to questions tagged with `scrapy` that suggest using `set_crawler`[¹](https://stackoverflow.com/questions/21785352/scrapy-cant-write-to-log-in-spiders-init-method/21799505#comment100525334_21799505)[²](https://stackoverflow.com/questions/25353650/scrapy-how-to-import-the-settings-to-override-it/27244390#comment100525666_27244390).

Should we do something else?

We could update the 1.0.0 release notes (in master) to mention this backward-incompatible change. Although I don’t expect much people upgrading from 0.25 these days.

@NewUserHa Do you recall where you learned to use `set_crawler`? Had you been using it since pre-1.0.0 times, were you upgrading a pre-1.0.0 spider, or had you seen it used somewhere recently?

**Comment by NewUserHa** [comment]
don't remember, maybe from scrapy's source code or other's comments.
I might open this issue to say `there's old code need to remove`. but it's not in the master branch now.

maybe mistake and this issue can be closed.
thanks.
