### ISSUE TITLE
try to pass two arguments with -a to spider

### ISSUE THREAD

**Issue by digitaldust** [scrapy/scrapy#3611]
I am trying to pass two argument to scrapy as per the docs, like this:

    scrapy crawl myspider -a product_id=BEHEH -a last_update='01 January 1990' -s LOG_FILE=scrapy.log

but get the error:

    crawl: error: running 'scrapy crawl' with more than one spider is no longer supported

Is this a known behavior or am I missing something?

I am on Mac OSX 10.14.2 with Scrapy 1.5.1

**Comment by joaquingx** [comment]
I cannot reproduce error with Scrapy 1.5.1 on a linux box.

**Comment by Gallaecio** [comment]
If the issue is that your terminal emulator somehow does not handle quoting as others do, you could verify that by changing your date string to a single word (`'01 January 1990'` → `asdf`) and see if that causes you to get a different error.

If that were the case, you should find out how to properly escape spaces in your terminal emulator. You might need to use something like `-a last_update=01\ January\ 1990`.

**Comment by ejulio** [comment]
@digitaldust, can we close this issue?
