### ISSUE TITLE
AttributeError: 'TelnetConsole' object has no attribute 'port'

### ISSUE THREAD

**Issue by Adhders** [scrapy/scrapy#3743]
system w10 ,scrapy 1.6.0

my scrapy can run nomally long before, but raise AttributeError  recently , I have reinstall the Scrapy ,It's  not help.

**Comment by Gallaecio** [comment]
This sounds like a duplicate of #2702. @Adhders Could you confirm?

**Comment by okomarov** [comment]
I have this issue and don't understand why the PR #2892 suggested in #2702 hasn't been merged. 
The workaround is to set `TELNETCONSOLE_PORT = None` in `settings.py` so that `self.port = listen_tcp(self.portrange, self.host, self)` creates an empty port? 

I reckon the suggested PR was much cleaner, just initialize the port to None and do not pollute settings.py with unused settings.

**Comment by Gallaecio** [comment]
Closing as a duplicate of #2702, lets keep the conversation there. Thanks!

**Comment by myuanz** [comment]
Give another possible reason: when an uncaught exception occurs, it will appear. 
I meet it today.
