### ISSUE TITLE
multithread-scrapy error: one thread error, but the other threads cannot stop?

### ISSUE THREAD

**Issue by qingmei-migu** [scrapy/scrapy#3779]
![1ad4989524d9149fcd8e7aa493e9e0b](https://user-images.githubusercontent.com/49146214/57758208-bf65e000-7729-11e9-8332-1e7067eb6db6.png)

before 12:54:43, one thread meets an exception, and the others threads run as usual, this is ok.
But the errors after 12:57:28 is due to the scrapy still running, and canot create a new instance.
I wait for one day, and the scrapy just don't stop. There must have some wrongs.
Lacking essential process after one thread happens an excepetion?

But why? and maybe this bug need to be fixed.

**Comment by grammy-jiang** [comment]
Hi, @qingmei-migu 

I didn't get your point. The error message you gave looks like **Requests** is used instead of **Scrapy**.

If you are using **Requests** and you want to insist to use it, your problem should put into [the issues of **Requests**](https://github.com/kennethreitz/requests/issues).

Otherwise, for Scrapy please refer to [Common Practices — Scrapy 1.6.0 documentation](https://docs.scrapy.org/en/latest/topics/practices.html#running-multiple-spiders-in-the-same-process). There is already a very clear example for multiple spiders running in one twisted reactor.
