### ISSUE TITLE
Adding Type Hints to Scrapy and its Modules

### ISSUE THREAD

**Issue by royahsan** [scrapy/scrapy#4041]
## Summary

We should add Variable Annotations/  Type hints as supported in [PEP 526](https://www.python.org/dev/peps/pep-0526/) , Python 3.6 to Scrapy to help out existing and new contributors and developers in understanding scrapy code. 

## Motivation

Intellisense  enabled IDES like PyCharm need Type hints to provide better experience.
For new contributors to understand Scrapy comprehensively, type hints are vital. 

Consider someone not that familiar with scrapy,  stumbling upon scheduler's constructor.

```
    def __init__(self, dupefilter, jobdir=None, dqclass=None, mqclass=None,
                 logunser=False, stats=None, pqclass=None, crawler=None):
        self.df = dupefilter
        self.dqdir = self._dqdir(jobdir)
        self.pqclass = pqclass
        self.dqclass = dqclass
        self.mqclass = mqclass
        self.logunser = logunser
        self.stats = stats
        self.crawler = crawler
```

**Comment by Gallaecio** [comment]
Related to #3618

**Comment by elacuesta** [comment]
Agreed. This sounds great, we should just keep in mind that Scrapy won't drop support for Python 2.7 until [2.0](https://github.com/scrapy/scrapy/milestone/10)

Also (not exactly what this issue is about, but related), _variable_ annotations were introduced in Python 3.6 ([PEP 526](https://www.python.org/dev/peps/pep-0526/))

**Comment by royahsan** [comment]
@elacuesta great!, actually you are right , type annotation were introduced in [PEP 526](https://www.python.org/dev/peps/pep-0526/) , only function annotations were introduced in [PEP 484](https://www.python.org/dev/peps/pep-0484/) , i was in in little hurry finding the PEP version lol.

**Comment by laurentS** [comment]
> Agreed. This sounds great, we should just keep in mind that Scrapy won't drop support for Python 2.7 until [2.0](https://github.com/scrapy/scrapy/milestone/10)

Based on [mypy docs](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages) it seems that it's possible to provide the type hints as separate stub files, which shouldn't interfere with older versions of python that don't support them. Depending on the timeline for scrapy 2.0, this might be a way to fix this issue earlier...

**Comment by kmike** [comment]
There is also comment-based syntax which works in 2.7. Anyways, I think that'd be great to test the waters on Scrapy dependencies first - w3lib, parsel. See e.g. https://github.com/scrapy/w3lib/pull/123. Python 3 syntax is nicer though, so I'd prefer to go with Python3-only syntax first (3.5+, not 3.6+; for variable annotations one can use comment-based annotations).

**Comment by victorteodoro** [comment]
Hey, guys! Is this a good issue for a scrapy beginner to help with? Is there anyone already working on it?

**Comment by grammy-jiang** [comment]
[Monkeytype](https://github.com/Instagram/MonkeyType) maybe a good choice to automatically add typing hint for existing code:

[Let your code type-hint itself: introducing open source MonkeyType](https://instagram-engineering.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881)

**Comment by grammy-jiang** [comment]
> Considering there are already hundreds and thousands of lines code in Scrapy, [Monkeytype](https://github.com/Instagram/MonkeyType) may be a good choice to automatically add typing hint for existing code:
> 
> > MonkeyType collects runtime types of function arguments and return values, and can automatically generate stub files or even add draft type annotations directly to your Python code based on the types collected at runtime.
> 
> * [Let your code type-hint itself: introducing open source MonkeyType](https://instagram-engineering.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881)
> 
> Before each data type is added manually, I think this can give some help for typing hint.

I have tested [MonkeyType](https://github.com/Instagram/MonkeyType). I get the following conclusions:

- MonkeyType only add typing hint to the input (arguments) and output (return) of the methods which are tested in the test cases
- Because the input (arguments) may be mocked in the test cases, the typing hint  may include this mocked objects' types, which is not accurate
- The **from_crawler** classmethod will be added a typing hint for returning an instance of the class, Monkeytype  can't add `from __future__ import annotations` automatically
- Some imports will be added for typing hint, but this may cause some duplications - Monkeytype will only import from the very detail module path and ignore the imports already imported, e.g.:
```python
...
from scrapy.http import Request  # original imports
...
from scrapy.http.request import Request  # added by MonkeyType
...
```

It seems Monkeytype can help for typing hint in some way, but manually checking the result is still necessary.

**Comment by laurentS** [comment]
@grammy-jiang it sounds similar to mypy's `stubgen`, except the later only does a static analysis of the code. In my experience, the stubs that it produces still require manual adjustments. I don't know how it compares to MonkeyType, in terms of quality of results. Have you checked?

**Comment by laurentS** [comment]
I just came across [pyannotate](https://github.com/dropbox/pyannotate) which does essentially the same job as `MonkeyType`. It might be interesting to compare their outputs.

**Comment by kmike** [comment]
My 2c: I'd prefer high-quality type coverage of a small user-facing part of the Scrapy, over extensive automatically generated type hints, some of them incorrect.

**Comment by grammy-jiang** [comment]
@laurentS Yes, Monkeytype just create stub files first then you can choose to add typing hint to the code manually. The output of Monkeytype is not high quality, not at all.

@kmike if you want to a high-quality typing hint, I am afraid manually adding typing hint is the only way at this moment.

**Comment by laurentS** [comment]
This pytest plugin [pytest-mypy-plugins](https://github.com/typeddjango/pytest-mypy-plugins) might help write tests to check that new typing annotations are correct. This[blog post](https://sobolevn.me/2019/08/testing-mypy-types) explains how to use it. It was written to help annotate Django, so it should be relatively solid.

**Comment by synodriver** [comment]
Well I think [pydantic](https://github.com/samuelcolvin/pydantic/) would be useful if type hints could be added to scrapy in future versions. It could help validate types, also make it easier to read configuration files and environment variables. After adding these settings, the code will be easier to understand. For example, ```Item``` can be defined as subclasses of ```pydantic.BaseModel``` , making it more convenient to use, and settings can be defined as subclasses of ```pydantic.BaseSettings```

**Comment by ChihweiLHBird** [comment]
@grammy-jiang Hey, is there any plan to add type hints to the rest of the mudules of scrapy? I am trying to understand some parts of the project and I think it would be very helpful if there are type hints. If possible, I would like to add some type hints and create a PR for them.

**Comment by Gallaecio** [comment]
Yes, we plan to do it, specially to those parts of the API that users interact with. Feel free to create a pull request to add type hints to some parts of the code.

**Comment by grammy-jiang** [comment]
Hi, @ChihweiLHBird ,

You can go through the previous posts in this discussion, and also this PR:
* https://github.com/scrapy/scrapy/pull/4243

I haven't got time to work on this. Your work about adding typing hints will be very appreciated.

Something you may need to note:
* the strength of typing hints support is different between python versions, you may need to check the python versions that current scrapy supports
* powerful typing hints support from `annotation` of `__future__`

**Comment by half2me** [comment]
Having used pydantic before, I'd be keen on seeing it in scrapy.

**Comment by slix** [comment]
> Considering there are already hundreds and thousands of lines code in Scrapy, Monkeytype may be a good choice to automatically add typing hint for existing code:
>
> It seems Monkeytype can help for typing hint in some way, but manually checking the result is still necessary.
>
> The output of Monkeytype is not high quality, not at all. 
>
> Maybe splitting the work into several stages and implementing one by one is a good idea.

> My 2c: I'd prefer high-quality type coverage of a small user-facing part of the Scrapy, over extensive automatically generated type hints, some of them incorrect.

I ran MonkeyType through the unit tests across the scrapy codebase and saved the changes of all `.py` files.

https://github.com/slix/scrapy/commit/2f22b841f874e948fa80c3dd81166eb0f5f74485 <--

The result is a decent starting point for typing Scrapy. Contributors wouldn't have to run monkeytype and collect types from unit tests themselves.

MonkeyType's output is too messy to commit directly. So each `.py` file still needs a lot of human attention like cleaning up imports and deciding on reasonable types from what unit tests saw.

My output doesn't include `Coroutine` and `AsyncGenerator` due to a bug in MonkeyType (https://github.com/Instagram/MonkeyType/issues/252). There's a lot of activity in this repo about async right now, so that bug may be a blocker.

An alternative to MonkeyType is pytype, which does static analysis. I now wonder whether that would produce better results.

> Yes, we plan to do it, specially to those parts of the API that users interact with.

Should any typing efforts be focused on the APIs shown in the Scrapy documentation instead of on internal code? Should methods starting in underscores be left untyped?

**Comment by Gallaecio** [comment]
> Should any typing efforts be focused on the APIs shown in the Scrapy documentation instead of on internal code?

Yes.

> Should methods starting in underscores be left untyped?

No, but they are indeed on the low end of type-hinting priorities.

**Comment by wRAR** [comment]
This is work in progress with its own `typing` tag, I don't see a reason to have this open.
