### ISSUE TITLE
Cover the scrapy-sticky-meta-params middleware in the documentation

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4109]
https://github.com/heylouiz/scrapy-sticky-meta-params

Related to #3645

**Comment by heylouiz** [comment]
Hey @Gallaecio, cool that you noticed my project.
I've implemented this in a project and decided to move it out, as an extension.
While searching online for similar extensions I came across #3645 and was planning to finish it.

Do you think this is better be out of Scrapy as an extension? Because if you think this could be a good Scrapy feature I will finish what @Granitosaurus started.

PS: This project is not on PyPi yet, my project is using it from Github.

**Comment by Gallaecio** [comment]
I don’t see why it shouldn’t be a part of Scrapy itself, moreover if you yourself would like it so :slightly_smiling_face:
