### ISSUE TITLE
The documentation cannot be built with Sphinx 3

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#4475]

**Comment by anusha94** [comment]
can I take this up?

**Comment by elacuesta** [comment]
Seems like this is an issue in the `sphinx-hoverxref` extension: https://github.com/readthedocs/sphinx-hoverxref/issues/45.
If we can't wait for the upcoming release as mentioned in https://github.com/readthedocs/sphinx-hoverxref/issues/45#issuecomment-609462935, we might want to try disabling it in [our configuration](https://github.com/scrapy/scrapy/blob/2.0.1/docs/conf.py#L31)

**Comment by Gallaecio** [comment]
If they have not released a fixed version by the time we are about to release Scrapy 2.1, we can change our documentation requirements temporarily to specify a Sphinx version older than 3, since we are not using anything specific of Sphinx 3 at the moment.

@anusha94 Given the circumstances, I think it makes sense for use to handle this from the core team.

**Comment by humitos** [comment]
>  If we can't wait for the upcoming release as mentioned in [readthedocs/sphinx-hoverxref#45 (comment)](https://github.com/readthedocs/sphinx-hoverxref/issues/45#issuecomment-609462935), we might want to try temporarily disabling it in [our configuration](https://github.com/scrapy/scrapy/blob/2.0.1/docs/conf.py#L31) [](/scrapy/scrapy/blob/HEAD@{2020-04-06T12:54:18Z}/docs/conf.py#L31)

Hi! I'm one of the authors of sphinx-hoverxref. I've already released 0.2b that includes the fix for Sphinx 3.0. I took a look at the PR and saw that the new warnings made your build to fail (I'm sorry for that), and I created a new issue to take a deeper look at this at https://github.com/readthedocs/sphinx-hoverxref/issues/58

Besides, I saw that you are using some custom roles/objects like [`:setting:`](https://github.com/scrapy/scrapy/blob/master/docs/_ext/scrapydocs.py#L83), `:signal:` and others, and I wanted to let you know that you can enable hoverxref on those as well with the config [hoverxref_roles](https://sphinx-hoverxref.readthedocs.io/en/dirhtml/configuration/#confval-hoverxref_roles). See https://sphinx-hoverxref.readthedocs.io/en/dirhtml/usage/#tooltip-on-custom-object

Happy that an amazing project like Scrapy is using this extension! Thanks for making Scrapy :smile:

**Comment by joybhallaa** [comment]
hey @elacuesta @Gallaecio I'm having the same issue, as I'm working on an issue regarding documentation. Can I be of any help to solve this issue?
