### ISSUE TITLE
[ReactorAlreadyRunning issue] In a dynamic spider for loop 

### ISSUE THREAD

**Issue by secsec2020** [scrapy/scrapy#4483]
Basically, I have two spider. MySpider1 will scrape the index page and extract the link for MySpider2. 
But inside the for loop in MySpider1, it cant start the new spider and return the ReactorAlreadyRunning error. 

```
class MySpider1(scrapy.Spider):
    name = 'GenerateLink'
    start_urls = ['www.index.page']

    def parse(self, response):
        for link in response.css('.a::attr(href)').getall():
			process2 = CrawlerProcess()
			process2.crawl(MySpider2, link)
			process2.start()


class MySpider2(scrapy.Spider):
    name = 'MySpider2'

    def __init__(self, link=None, **kwargs):
        self.start_urls = link
        super().__init__(**kwargs)
		
process = CrawlerProcess(s)
process.crawl(GeneratelinkSpider)
process.start()
```

**Comment by elacuesta** [comment]
This is expected, the docs about [running spiders from scripts](https://docs.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script) say (emphasis mine):
> The first utility you can use to run your spiders is scrapy.crawler.CrawlerProcess. **This class will start a Twisted reactor for you**, configuring the logging and setting shutdown handlers. This class is the one used by all Scrapy commands.

On the other hand, the [`CrawlerRunner`](https://docs.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerRunner) class shifts the responsibilities of starting and stopping the reactor to the user.

For the record, I do not think this is a good practice. I'd recommend using a producer/consumer pattern, even if it is as simple as writing links from the first spider to text files and picking them up from the second spider. More advanced alternatives are available, such as [`scrapy-frontera`](https://github.com/scrapinghub/scrapy-frontera) and [`spider-feeder`](https://github.com/ejulio/spider-feeder). You can find an example project for `scrapy-frontera` [here](https://github.com/elacuesta/frontera-hcf-example) (disclaimer: written by me, hosted under my account).

I'm closing this issue since there is a [StackOverflow question](https://stackoverflow.com/q/61157992) about it, and I consider this neither a bug report nor a feature request. Please feel free to reopen it if you disagree.

**Comment by secsec2020** [comment]
I hope you guide me to a right direction because I am so confused. My spider is now at a bottleneck which only scrape 30 pages/min. So I just start to think of create more spider in a for loop. So I will have more spider to work and work faster. I dont know the way I think a make sense or not. So can you guide me what should I look for ? and can I use this logic : writing links from the first spider to text files and picking them up from the second spider to speed up my spider. Thank you so much

**Comment by secsec2020** [comment]
> This is expected, the docs about [running spiders from scripts](https://docs.scrapy.org/en/latest/topics/practices.html#run-scrapy-from-a-script) say (emphasis mine):
> 
> > The first utility you can use to run your spiders is scrapy.crawler.CrawlerProcess. **This class will start a Twisted reactor for you**, configuring the logging and setting shutdown handlers. This class is the one used by all Scrapy commands.
> 
> On the other hand, the [`CrawlerRunner`](https://docs.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerRunner) class shifts the responsibilities of starting and stopping the reactor to the user.
> 
> For the record, I do not think this is a good practice. I'd recommend using a producer/consumer pattern, even if it is as simple as writing links from the first spider to text files and picking them up from the second spider. More advanced alternatives are available, such as [`scrapy-frontera`](https://github.com/scrapinghub/scrapy-frontera) and [`spider-feeder`](https://github.com/ejulio/spider-feeder). You can find an example project for `scrapy-frontera` [here](https://github.com/elacuesta/frontera-hcf-example) (disclaimer: written by me, hosted under my account).
> 
> I'm closing this issue since there is a [StackOverflow question](https://stackoverflow.com/q/61157992) about it, and I consider this neither a bug report nor a feature request. Please feel free to reopen it if you disagree.

I hope you guide me to a right direction because I am so confused. My spider is now at a bottleneck which only scrape 30 pages/min. So I just start to think of create more spider in a for loop. So I will have more spider to work and work faster. I dont know the way I think is make sense or not. So can you guide me what should I look for ? and can I use this logic : writing links from the first spider to text files and picking them up from the second spider to speed up my spider. Thank you so much
