### ISSUE TITLE
Scrapy with Puppeteer and/or Playwright?

### ISSUE THREAD

**Issue by osmenia** [scrapy/scrapy#4484]
Hi Team, 

I would like to aks , is there any development plan to create Scrapy for Puppeteer and/or Playwright?

tnx a lot

**Comment by elacuesta** [comment]
I don't think either Puppeteer nor Playwright could be integrated directly, as they are Javascript projects. However, there is [`Pyppeteer`](https://github.com/miyakogi/pyppeteer), and some attempts to integrate it with Scrapy (a quick search yields [`lopuhin/scrapy-pyppeteer`](https://github.com/lopuhin/scrapy-pyppeteer) and [`clemfromspace/scrapy-puppeteer`](https://github.com/clemfromspace/scrapy-puppeteer), there might be more projects).

Scrapy added partial support for `asyncio` in 2.0 (see the [`asyncio`](https://docs.scrapy.org/en/latest/topics/asyncio.html) and [`coroutines`](https://docs.scrapy.org/en/latest/topics/coroutines.html) topics). This was released very recently though, barely over a month ago, it doesn't seem like the above projects have had the time to take advantage of it.

It is currently possible to run the following spider. Keep in mind that you need to [enable the AsyncIO reactor](https://docs.scrapy.org/en/latest/topics/asyncio.html#installing-the-asyncio-reactor) for this to work.

```python
from pyppeteer import launch
from scrapy import Spider


class PyppeteerSpider(Spider):
    name = "pyppeteer"
    start_urls = ["https://example.org"]

    async def parse(self, response):
        browser = await launch(
            executablePath="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        )
        page = await browser.newPage()
        await page.goto(response.url)
        title = await page.title()
        yield {"title": title}
```

(Just a proof of concept, not particularly efficient: it requests the page twice, once using Scrapy and  once using Pyppeteer).

**Comment by Gallaecio** [comment]
Probably worth covering at https://docs.scrapy.org/en/latest/topics/dynamic-content.html#using-a-headless-browser

**Comment by elacuesta** [comment]
@osmenia You might also want to check out https://github.com/elacuesta/scrapy-pyppeteer.
Disclaimer: personal project, not officially supported by the Scrapy project, very early stage of development.

**Comment by thernstig** [comment]
@elacuesta Long-time scrapy user here. Since your original post, the Playwright people have created https://github.com/microsoft/playwright-python - this is now a full-feature Python SDK for Playwright. It is supported by Microsoft, and the smart authors of Playwright have made sure to create a great framework so any programming language can implement Playwright. There are multiple languages doing that now.

In addition, Playwright is far superior over Puppeteer.

Making a native plugin in Scrapy for using Playwright to scrape sites would be a huge boost to this project. Having worked with projects that require heavy Javascript and authentication, the solution of using e.g. Splash is inferior to using something like Playwright directly as a downloader.

Is there a chance you could consider this as a strong candidate as a new, future feature?

p.s. I also hope asyncio gets full support and twisted becomes a secondary citizen. asyncio gets far more traction these days, and it has a nicer interface and it correlates with how many other languages work (e.g. Javascript).

**Comment by Gallaecio** [comment]
> I noticed you started crearting https://github.com/elacuesta/scrapy-playwright - any chance this could instead be something that in the future exists under the scrapy org here on Github?

The future is here: https://github.com/scrapy-plugins/scrapy-playwright :slightly_smiling_face:

**Comment by thernstig** [comment]
@Gallaecio that is great news! I hope that `asyncio` graduates from non-experimental as well soon. Then I truly believe Scrapy is "modern" again :)
