### ISSUE TITLE
Scrapy pause/resume Bug ? 

### ISSUE THREAD

**Issue by ghost** [scrapy/scrapy#4509]
My spider is scraping on a big website, so I start it with the pausing and resuming crawls setup. 

`scrapy crawl somespider -s JOBDIR=crawls/somespider-1` 

But every time I pause and resume later, I find that after the resume the spider will revisit all the website in the start_urls again. Is it a bug ?

**Comment by dexax** [comment]
Are You sure that the prev job has been gracefully terminated ? Because this kind of thing should be handled by the dupe filter, the dupe filter dumps the state to the file `requests.seen` inside the `JOBDIR`. So when you got this file, the state will be resumed and already visited pages won't be visited again.

**Comment by elacuesta** [comment]
Please include a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that would help us reproduce the issue.

**Comment by secsec2020** [comment]
Does the duplicate filter apply to start urls ? I saw duplicate request from start urls only

**Comment by wRAR** [comment]
@secsec2020 you are right, it doesn't (you can override `start_requests` to change this). Does this mean this issue isn't about a problem in Scrapy?
