### ISSUE TITLE
item_scraped signal is not fired when crawler is called via API

### ISSUE THREAD

**Issue by noisecoder** [scrapy/scrapy#451]
When using the example from http://doc.scrapy.org/en/latest/topics/practices.html "Run Scrapy from a script" using Windows XP and Python 2.7 it seems the item_scraped passed signal is not fired. The scraping works and shows in its stats that "item_scraped_count" is 60, yet not a single time the associated function gets called.
I connected it using
crawler.signals.connect(self._item_passed, signal=signals.item_scraped)

I also tried 
crawler.signals.connect(self._item_passed, signal=signals.item_passed)
dispatcher.connect(self._item_passed_2, signals.item_scraped)
dispatcher.connect(self._item_passed_2, signals.item_passed)
which didn't get called either.

item_dropped isn't called either.

I have no explicit pipelines defined, just a single basic spider which works fine as seen in the debug logs.

Connecting other signals like 
crawler.signals.connect(self._spider_opened, signal=signals.spider_opened)
works on the other hand.

The main call is:

    def _item_passed(self, item, response, spider):
        print "PASSED"

    def _item_passed_2(self, item, response, spider):
        print "PASSED-DISP"
    
    def _item_dropped(self, item, spider, exception):
        print "dropped"

    def _spider_opened(spider):
        print "spider opened"

    def run(self):
        spider = TestSpider()
        settings = get_project_settings()
        crawler = Crawler(settings)
        crawler.install()
        crawler.signals.connect(reactor.stop, signal=signals.spider_closed)
        crawler.signals.connect(self._item_passed, signal=signals.item_scraped)
        crawler.signals.connect(self._item_passed, signal=signals.item_passed)
        crawler.signals.connect(self._item_dropped, signal=signals.item_dropped)
        crawler.signals.connect(self._spider_opened, signal=signals.spider_opened)
        crawler.configure()
        crawler.crawl(spider)
        dispatcher.connect(self._item_passed_2, signals.item_passed)
        dispatcher.connect(self._item_passed_2, signals.item_scraped)

        crawler.start()
        
        log.start(loglevel=log.INFO)
        reactor.run()

**Comment by zeafynx** [comment]
I also met the same issue!

**Comment by nramirezuy** [comment]
@zeafynx which version of scrapy are you using?

**Comment by zeafynx** [comment]
@nramirezuy I use version 0.24

**Comment by Curita** [comment]
Turns out this is a duplicate issue of an apparently unrelated problem.

The catch here is that `log.start()` has as default argument `logstdout` set to `True` (can be seen [here](https://github.com/scrapy/scrapy/blob/0.24/scrapy/log.py#L114)). When calling Scrapy from the commandline (or calling `log.start_from_crawler()` or `log.start_from_settings()`) this is populated with the `LOG_STDOUT` setting, which is `False` by default.

By itself that wouldn't be a problem, but `LOG_STDOUT` is broken as stated in #265. I've opened a pull request (#1085) to match that default with the one from Scrapy's settings in the meantime so at least this problem won't happen as often. 

Still, callbacks attached to the `item_scrapped` signal from the description of this issue are called, it can be checked by doing anything besides printing (or just changing `log.start(loglevel=log.INFO)` for `log.start(loglevel=log.INFO, logstdout=False)`).

Full scripts that I used to check this for reference: https://gist.github.com/Curita/53eeb1842767344e8863. In `scrapy:master` this doesn't happen because `log.start` doesn't need to be called explicitly.
