### ISSUE TITLE
Support choosing a file path based on item data in media pipelines

### ISSUE THREAD

**Issue by hosunrise** [scrapy/scrapy#4628]
https://github.com/scrapy/scrapy/blob/8b549392f924ddad9536e55c6120638daf688dfd/scrapy/pipelines/media.py#L77-L111

**Comment by Gallaecio** [comment]
`_process_request` is a private method that does not use `item`, so there is no reason for it to receive it.

I imagine you have a use case where you are overriding `_process_request` and you would like to have access to `item` there. Overriding private methods is not a good practice, so instead of asking for `item` to be passed, maybe you should describe your use case, and we can try to figure out an alternative way to support your use case, be it making `_process_request` a public method which also receives `item`, or some other approach.

**Comment by hosunrise** [comment]
When I need process response in `media_downloaded` depend on `item`, the `item` pass to `_process_request`  is necessary.

e.g., generate file path by some `item`'s field.

**Comment by Gallaecio** [comment]
Related StackOverflow question: https://stackoverflow.com/q/62391828/939364

**Comment by ajaymittur28** [comment]
> When I need process response in media_downloaded depend on `item`

This can be achieved by overriding `media_downloaded` in the child class if I understood your issue correctly. You can use `process_item` to maybe set the item as a class attribute in the child and access it from `media_downloaded` using `self.item`.
