### ISSUE TITLE
Document async def interfaces for signals

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#4852]
It'd be nice to mention `async def` approach in https://docs.scrapy.org/en/latest/topics/signals.html#deferred-signal-handlers, and maybe even rewrite the example to it.

**Comment by codeslash21** [comment]
@Gallaecio  I want to work on this issue. Can you please tell how to start with?

**Comment by Gallaecio** [comment]
@codeslash21 Sure.

Scrapy uses Twisted, which has a class called Deferred, which is used to implement asynchronous code. You may find more information about them in the Twisted documentation, but it’s a complex topic, and full understanding is not needed for this task, I think.

However, Twisted also allows to write code using Python coroutines, also known as `async def` syntax. The code still uses deferreds underneath, but its use is transparent to users, and the resulting code is more readable.

We actually have this covered in the documentation of Scrapy, at https://docs.scrapy.org/en/latest/topics/coroutines.html, with a good example of how a piece of code looks with Deferreds, and how the same code can be rewritten with coroutine syntax.

If you manage to understand that example, I think you should be able to handle this task, which would consist of:

1. Adding a second paragraph to https://docs.scrapy.org/en/latest/topics/signals.html#deferred-signal-handlers that mentions that you can also use coroutines, with a link to the coroutine topic.
2. Changing the example to use coroutines instead of deferreds, for better readability.

**Comment by codeslash21** [comment]
@Gallaecio  Thanks, for your guidance.

**Comment by rox117** [comment]
is this issue still up for grabs?

**Comment by Gallaecio** [comment]
@rox117 I think so.

**Comment by burakcank** [comment]
Can I take this issue please ? I have been working on this one for almost a day now, trying to learn my way around coroutines and deferred objects.

**Comment by rox117** [comment]
about to submit a pull request
