### ISSUE TITLE
Force HTTP 1.0

### ISSUE THREAD

**Issue by franciscohanna92** [scrapy/scrapy#4877]
I'm having problems with a site that returns chunked responses. I'm guessing forcing the request to be HTTP 1.0 will solve this. Is there anyway to accomplish this on latest Scrapy version?

**Comment by elacuesta** [comment]
Setting [`DOWNLOAD_HANDLERS`](https://docs.scrapy.org/en/2.4/topics/settings.html#download-handlers) to use `scrapy.core.downloader.handlers.http10.HTTP10DownloadHandler` for the `http/https` schemes should force the use of HTTP/1.0 (not sure it will solve your issue though).
I'm closing this since it looks more like a support question than a bug report or feature request, feel free to reopen if you think it's necessary (see also [_Getting help_](https://docs.scrapy.org/en/latest/#getting-help)).
