### ISSUE TITLE
While using Crawler the sequence of parsing information differ

### ISSUE THREAD

**Issue by Crispae** [scrapy/scrapy#4894]
As i am currently  using the spider crawlspider to fetch link from the home page and then follow  this link continuously ,as the home page satisfy my first rule it extract the urls and call the callback function  which scrape the data from there. While entering/crawling  the second page it no more satisfy the first rule while it still satisfying the second rule and continue pagination, While crawling or scraping it doesnot follow the sequence of pages like (<subomain/domain?page=2,3,4.....) it scraping the page randomly.

To be more specific if the homepage contain 5 link of different categories(coding,music,video,design) it should first the scrape from first link like coding and crawling and scraping it the after it should go with next link but this is not happening.

![Captur22](https://user-images.githubusercontent.com/74324530/99533541-13f7b480-29cc-11eb-81f6-b0e2e8efb528.PNG)

**Comment by elacuesta** [comment]
This issue is lacking actual code that we could debug. I suspect it is a continuation of #4891, so I replied in https://github.com/scrapy/scrapy/issues/4891#issuecomment-729706916.

Please, do not open issues here for support questions, use the ["scrapy" tag at StackOverflow](https://stackoverflow.com/tags/scrapy) instead. See also [_Getting help_](https://docs.scrapy.org/en/latest/index.html#getting-help).
