### ISSUE TITLE
cb_kwargs parameters: sometimes not shallow-copied

### ISSUE THREAD

**Issue by k3kc** [scrapy/scrapy#4918]
### Description
Inconsistent copying method of cb_kwargs parameters: sometimes it's shallow, sometimes it's deep - likely depending on serialization / disc queues

### Steps to Reproduce
```
class A:
    def __init__(self) -> None:
        self.b = B()


class B:
    def __init__(self) -> None:
        self.name = "old"

def start_requests(self):
        self.a = A()
        yield scrapy.Request("http://ya.ru", cb_kwargs={'b': self.a.b})

def parse(self, response, b):
        b.name = 'new'
        logger.info(self.a.b.name)
```

**Expected behavior:**
`new`

**Actual behavior:**
`old`

**Reproduces how often:** 
100%

### Versions
2.4.1, Scrapy cloud

### Additional context
Documentation for meta parameter states that "If given, the dict passed in this parameter will be shallow copied." 
cb_kwargs assumed to be working similarly, but its result can be different, likely if serialization / disc queues are used.

**Comment by elacuesta** [comment]
Indeed, `cb_kwargs` is treated exactly like `meta` (see [this](https://github.com/scrapy/scrapy/blob/2.4.1/scrapy/http/request/__init__.py#L42-L43) and [this](https://github.com/scrapy/scrapy/blob/2.4.1/scrapy/http/request/__init__.py#L46-L56)).
I think the behaviour you're observing is because deserialized requests are different objects. Scrapy users [`request_to_dict/request_from_dict`](https://github.com/scrapy/scrapy/blob/2.4.1/scrapy/squeues.py#L11) and `pickle` (`pickle` is the default, it can be changed by using other queues) to serialize/deserialize:
```python
>>> from scrapy import Request
>>> from scrapy.utils.reqser import request_from_dict, request_to_dict
>>> r = Request("https://example.org")
>>> r is r
True
>>> r is request_from_dict(request_to_dict(r))
False
```

Moreover, `pickle` doesn't preserve object identity either:
```python
>>> import pickle
>>> d = {}
>>> d is d
True
>>> d is pickle.loads(pickle.dumps(d))
False
```
---
For completeness, this is a full spider that shows the behaviour:
```python
# shallow_copy.py
from scrapy import Spider, Request

class B:
    def __init__(self) -> None:
        self.name = "old"

class TestSpider(Spider):
    name = "test_spider"

    def start_requests(self):
        self.b = B()
        yield Request("https://example.com", cb_kwargs={"b": self.b})

    def parse(self, response, b):
        b.name = "new"
        self.logger.info(self.b.name)
```

If executed with `scrapy runspider shallow_copy.py`, the logs show "new", whereas if `-s JOBDIR=test` is added to the command, "old" appears in the logs.

I'm closing this, please re-open if you think it's necessary.

**Comment by k3kc** [comment]
Thank you, this is clear. I'm trying to understand where it would be helpful to provide a hint for such behaviour. I came across this when deployed a spider in Scrapy cloud and it behaved differently to the local stack, despite everything else being equal.
Probably makes more sense to put a note to cb_kwargs description in scrapy documentation that one should not rely on shallow copy behaviour when passing arguments as it will depend on deployment scenarious.

**Comment by elacuesta** [comment]
Assuming you're using Scrapy Cloud, [this support article](https://support.scrapinghub.com/support/solutions/articles/22000200426-what-are-the-differences-between-running-a-spider-locally-and-on-scrapy-cloud-) lists the differences between running a spider locally and on the platform.

I'm not sure about talking about deployment considerations in the Request docs, I think instead a good place to add a note would be the ["Request serialization" section on the Jobs page](https://docs.scrapy.org/en/latest/topics/jobs.html?highlight=jobdir#request-serialization).

**Comment by k3kc** [comment]
Thanks! That's quite a long shot to assume that an average Scrapy user will make such a chain of implications from "JOBDIR is set" to "cb_kwargs shallow copy won't work anymore" :)
I would stress the importance to put a hint into the main Requests section, as not everyone (including myself) will have practical interest in reading Request serialization section, but pretty much everyone will read the main section.
