### ISSUE TITLE
Request yield in spider parse function causing slowness in URL journey

### ISSUE THREAD

**Issue by svnshikhil** [scrapy/scrapy#4926]
Scrapy version **2.1.0**

We have a large crawler running on my production environment. Recently we found that some of the large sites taking too much time to crawl their sites. So we added some logging in our system and found that the **parse** function of spider is causing the issue. 

In **parse** function we are not doing too many tasks but we are generating some child requests and items from this function. Attaching a sample code here

```import scrapy
import logging
from scrapy.linkextractors.lxmlhtml import LxmlLinkExtractor

logging.basicConfig(
    filename='app.log',
    level=logging.DEBUG,
    format='%(asctime)s.%(msecs)03d %(levelname)s %(module)s - %(funcName)s: %(message)s',
    datefmt="%Y-%m-%d %H:%M:%S")


class LinkSpider(scrapy.Spider):
    name = "link"

    link_extractor = LxmlLinkExtractor(allow=(), deny=(), allow_domains=(["example.com"]), deny_domains=(),
                                       deny_extensions=None, restrict_xpaths=(), restrict_css=(), tags=('a', 'area'),
                                       attrs=('href',), canonicalize=False, unique=True, process_value=None, strip=True)

    def __init__(self, *args, **kwargs):
        self.start_urls = "https://www.example.com"
        super(LinkSpider, self).__init__()

    def parse(self, response):

        links = self.link_extractor.extract_links(response)
        links_processing_start = time.time()
        for link in links:
            yield {
                'source_url': response.url,
                'destination_url':link.get('url')
            }
            yield scrapy.Request(url=link.url, callback=self.parse)
        print(time.time() - links_processing_start)
        yield {
            'url': response.url,
            'download_time': response.meta['__end_time'] - response.meta['__start_time'],
            'download_latency': response.meta['download_latency']
        }

    def parseError(self, response):
        print('Error')
```

Here we can see that the for loop is yielding 1 item and 1 request for each URL from link extractor output. If the link_extractor returns 2000 URLs from a page the above loop will take more than 180 seconds to complete 

Please let me know if you have any suggestions on my architecture

**Comment by wRAR** [comment]
> If the link_extractor returns 2000 URLs from a page the above loop will take more than 180 seconds to complete

I doubt that, but how did you measure that? The provided code doesn't measure the loop run time.

**Comment by svnshikhil** [comment]
Hey @wRAR 
Thanks for asking the this

I just updated the above code

**Comment by wRAR** [comment]
Please provide a minimal reproducible example.

**Comment by svnshikhil** [comment]
@wRAR 
Please take a look at the below code. 

Here I am returning a fake HTML with 2000 urls from downloader middleware. In the spider success callback function, the for loop is taking more than 300 seconds to yield the requests and items

https://github.com/svnshikhil/scrapy_crawler

**Comment by wRAR** [comment]
I wouldn't call that code minimal, especially as it seems to be an infinite spider with an exponentially growing queue and it throws exceptions from time to time, but here all loops except the first one take about 40 seconds. Anyway, this metric doesn't seem very useful as it includes time spent sleeping. The loop itself doesn't take any significant time as you can check by separating item and request generation and yielding.

**Comment by svnshikhil** [comment]
@wRAR This is a minified version of my production crawler. In the actual code ,we have customized dupe filter and depth middleware to avoid the infinite jobs.  

We have enabled the depth middleware and dupfilter in the sample code

https://github.com/svnshikhil/scrapy_crawler/commit/8bee826c332feb21677350054f87c78e7b19e64b

**Comment by wRAR** [comment]
Can you please explain what real problems do you have regarding this?

**Comment by svnshikhil** [comment]
Yes, 
Basically, we have a crawler that starts from the seed URL and schedules all links found from the page as a new Scrapy request. This process will continue until the crawler reaches the configured **DEPTH**. 

Recently we found that the **link extraction and request scheduling** code is taking too much time to complete the process when we get HTML with a large number of links. This is causing slowness in our crawler

**Comment by wRAR** [comment]
The link extraction code doesn't take any significant time as I already mentioned. The request scheduling code itself doesn't take any time either, it just doesn't run synchronously. I guess if you want sync you can create a list and then return it instead of yielding individual items.

If you don't agree with this analysis please provide a minimal example of the problem.

**Comment by svnshikhil** [comment]
I tried the suggestion you made in the previous comment. But unfortunately, it's not working. I am still getting the slowness. 

I can still reproduce the issue on https://github.com/svnshikhil/scrapy_crawler. 

Please run the code

**Comment by wRAR** [comment]
I was trying to explain that you are measuring a wrong thing.

**Comment by Gallaecio** [comment]
@svnshikhil As @wRAR [mentioned](https://github.com/scrapy/scrapy/issues/4926#issuecomment-744497810), if your issue is caused by a problem in Scrapy you should be able to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to demonstrate the issue.

Creating a minimal, reproducible example often leads to finding the root issue, which is often not in Scrapy itself, but in a project-specific issue or a lack of understanding of some aspects of Scrapy (sometimes due to incomplete documentation).

Because chances are this is not a bug in Scrapy itself, we must prioritize our time to work on Scrapy bug fixes and features that can benefit the whole Scrapy community, and not (potentially) just your project.

So please, if you really think you have found and issue in Scrapy, and you want it fixed, try and find some time to remove from your project anything that is not required to reproduce the issue, and then share the result.
