### ISSUE TITLE
Collect data and save it in pdf format feature

### ISSUE THREAD

**Issue by StarTrooper08** [scrapy/scrapy#5056]
Note : Not an issue just a Feature I want to make 
### Scrape Data and Save it in pdf format   /  Feature(Idea / Approach for GSoC 2021 )

As we know the PDF format files has become popular now a days . 
Every individual use pdf file from office use to educational use .
I just want to make one feature where one can scrape the data from web and save the parsed text data in pdf format.
This idea came into my mind when I realize in many field individuals use pdf file and web scapers for there office work .
So such individual can be benefited if such feature added .

Please give me suggestion / feedback whether this idea work for us .

Till that I will contribute to some other issue .

Waiting for the precious reply / feedback / suggestion 

Thank You.

**Comment by Gallaecio** [comment]
While it should be technically possible to implement, maybe not even too complicated, I’m not completely sure of the usefulness of the feature, to the point that even if we implemented I think it may make sense to keep it in a package separated from Scrapy itself.

Looking for people asking for a feature like this in the internet, the closest I’ve been was to find an existing project, https://github.com/etng/scrapy-save-as-pdf, which seems to be able to print the webpages in PDF format. If that’s what you are thinking, if the feature you are proposing is to print the web pages (rather than the parsed data) in PDF format, I can see an use for it, even though I think screenshots may be better. But given https://github.com/etng/scrapy-save-as-pdf exists, and assuming it works, it would probably be best not to reinvent the wheel. Otherwise, maybe this should be implemented as part of a headless browser, either Splash or something fresher like https://github.com/scrapy-plugins/scrapy-playwright

If that’s not what you meant, and you actually want the extracted data to be exported in PDF format, I wonder how that would look like, and what the use case would be. Would it be similar to the result of exporting a CSV file as PDF from LibreOffice Calc?

**Comment by StarTrooper08** [comment]
Ya I want to save the parse data in pdf format.
It will be little bit complicated.
But I will try my best .

**Comment by Gallaecio** [comment]
What would it look like? Would it be similar to the result of exporting a CSV file as PDF from LibreOffice Calc?

**Comment by StarTrooper08** [comment]
No , I m planning to make python function which can directly parse data and save it in pdf format directly.

**Comment by Gallaecio** [comment]
I mean the resulting PDF. What would that output file look like?

**Comment by StarTrooper08** [comment]
It will be proper pdf file

**Comment by StarTrooper08** [comment]
I guess I m creating confusion.
Please give me time , I will try to come up with code snippets.

**Comment by StarTrooper08** [comment]
I have one doubt can I ask?

**Comment by Gallaecio** [comment]
Ask away

**Comment by StarTrooper08** [comment]
If I mail the GSoC 2021 proposal before 29-03 will it be ok.

**Comment by Gallaecio** [comment]
You can share a public link to your proposal here, in a comment to this GitHub issue, so that the community can review it and provide feedback.

**Comment by StarTrooper08** [comment]
Ok

**Comment by StarTrooper08** [comment]
> What would it look like? Would it be similar to the result of exporting a CSV file as PDF from LibreOffice Calc?

@Gallaecio  I came up with new idea quite different from previous . I think it will be better than previous one.

Idea : RSS-api extraction package


![weather.PNG](https://user-images.githubusercontent.com/72031540/112437890-76dbcc80-8d6d-11eb-85a3-854eb4cf0325.PNG)

Here is the snippet which shows how the weather data is been gather.

#api extraction(json-to-csv) :

How it will be implemented:
1 . Extract data from api which is in json form.
2. The parse json data will be store in list for temporary purpose.
3. The function will be there which will give option whether to print the data in CSV or pdf file.


The api functions will be specificly for popular and most used api website.
For example openweather api, news api etc.

#RSSfeed.extraction (xml-to-csv):

How it will be implemented:

 The xml data from RSS feed website will be extracted.
 The extracted data will be stored as XML file at initial stage.
 And if want to store it in CSV file ,this can be done using function which we will create for RSS feed.extraction.

Any rss feed website can be used for the rssfeed functions.

What is the need of this project (RSS-api extraction):
 User using this package can easily access the json data of api with by just passing few parameters.
 Individual can store it in CSV file for Data Science usage or in pdf file for report kind of purpose .
 User can extract the XML file for making own mini web service .
 Because of the package user can get the json,XML data by just few parameters and functions. And store it in CSV or pdf file.

The RSS-API extractor project can be published on pypi for other users to use it .

I will be using few packages for this project like request, csv ,fpdf etc.

Please let know can we implemented this idea.
And also feedback and suggestion how this can be made more useful.

**Comment by StarTrooper08** [comment]
> What would it look like? Would it be similar to the result of exporting a CSV file as PDF from LibreOffice Calc?

@Gallaecio  I came up with new idea quite different from previous . I think it will be better than previous one.

Idea : RSS-api extraction package


![weather.PNG](https://user-images.githubusercontent.com/72031540/112437890-76dbcc80-8d6d-11eb-85a3-854eb4cf0325.PNG)

Here is the snippet which shows how the weather data is been gather.

#api extraction(json-to-csv) :

How it will be implemented:
1 . Extract data from api which is in json form.
2. The parse json data will be store in list for temporary purpose.
3. The function will be there which will give option whether to print the data in CSV or pdf file.


The api functions will be specificly for popular and most used api website.
For example openweather api, news api etc.

#RSSfeed.extraction (xml-to-csv):

How it will be implemented:

 The xml data from RSS feed website will be extracted.
 The extracted data will be stored as XML file at initial stage.
 And if want to store it in CSV file ,this can be done using function which we will create for RSS feed.extraction.

Any rss feed website can be used for the rssfeed functions.

What is the need of this project (RSS-api extraction):
 User using this package can easily access the json data of api with by just passing few parameters.
 Individual can store it in CSV file for Data Science usage or in pdf file for report kind of purpose .
 User can extract the XML file for making own mini web service .
 Because of the package user can get the json,XML data by just few parameters and functions. And store it in CSV or pdf file.

The RSS-API extractor project can be published on pypi for other users to use it .

I will be using few packages for this project like request, csv ,fpdf etc.

Please let know can we implemented this idea.
And also feedback and suggestion how this can be made more useful.

**Comment by Gallaecio** [comment]
@StarTrooper08 I’m sorry to say that none of the two ideas seem like a good fit for Scrapy.

The PDF idea does not seem useful enough to make it into Scrapy. It could be implemented as a Scrapy plugin, but even so I don’t find it very useful. If the choice for PDF is for readability purposes, CSV is often a better choice, since spreadsheet software like LibreOffice Calc can be used for visualization.

Your idea to provide an API or project to extract information for some popular RSS feeds is not in line with the way we usually design our data extraction open source libraries. We create projects that offer the tools for people to write and maintain their own spiders. What you are suggesting sounds like writing and maintaining spiders for specific RSS feeds in the internet. That would only be useful for people interested in scraping those specific websites, and it would require active maintenance to keep up with upstream changes.

Please, have a look at the [suggested Scrapy ideas](https://gsoc2021.zyte.com/ideas#scrapy) and at [open issues](https://github.com/scrapy/scrapy/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) to get a grasp of the kind of features that the Scrapy community wishes to have, and try to come up with an idea in line with those, or directly based on one of them.

**Comment by StarTrooper08** [comment]
Ok np I will come up new idea .

**Comment by StarTrooper08** [comment]
Or else fix the issues and features which are needed the most right now.

**Comment by Gallaecio** [comment]
Thanks!
