### ISSUE TITLE
scrapy genspider [options] <name> <domain> 

### ISSUE THREAD

**Issue by Assadzy** [scrapy/scrapy#5060]
### Description

Whenever the scrapy genspider is initiated with domain that includes http/https, multiple http/https are included in spider start_urls,

### Steps to Reproduce

1. If 'http' already exists in scrapy genspider [options] <name> http://domain.com 
2. Domain must be considered as it is
3. else http or https can be added which is normal behaviour  

**Expected behavior:** Upon initiating a genspider, <domain> should expect http if it exists it must not add http/https in start_urls

**Actual behavior:** Upon executing scrapy genspider [options] <name> http://domain.com, it creates spider with start_urls = ['http://http://domain.com/'] 

**Reproduces how often:**  Every time we copy website link from browser and try to create a genspider

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

Scrapy       : 2.3.0
lxml         : 4.5.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.8.5 (default, Sep 21 2020, 01:55:45) - [Clang 7.0.2 (clang-700.1.81)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 3.1
Platform     : macOS-10.16-x86_64-i386-64bit

**Comment by elacuesta** [comment]
There a little bit of confusion about this topic, and since it's not the first time it comes up (#3553 comes to mind but there could be others, I didn't take the time to do a deep search), I'm going to treat this as a documentation improvement request. 

The behaviour you are observing is expected, because the `genspider` command expects a **domain**. By contrast, "http://domain.com" is not a domain but an URL, containing information about the protocol to be used to access the resource (HTTP).

Perhaps we could do some processing to detect the format of the arguments and act accordingly, but I wanted to clarify that the current behaviour is consistent with the [documentation](https://docs.scrapy.org/en/2.4/topics/commands.html#std-command-genspider).

**Comment by Gallaecio** [comment]
Now URLs are supported as input: https://github.com/scrapy/scrapy/pull/4439

However, we still simply extract the domain from them. Which means that the input protocol is not respected. Maybe we can keep this open to change that?

**Comment by Gallaecio** [comment]
Actually, https://github.com/scrapy/scrapy/issues/3553 probably makes more sense to track that remaining work, since the oritional issue description targets specifically passing an HTTPS URL.
