### ISSUE TITLE
Starting contributing 

### ISSUE THREAD

**Issue by luisotaviocap98** [scrapy/scrapy#5109]
Hello everybody. I am a Brazilian student at UTFPR. I would like to contribute with Scrapy and I would like to ask someone to refer me to an issue to start, most of the issues I saw are already in progress or have been finalized. Thanks

**Comment by Gallaecio** [comment]
This is a common problem in Scrapy. Whenever we tag an issue as a “good first issue”, someone new often starts working on it no longer after.

Some of those listed in https://github.com/scrapy/scrapy/contribute do not have pull requests targeting them, but they are all about improving the documentation.

Anything that is not tagged as a “good first issue” is potentially too hard for someone unfamiliar with the Scrapy code base. So I’m hesitant to suggest issues that are not tagged as so. You could review other issues yourself, see if anything catches your eye. Or you could look into issues that affect yourself. You can also look into improving the documentation or improving [test coverage](https://app.codecov.io/gh/scrapy/scrapy); for some people these are not as gratifying as implementing features or fixing tests, but they are also a good way of forcing yourself to deep into the code base, which could put you in a better place to handle harder issues.

I’ll keep this issue open because I think it may be a good idea to extend https://docs.scrapy.org/en/master/contributing.html to cover this topic, of suggestions for people that want to start contributing but do not know what work to do.

**Comment by luisotaviocap98** [comment]
All right. Thank you for your attention, @Gallaecio . I'm going to take a look at this part of the documentation and testing. As I use Scrapy, I will see if there are any bugs to report or any ideas for new features. If you need help with ideas for new contributors you can call me.
