### ISSUE TITLE
Scrapy pronunciation 

### ISSUE THREAD

**Issue by S4NT14G0** [scrapy/scrapy#5280]
My co-worker has been making everyone laugh in our daily standups while saying the word scrapy.  This sparked a debate of how to pronounce this library name..  Please advise.

**Comment by pablohoffman** [comment]
Hehe, this is a nice discussion comes back every now and then. tl;dr: both pronunciations are accepted.

Originally we pronounced it like this: https://www.youtube.com/watch?v=IUFJdsNZYlA - because a lot of the team behind it were native Spanish (Uruguayans) and that pronunciation felt more natural.

Then came /ˈskreɪpaɪ/ SKRAY-peye - which I think it's more natural to English native, and we decided that both pronunciations were accepted, cause both were pretty embedded by then. A consequence of the distribute nature of how Scrapy started and the fact that most conversations happened over text chat, not spoken conversations :)
