### ISSUE TITLE
-a settings can crash Scrapy

### ISSUE THREAD

**Issue by woho** [scrapy/scrapy#5390]
### Problem

The Scrapy command-line tool lets you directly modify internal variables using the `-a` arguments, without validation or parsing steps. Invalid user input can crash the program:

`scrapy crawl <spider> -a start_requests=bla`

I have to say it explicitly that it is bad design when invalid user input crashes a program. Also the way the `-a` option are implemented contradicts the recommended design practice of having application layers with clearly defined interfaces. 

### Solution
Since passing arbitrary arguments can be done with environment variables, I suggest removing the `-a` options completely. Environment variables have to be parsed explicitly and that's a good thing here, since it automatically pushes the developer toward implementing proper parsing & validation of user input in a dedicated application layer. Another advantage is that environment variables can be passed to container (Docker) images, which are probably very commonly used to deploy Scrapy applications.

**Comment by wRAR** [comment]
> Since passing arbitrary arguments can be done with environment variables, I suggest removing the -a options completely.

I'm afraid this is an overreaction, envvars or no. If you want to prevent users of your spider from overwriting spider attributes, override `__init__` and don't call `self.__dict__.update(kwargs)`. 

> automatically pushes the developer toward implementing proper parsing & validation of user input

Sounds like your problem is caused by separating the spider developer and the spider user. There are many ways to break the spider, e.g. by providing bad setting values. If you indeed have a valid use case where you need to protect the spider from bad user input, removing `-a` is both not necessary (because as I've already mentioned you can disable attribute assignment) and not enough.

> Another advantage

You can already parse envvars in your code.
