### ISSUE TITLE
Scrapyd needs to communicate LOG_FILE and FEEDS to Scrapy

### ISSUE THREAD

**Issue by jpmckinney** [scrapy/scrapy#5498]
Since 2.0.0, overriding settings with environment variables is deprecated. However, Scrapyd needs some way to override LOG_FILE and FEEDS, so that it can configure the output of the spiders it runs.

At present, Scrapy's only interface is a settings file. However, having Scrapyd write a temporary settings file for each crawl seems like a big hack.

I don't see why it's a problem for environment variables to override settings (I do this in my own Scrapy projects!), so ideally we can restore LOG_FILE as a non-deprecated override.

In the case of FEEDS (a dict), Scrapyd uses the deprecated FEEDS_URI (a string). Setting and reading a dict in an environment variable is a bit awkward. I'm not sure what to do about this case.

**Comment by elacuesta** [comment]
(This is a long shot because I'm not really familiar with `scrapyd`, so the following might not make any sense :sweat_smile:) Would it be possible to use the `settings` argument in [this invocation](https://github.com/scrapy/scrapyd/blob/1.3.0/scrapyd/runner.py#L43) of [`scrapy.cmdline.execute`](https://github.com/scrapy/scrapy/blob/2.6.1/scrapy/cmdline.py#L109)?

**Comment by jpmckinney** [comment]
Aha, that should do it! I'll close this issue and update https://github.com/scrapy/scrapyd/issues/369

**Comment by elacuesta** [comment]
Awesome, glad to help 😄
