### ISSUE TITLE
item piplines can not be enabled

### ISSUE THREAD

**Issue by zerokkkk** [scrapy/scrapy#5916]
### Description

After starting crawl, it printed:
```
[scrapy.middleware]  INFO: Enabled item pipelines:
[]
```
but I had enabled it in settings.py

### Steps to Reproduce

1. start a new project
```
scrapy startproject test1
cd test1
scrapy genspider music sekai.best
```
2. paste following code in items.py
```
import scrapy


class PjskMusicItem(scrapy.Item):
    name = scrapy.Field()
    url = scrapy.Field()
    pass
```
3. paste following code in music.py
```
import scrapy
from test1.items import PjskMusicItem

class MusicSpider(scrapy.Spider):
    name = "music"
    allowed_domains = ["sekai.best"]
    start_urls = "http://sekai.best/"

    def start_requests(self):
        yield scrapy.Request(self.start_urls,self.parse)

    def parse(self, response):
        item = PjskMusicItem()
        item['name'] = "0001"
        item['url'] = "https://storage.sekai.best/sekai-assets/music/long/0001_01_rip/0001_01.mp3"
        print('###########################')
        yield item
        print('###########################')
```

4. paste in pipelines.py
```
from itemadapter import ItemAdapter
from scrapy.pipelines.files import FilesPipeline

class Test1Pipeline(FilesPipeline):
    def process_item(self, item, spider):
        return item
```
5. enable `ITEM_PIPELINES`, turn `ROBOTSTXT_OBEY = False` and add follow in setting.py
```
FILS_STORE = '../music_'
FILES_URLS_FIELD = 'url'
FILES_RESULT_FIELD = 'file'
```

6. run it:
`scrapy crawl music`

**Expected behavior:** 
no enabled pipelines 
```
[scrapy.middleware] INFO: Enabled item pipelines:
[]
```
and `yield` in `parse` retern `item` to the terminal

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

```
Scrapy       : 2.8.0
lxml         : 4.9.1.0
libxml2      : 2.9.14
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.21.0
Twisted      : 22.2.0
Python       : 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
pyOpenSSL    : 23.0.0 (OpenSSL 1.1.1t  7 Feb 2023)
cryptography : 39.0.1
Platform     : Windows-10-10.0.19044-SP0
```

**Comment by GeorgeA92** [comment]
Conclusion (most likely) - setting name mistyped

According to files pipeline source code - it is expected that `FILES_STORE` setting will be defined:
https://github.com/scrapy/scrapy/blob/c34ca4aef5fbfeba5c832a327ee36147cd6fb20f/scrapy/pipelines/files.py#L382-L384


> FILS_STORE = '../music_'
FILES_URLS_FIELD = 'url'
FILES_RESULT_FIELD = 'file'

While on previous message I see that only `FILS_STORE` (probably mistyped setting name) was set.

As (probably due to mistyped setting) `FILES_STORE` setting didn't set - pipeline's `__init__` raised `NotConfigured` and disabled
https://github.com/scrapy/scrapy/blob/c34ca4aef5fbfeba5c832a327ee36147cd6fb20f/scrapy/pipelines/files.py#L336-L338

Side comment: +1 case to apply something like I proposed on https://github.com/scrapy/scrapy/issues/4302#issuecomment-596271546

**Comment by zerokkkk** [comment]
I'm sorry for my carlessness. However, although the pipeline was enabled after correcting this error, it seems that `item` was still not sent into the pipeline. Is there any other thing need to be setup?

**Comment by wRAR** [comment]
> it seems that item was still not sent into the pipeline

How can you know this? Your pipeline doesn't do anything.

> print follow instead:

Items are printed by default.

**Comment by zerokkkk** [comment]
oh,yes, it is as you say. I found bug in my full code.

Really thanks for your help!
