### ISSUE TITLE
Add Link to BSD-3 License

### ISSUE THREAD

**Issue by jtoallen** [scrapy/scrapy#6338]
As I am worked through your project repository I found most of what I needed to know about your project in the very informative README.md. 

As a developer new to the open source development community, it took me awhile to find your license though.  I eventually found it.  When I did find the license, I still was not sure if it was an Open Source Initiative (OSI) approved license, so I had to leave your site and go to Google to learn more.  

I found my answer, but I think it would be easy to provide this link to your documentation and it would improve the user experience.  

My suggestions are two-fold.  

First, include this link in the BSD-3-Clause license section of your repository.   https://opensource.org/license/bsd-3-clause
Second, state plainly that your project is operates under an Open Source Initiative approved license.

**Comment by wRAR** [comment]
Do you have any examples where this is done? 

(I think that it's easy to find the license because it's linked in all the usual places and that if someone knows about OSI and why is it important they should know the basic OSI-approved licenses by their names, but maybe there are indeed some additional GitHub-provided buttons to make what you ask)

**Comment by Gallaecio** [comment]
> As a developer new to the open source development community, it took me awhile to find your license though.

Searching for “license” in the README.rst file should work right away. On top of that, if you are reading it from GitHub, it shows you the license in multiple places.

> I had to leave your site and go to Google to learn more

Well, to me this sounds like a positive :slightly_smiling_face:. 

I don’t think there is anything we need to do here. If you were unfamiliar with open source licenses, it is normal that you did not find all the information about them, or a link to that, in this repository. We could change the README wording to say “open source” instead of “BSD-licensed”, but other than that, I don’t think there is much of an action needed here.

**Comment by jtoallen** [comment]
Thanks for your reply and consideration.

It sounds like you like your project as it is.

I did not know what OSI was until a few weeks ago.  I had several other projects that I wanted to get involved with, but although they claimed to be “open source” projects, they were not actually licensed under an OSI license.

I proposed the changes to your repo for the sake of clarity. Your repo was the fifth one that I evaluated.  I grew tired of looking for licenses on sites and then trying to verify is the “open source” project was actually an OSI licensed project.

On your well documented site, I found almost everything I needed right away, except, that I could not confirm if your project was an OSI one or not.

Anytime someone has to bounce from your site to answer a basic question that you could solve with one sentence “we are operating in the OSI approved BSD-3-Clause license (link)”, then I see room for improvement.

It sounds like as a matter of preference you prefer to have users leave your site for Google.  That part I don’t really understand.  Can you tell me why that is a good thing?

I thank you again for your reply and consideration.

Jason Allen


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wRAR** [comment]
> but although they claimed to be “open source” projects, they were not actually licensed under an OSI license.

Do you have examples?

> Anytime someone has to bounce from your site to answer a basic question that you could solve with one sentence “we are operating in the OSI approved BSD-3-Clause license (link)”, then I see room for improvement.

I can imagine several more questions (e.g. "is this copyleft or permissive?", "can I use this in closed-source software?") that are even more important than the one you propose while also being basic and I don't think those need to be answered in the README either. 

> Can you tell me why that is a good thing?

I agree that learning about a license you are going to use for your code is a good thing.

Actually, almost the only circumstances when a user cares that the project license is OSI-approved but doesn't care about _its actual provisions_ is when they are told at a school to contribute to an OSI-approved open source project or when they want to make some kind of a distribution/software archive.
