### ISSUE TITLE
Method/exception for gracefully killing a crawl

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#6452]
There doesn't seem to be any mechanism to gracefully kill an entire crawl from inside the crawl. I've had to do it a hacky way with a global variable. Simplified example:

```
global global_crawler_process

class MySpider():
    ...
    except Exception:
        kill_crawl()

def main():
    globals global_crawler_process

    global_crawler_process = CrawlerProcess(scrapy_settings)
    global_crawler_process.crawl(MySpider)

def kill_crawl():
    globals global_crawler_process
    # Uses SIGABRT (Abort signal)
    global_crawler_process._signal_shutdown(22, 0)


class MySpider():
    ...
    except Exception:
        kill_crawl()

```

Note: This is distinct from `CloseSpider` which only closes the current spider.

**Comment by wRAR** [comment]
`engine.close_spider()`

**Comment by mohmad-null** [comment]
> `engine.close_spider()`

Thanks, but: 
a) What's the `engine` and how do I access it from
b) Where is this documented? I can't find it in the docs anywhere.
c) (most important) - I don't want to kill a spider, I want to kill the entire crawl.

**Comment by wRAR** [comment]
a) An instance of `ExecutionEngine`. Usually accessed via a Crawler instance, which in turn is available in various places as an attribute or an argument. Places where it isn't available usually cannot call any other Scrapy code anyway so for those places the answer may be "you can't".
b) I don't think it's currently documented explicitly. 
c) You can't easily kill a spider with a `CloseSpider` exception because there are only 2 or so code paths where it's handled. But, yes, those handlers call `ExecutionEngine.close_spider()`. OTOH I don't see a good way (as in, a good API that could do it) to kill a CrawlerRunner instance (if that's what you want) without having an instance of it, feel free to propose one.
