### ISSUE TITLE
Add Azure Blob Storage Exporter to Scrapy's Standard Feed Exporters

### ISSUE THREAD

**Issue by holodorum** [scrapy/scrapy#6465]
## Summary

Currently, Scrapy supports exporting feeds to two cloud providers: Google Cloud Storage and AWS S3. Is there any interest in an exporter for Azure Storage to extend Scrapy's cloud capabilities and accommodate users who rely on Microsoft's cloud infrastructure.

## Motivation

This feature would allow Scrapy users who utilize Azure as their primary cloud provider to directly export their scraped data to Azure Blob Storage. This integration would streamline workflows for organizations and developers using Azure, enabling them to keep all their cloud operations within a single platform.

**Comment by Gallaecio** [comment]
[There’s already a separate plugin for that](https://github.com/scrapy-plugins/scrapy-feedexporter-azure-storage).

**Comment by holodorum** [comment]
Yeah I found that one too, thanks! Just wondering, is there a specific reason that an Azure integration isn't part of the standard library but GCP and AWS integrations are?

**Comment by Gallaecio** [comment]
I think it was a timing thing. In general, with Scrapy we are increasingly trying to split off bits, which has several advantages, mainly making maintenance of both Scrapy and those split off components easier. If we were to add GSC or S3 support today, I think we would also go for the same approach as with Azure.

We do need to improve the docs to mention those other plugins, though, so that people can easily find them.

**Comment by holodorum** [comment]
That's clear, thanks for the explanation
