### ISSUE TITLE
rename str_to_unicode and unicode_to_str functions

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#778]
I think that `unicode_to_str` and `str_to_unicode` names are misleading: `unicode_to_str` can accept input which is not unicode, and 'str' is ambiguous in Python 2.x / 3.x; `str_to_unicode` can accept input which is not `str`.

What about renaming them to `text_to_bytes` and `text_to_unicode`? "Text" will mean "either a bytestring or a unicode string".

Django uses `force_bytes` / `force_text` names for similar utilities; the difference is that they acept any objects, not just bytes/unicode as input. 

"Text" means "unicode" in Django names. This makes sense because not all bytestrings are a representation of text. I think that for Scrapy bytestrings acceptable by `text_to_bytes` and `text_to_unicode` functions *are* representation of text, so "either a bytestring or a unicode string" meaning is OK in Scrapy.

**Comment by klangner** [comment]
If I understand it correctly in python3:
`unicode_to_str` accepts `Str` and `Binary` as input and output is always `Binary`
`str_to_unicode` accepts `binary` and `Str` and output is always `Str`

I'm not sure if in all places this will be correct behaviour in py3. It would be good to rename this functions (`force_bytes/force_text` sounds good to me) so they will make sense in py3. And probably it will be necessary to add another functions which will return `Str` in py3.

Also the current tests are misleading in py3.
For example:

`self.assertEqual(unicode_to_str(u'\xa3 49'), '\xc2\xa3 49')`
`assert isinstance(text, str)` 
Expected type is string in py3, but should be binary

What should be done with those tests in py3? (tests/test_utils_python.py)

**Comment by kmike** [comment]
> If I understand it correctly in python3:
unicode_to_str accepts Str and Binary as input and output is always Binary
str_to_unicode accepts binary and Str and output is always Str

That's correct. To be precise, 

* Str == unicode in Python 2.x;
* Str == str in Python 3.x; 
* Binary == str == bytes in Python 2.x; 
* Binary == bytes in Python 3.x.

> I'm not sure if in all places this will be correct behaviour in py3. It would be good to rename this functions (force_bytes/force_text sounds good to me) so they will make sense in py3. And probably it will be necessary to add another functions which will return Str in py3.

I don't quite understand this, could you please explain it? 

> What should be done with those tests in py3? (tests/test_utils_python.py)

The test should be fixed. `bytes` is an alias for `str` in Python 2.x; test should be written like this:

```
self.assertEqual(unicode_to_str(u'\xa3 49'), b'\xc2\xa3 49')  # note b prefix
assert isinstance(text, bytes)  # this is a name for Binary compatible with both 2.x and 3.x
```

**Comment by klangner** [comment]
Thanks for the answers.

>> I'm not sure if in all places this will be correct behaviour in py3. It would be good to rename this 
>> functions (force_bytes/force_text sounds good to me) so they will make sense in py3. And probably
>> it will be necessary to add another functions which will return Str in py3.

> I don't quite understand this, could you please explain it?

I wanted to say that it would be good to rename this functions. I don't know if in all places where this functions are called it would be ok to have bytes as output type. If  not, maybe it will be necessary to add another pair of functions which will return `str` instead of `bytes`

**Comment by Curita** [comment]
>I wanted to say that it would be good to rename this functions. I don't know if in all places where this functions are called it would be ok to have bytes as output type. If not, maybe it will be necessary to add another pair of functions which will return str instead of bytes.

Not sure if I understood that myself. Talking about ``str`` is maybe confusing since it has different meanings depending on Python's version.

Strings come in two (and only two) "flavors", they are unicode objects, or they are bytes objects (this distinction was made clearer on Python 3). ``str`` either refers to bytes on Python 2 (It's an alias for it as @kmike said) or unicode on Python 3 (the actual ``unicode`` type was replaced for ``str`` on Python 3).

We should focus on making this distinction explicit to make code Python 2 and Python 3 compatible, and that means to stop using ``str`` alias, have "u" and "b" prefixes on strings, and use ``six.text_type`` and ``bytes`` accordingly while checking string types.

**Comment by kmike** [comment]
We (@dangra, @eliasdorneles and me) decided to go with `to_bytes` and `to_unicode` names.
