### ISSUE TITLE
CrawlSpider improvements

### ISSUE THREAD

**Issue by dangra** [scrapy/scrapy#781]
A ticket to kickoff the discussion on CrawlSpider enhancements (if any)

ideas:
- Simplify rule definitions by using an implicit linkextractor instanciated from LxmlLinkExtractor.
- ... what else?

**Comment by redapple** [comment]
I would also add something related to https://github.com/scrapy/scrapy/issues/929, that is passing the response to `process_request` in `_requests_to_follow`, so that one can tweak the generated requests with some context. (If there's another way currently than overriding `_request_to_follow`, it'd be happy for it to be documented :)

Oh, and also adding `errback` to rules could be handy at times: see http://stackoverflow.com/a/35870000/2572383

**Comment by guillaumedsde** [comment]
> I would also add something related to #929, that is passing the response to `process_request` in `_requests_to_follow`, so that one can tweak the generated requests with some context. (If there's another way currently than overriding `_request_to_follow`, it'd be happy for it to be documented :)
> 
> Oh, and also adding `errback` to rules could be handy at times: see http://stackoverflow.com/a/35870000/2572383

is this a planned feature?

**Comment by elacuesta** [comment]
> is this a planned feature?

@guillaumedsde Please see #3682 (included in version `1.7.1`) and #4000 (in progress).

**Comment by elacuesta** [comment]
Seems to me like everything has been addressed :ok_hand:
