### ISSUE TITLE
Item validation

### ISSUE THREAD

**Issue by nramirezuy** [scrapy/scrapy#844]
I been thinking in implementing some kind of `Item` validation making use of `Field`. 
The idea behind this is to normalize the data types and formats on the fields.

Declaration approaches:

``` python
# Django like
class Product(Item):
    name = CharField(max_length=30, can_be_none=False)
    colors = ListField(max_length=5)
    price = FloatField(max_digits=5, max_value=10.0)

# Simpler and more flexible
class Product(Item):
    name = Field(validator=lambda value: return True or False) # maybe pass the item to do some comparation
    colors = Field(validator=lambda x: isinstance(x, list))
```

The main problem I have right now is understand when we want to do the validation, at first I thought that doing the validation when a value is assigned was good but it can have complications with mutable types. Another options is to add a method that run the validation for every field but who will call this method? the spider?(I don't want to relay on the developer) and a middleware looks overkill.

What do you think?

**Comment by cathalgarvey** [comment]
Hi folks, is there still interest in this? I agree that we shouldn't roll our own. I personally like [Voluptuous](https://github.com/alecthomas/voluptuous) out of the few validator libraries I've looked at. It strikes a nice balance of simplicity, clarity, and hackability.

**Comment by kmike** [comment]
A common approach is to create a pipeline which validates data, or a separate post-processing script. A related package: https://github.com/scrapy-plugins/scrapy-jsonschema.

But I guess the main idea here is to allow validation as a part of Item definition. This issue is related: https://github.com/scrapy/scrapy/issues/2749 - the idea is to allow https://github.com/python-attrs/attrs instances instead of scrapy items; `@attr.s` classes already provide an option for per-field validation. If we're to extend Scrapy items, then maybe efforts can be better spent on allowing `@attr.s` instance - this would allow better interoperability with the rest of Python ecosystem, more features out of box, and less maintenance efforts from our side.

Probably we can also support Python 3.7 dataclasses, though they are less feature rich and don't support validation.

**Comment by kmike** [comment]
So I'm 

* -1 to adding a built-in validation solution using Voluptuous, schema or jsonschema (as it can be easily done in a plugin); 
* -0 on extending Item to allow per-field validation (it can't be done in a plugin, but it requires more maintenance efforts from pour side); 
* +1 to add support for `@attr.s` instances to Scrapy (it solves this problem, as well as several other problems)

**Comment by Gallaecio** [comment]
Should we close this, given `@attr.s` support has been added as part of #3881?

**Comment by wRAR** [comment]
I think this is fixed by adding several validating classes to python-itemadapter.
