### ISSUE TITLE
Scrapy Only Close Spider and never dumped Scrapy status

### ISSUE THREAD

**Issue by AlanChien** [scrapy/scrapy#945]
Hello,

I have found some issue recently .

I use Scrapyd to run my spider with python-scrapyd-api.

Some times my spider log only show below:

2014-11-12 07:40:59+0800 [FullInfo] DEBUG: Scraped from 200 http://www.indeed.com/jobtrends/industry?date=2010-08
        {'file_md5': '62aac088a1bc77d9abc3d32d92bf7168',
         'file_sha1': '50b625fe3d605bc27d601d1e1fe1c46ad2ebe39b',
         'file_size': 51722,
         'file_type': 'HTML document, ASCII text, with very long lines',
         'status_code': 200,
         'url_info': [{'http_status_code': 200,
                       'url': 'http://www.indeed.com/jobtrends/industry?date=2010-08',
                       'url_host': 'www.indeed.com',
                       'url_host_ip': '50.97.195.27'}]}
2014-11-12 07:40:59+0800 [FullInfo] INFO: Closing spider (finished)

You will see there is no 'Dumping Scrapy status'.

I have get nothing error message...

Why...?

P.s 
The pipelines close_spider function was never be called , then just hang there

**Comment by cathalgarvey** [comment]
Hey @AlanChien - I'm closing this as it's gone very stale, and it's marked as "not reproducible" since 2016. If you think it should remain open, by all means reopen it! But, before you do, please confirm that the issue still affects you on the most recent release or git-revision of Scrapy?

Thanks for contributing to Scrapy!
